### ISSUE TITLE
Error in local_add_canonizer

### ISSUE THREAD

**Issue by richardotis** [Theano/Theano#3600] opened 2015-11-04 17:17 UTC
I'm not entirely sure how to provide a reproducible example for this. I'll include the error here and maybe we can brainstorm the best way to serialize the problematic function graph for inspection. I can make the error go away by passing optimizer_excluding = local_add_canonizer. This error only seems to happen when I include terms which are big powers of variables, e.g., x^15 and x^-15.

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.RuntimeError'> maximum recursion depth exceeded while calling a Python object local_add_canonizer
ERROR: clients intersect!
  RCLIENTS of Elemwise{add,no_inplace}.0 [(Elemwise{add,no_inplace}(Elemwise{add,no_inplace}.0, TensorConstant{(1, 1, 1) of 0.0}), 0, <class 'theano.gof.graph.Apply'>, 139797783921104)]
  NCLIENTS of Elemwise{add,no_inplace}.0 [(Elemwise{add,no_inplace}(Elemwise{add,no_inplace}.0, TensorConstant{(1, 1, 1) of 0.0}), 0, <class 'theano.gof.graph.Apply'>, 139797783921104)]
ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR:theano.gof.opt:Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{add,no_inplace}.0, Elemwise{mul,no_inplace}.0)
ERROR:theano.gof.opt:node: Elemwise{add,no_inplace}(Elemwise{add,no_inplace}.0, Elemwise{mul,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR:theano.gof.opt:TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.revert(chk)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/toolbox.py", line 192, in revert
    f()
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/toolbox.py", line 146, in __call__
    reason=("Revert", self.reason))
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 541, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 315, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 442, in __import__
    self.__add_clients__(input, [(node, i)])
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 276, in __add_clients__
    assert not set(r.clients).intersection(set(new_clients))
AssertionError

ERROR:theano.gof.opt:Traceback (most recent call last):
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.revert(chk)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/toolbox.py", line 192, in revert
    f()
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/toolbox.py", line 146, in __call__
    reason=("Revert", self.reason))
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 541, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 315, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 442, in __import__
    self.__add_clients__(input, [(node, i)])
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/fg.py", line 276, in __add_clients__
    assert not set(r.clients).intersection(set(new_clients))
AssertionError
```

 ```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-841104f314e6> in <module>()
----> 1 get_ipython().magic(u"time eq = equilibrium(db_alfe, ['AL', 'FE', 'VA'], my_phases_alfe, {v.X('FE'): 0.23, v.T: (300, 1400, 10), v.P: [101325]})")
      2 print(eq)

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(*args,**kwargs)
   2258             return result
   2259 

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1165         else:
   1166             st = clock2()
-> 1167             exec(code, glob, local_ns)
   1168             end = clock2()
   1169             out = None

<timed exec> in <module>()

/home/rotis/git/pycalphad/pycalphad/core/equilibrium.pyc in equilibrium(dbf, comps, phases, conditions, **kwargs)
    108             out = out.xreplace({undef: float(0)})
    109         callable_dict[name], grad_callable_dict[name], hess_callable_dict[name] = \
--> 110             build_functions(out, [v.P, v.T], site_fracs)
    111 
    112         # Adjust gradient by the approximate chemical potentials

/home/rotis/git/pycalphad/pycalphad/core/theano_utils.pyc in build_functions(sympy_graph, indep_vars, site_fracs, broadcast_dims)
    117     grad, hess = _build_grad_hess(obj, flat_params, dims, nvars)
    118     ofunc = theano.function(tinputs, obj)
--> 119     gfunc = theano.function(tinputs, grad)
    120     hfunc = theano.function(tinputs, hess)
    121     return ofunc, gfunc, hfunc

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/compile/function.pyc in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    306                    on_unused_input=on_unused_input,
    307                    profile=profile,
--> 308                    output_keys=output_keys)
    309     # We need to add the flag check_aliased inputs if we have any mutable or
    310     # borrowed used defined inputs

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/compile/pfunc.pyc in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    524                          accept_inplace=accept_inplace, name=name,
    525                          profile=profile, on_unused_input=on_unused_input,
--> 526                          output_keys=output_keys)
    527 
    528 

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/compile/function_module.pyc in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1775                    profile=profile,
   1776                    on_unused_input=on_unused_input,
-> 1777                    output_keys=output_keys).create(
   1778             defaults)
   1779 

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/compile/function_module.pyc in __init__(self, inputs, outputs, mode, accept_inplace, function_builder, profile, on_unused_input, fgraph, output_keys)
   1455                         optimizer, inputs, outputs)
   1456                 else:
-> 1457                     optimizer_profile = optimizer(fgraph)
   1458 
   1459                 end_optimizer = time.time()

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in __call__(self, fgraph)
     99 
    100         """
--> 101         return self.optimize(fgraph)
    102 
    103     def add_requirements(self, fgraph):

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in optimize(self, fgraph, *args, **kwargs)
     87             orig = theano.tensor.basic.constant.enable
     88             theano.tensor.basic.constant.enable = False
---> 89             ret = self.apply(fgraph, *args, **kwargs)
     90         finally:
     91             theano.tensor.basic.constant.enable = orig

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in apply(self, fgraph)
    228             try:
    229                 t0 = time.time()
--> 230                 sub_prof = optimizer.optimize(fgraph)
    231                 l.append(float(time.time() - t0))
    232                 sub_profs.append(sub_prof)

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in optimize(self, fgraph, *args, **kwargs)
     87             orig = theano.tensor.basic.constant.enable
     88             theano.tensor.basic.constant.enable = False
---> 89             ret = self.apply(fgraph, *args, **kwargs)
     90         finally:
     91             theano.tensor.basic.constant.enable = orig

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in apply(self, fgraph, start_from)
   2209                         nb = change_tracker.nb_imported
   2210                         t_opt = time.time()
-> 2211                         lopt_change = self.process_node(fgraph, node, lopt)
   2212                         time_opts[lopt] += time.time() - t_opt
   2213                         if not lopt_change:

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in process_node(self, fgraph, node, lopt)
   1828             # will print a traceback as a warning.
   1829             if self.failure_callback is not None:
-> 1830                 self.failure_callback(e, self, repl_pairs, lopt, node)
   1831                 return False
   1832             else:

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in warn_inplace(exc, nav, repl_pairs, local_opt, node)
   1686         if isinstance(exc, InconsistencyError):
   1687             return
-> 1688         return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
   1689 
   1690     @staticmethod

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/opt.pyc in warn(exc, nav, repl_pairs, local_opt, node)
   1672             # We always crash on AssertionError because something may be
   1673             # seriously wrong if such an exception is raised.
-> 1674             raise exc
   1675 
   1676     @staticmethod

AssertionError: 
```

**Comment by nouiz** [comment] 2015-11-04 18:27
As this happen during compilation, you can give me easy access to a
replicable forme with this method:

http://www.deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

thanks

**Comment by richardotis** [comment] 2015-11-04 19:08
@nouiz Unfortunately...

```python
RuntimeError: maximum recursion depth exceeded while pickling an object
```

**Comment by nouiz** [comment] 2015-11-04 19:10
Execute this before calling function_dump:

import sys
sys.setrecursionlimit(10000)

**Comment by richardotis** [comment] 2015-11-04 19:21
Interestingly, setting the recursion limit allowed the compilation and calculation to successfully finish. I have the PKL file. How should I send it to you? GitHub doesn't let me upload files in this repo.

**Comment by nouiz** [comment] 2015-11-04 19:25
what about: https://gist.github.com/

If you have a web site, you could put it there too.

**Comment by richardotis** [comment] 2015-11-04 19:33
This should work: https://psu.box.com/shared/static/oy4k0kuuntxdpb9epcky2spsxwtjjg82.pkl

**Comment by nouiz** [comment] 2015-11-04 20:10
I'm able to reproduce it.

It also get fixed when I raise the stack trace.

This is a duplicate of gh-3341, so I'll close this issue. You can raise the stack limit until it get fixed.

thanks for the report.

**Closed by nouiz** 2015-11-04 20:10 UTC
