### ISSUE TITLE
New GPU backend: Memory problem when using different shapes

### ISSUE THREAD

**Issue by danielS91** [Theano/Theano#5382] opened 2017-01-03 18:37 UTC
I recently noticed a problem when calling a theano function multiple times with data of different shapes. The problem occurs only if I use the new gpu backend.

The following code helps to reproduce the problem:
```python
import numpy as np
import theano
from theano.tensor.nnet import conv2d

dtype = theano.config.floatX
filter_shape = (256, 3, 5, 5)

# theano graph
input_ = theano.tensor.tensor4()
filter_ = theano.shared(np.random.random(filter_shape).astype(dtype))
f = theano.function([input_], conv2d(input_, filter_))

# apply multiple times using different shapes
for i in range(100, 1000):
    shape = (1, 3, i, i)
    data = np.random.random(shape).astype(dtype)
    f(data)

```

Using the old backend (`THEANO_FLAGS='device=gpu'`), the memory usage goes back to the initial 800 MB after each call. Using the new backend (`THEANO_FLAGS='device=cuda'`), the memory blows up and I run in a out-of-memory-exception after 115 calls (GTX 970 with 4GB).

Edit: fixed copy&paste fault

**Comment by Sentient07** [comment] 2017-01-04 22:30
I'm not pretty sure if this would work, but could you try making the first call to the function outside the loop? Because in the new backend, the function compiles at the first call and hence I take a guess.

**Comment by khaotik** [comment] 2017-01-05 15:39
I'm able to reproduce the problem. Turing on/off `allow_gc` does not seem to help.

**Comment by danielS91** [comment] 2017-01-05 20:07
I think the problem is related to the memory handling and the freelist internally used by libgpuarray. So the memory needed is continuously increasing with each call and does not fit the allocated memory required for the previous call. If I just reverse the order in the loop (`range(100, 1000)[::-1]`) everything looks fine, except that the allocated memory is never deallocated. Using the old backend most of the gpu memory is deallocated after the last call.

**Comment by danielS91** [comment] 2017-01-07 19:09
I found a kind of workaround for this problem. Using the gpuarray flag for preallocation: `THEANO_FLAGS='gpuarray.preallocate=x` with x large enough for the largest shape avoids the problem.

**Comment by abergeron** [comment] 2017-01-23 18:01
The solution is to preallocate a large enough block of memory as @danielS91 says.

Alternatively you can disable the cache using `gpuarray.preallocate=-1`, but that will be slower.

**Comment by nouiz** [comment] 2017-01-24 17:53
I think we should extend the Memory error in the new back-end to have as a
hint to try this.

Otherwise, we will frequently have such user questions.

**Comment by danielS91** [comment] 2017-01-30 08:50
@abergeron that's a good hint especially for prototyping, thanks! An additional function to free/reset the already preallocated memory during programm execution would be nice. Especially for the case when you have a long overall execution time, but only the first part is using the GPU.

Since I know how to avoid the problem, I would close this issue. Ok?

**Comment by abergeron** [comment] 2017-01-30 18:30
I've made an issue with your suggestion: https://github.com/Theano/libgpuarray/issues/337

As the rest is "fixed" I'll close this.

**Closed by abergeron** 2017-01-30 18:30 UTC
