### ISSUE TITLE
nvcc fatal   : The version ('70000') of the host compiler ('Apple clang') is not supported

### ISSUE THREAD

**Issue by sinjax** [Theano/Theano#3415] opened 2015-09-21 15:15 UTC
Hello,

The latest updated (i assume) of clang seems to break theano/cuda.

Running the GPU test code found here: http://deeplearning.net/software/theano/tutorial/using_gpu.html
I get the error in this gist: https://gist.github.com/sinjax/728c223a034c95480d76

Note also that this error starts by printing out in the stderr the entire c file being compiled. Useful for debugging I'm sure but is there any way to turn this off?

As this seems to be a clang/cuda error rather than a theano error I feel i might be posting in the wrong place. But I thought I'd give it a shot, just in case anyone else has seen/solved this problem

Cheers

**Comment by nouiz** [comment] 2015-09-21 15:34
Thanks for letting us know about this problem. This could tell people to
not update clang for now!

I don't have a solution, maybe other people can help you. If you find the
solution, can you give it here?

I agree an option to display hide the error dump would be good. Do you want
to contribute this? It isn't hard.

**Comment by abergeron** [comment] 2015-09-21 16:58
For people upgrading to El Capitan in a couple of days (Sept 30), upgrading clang is not an option.  The old clang produces broken binaries when run on that version.

**Comment by sinjax** [comment] 2015-09-22 10:07
hmm yeah happy to make the change to the printing of code. The fixing it to work with the new clang might take me longer :) Where should i look for the code printing thing?

**Comment by njones920** [comment] 2015-10-03 12:09
Well thank goodness I stumbled over here. I was pulling my hair out trying to figure out why I was getting this issue. I guess I should have known better than move up to 10.11 and expect the newer LLVM version ( clang-700.0.72 ) to work. Back to Yosemite for the time being.

**Comment by pkpb1** [comment] 2015-10-05 03:05
I haven't upgraded to El Capitan yet.
I haven't upgraded to El Capitan yet. I started getting this error after updating Xcode from ver 6 to 7.  
It appears that the error is associated with Xcode.

**Comment by abergeron** [comment] 2015-10-05 18:00
Yes.  The problem is that Xcode 7 is not yet supported by nvcc.  But you have to use Xcode 7 if you use El Capitan since the older Xcode will not work properly.

**Comment by igsoft** [comment] 2015-10-06 06:42
This link in the Nvidia forum can be useful:
https://devtalk.nvidia.com/default/topic/879431/cuda-programming-and-performance/nvcc-amp-clang-7-no-typo-here-/

**Comment by pluskid** [comment] 2015-10-07 01:06
A very hacky solution is posted here: https://gist.github.com/zchee/7833bf67013e83523181

**Comment by nouiz** [comment] 2015-10-16 14:37
nvidia release a new version. So I'll close this issue. But https://github.com/Theano/Theano/issues/3518 tell that with that, there is many useless warning printed.

**Closed by nouiz** 2015-10-16 14:37 UTC
Labels: Mac

**Comment by sunil-at-gh** [comment] 2016-01-23 01:54
I had this problem on OS X 10.10. The following workaround seems to be working:
Install Xcode 6.2 int /Applications/Xcode_6_2.app
Set environment variable DEVELOPER_DIR=/Applications/Xcode_6_2.app/Contents/Developer.
This can be done in the current shell, to localize the effect.

**Comment by Sentient07** [comment] 2016-05-25 12:43
@nouiz I'm getting this same error. I have been using Apple LLVM version 7.3.0 (clang-703.0.29) and CUDA v 7.5.19. The last time i had ran the tests using GPU were before my exams and it was working perfectly fine. I'm not able to figure what went wrong. My Command line tool's version is 7.3.

**Comment by nouiz** [comment] 2016-05-25 12:54
Did you update CUDA or llvm/clang since them? My guess is that

@sentient07, did you try the work around suggested in this issue?

@abergeron, do you have an idea? Was this fixed?

Fred

**Comment by Sentient07** [comment] 2016-05-25 13:11
@nouiz I don't remember updating lvm/clang. From what i see, the fix of this would be to downgrade x-code, but i have installed command line tools without x-code.

**Comment by Sentient07** [comment] 2016-05-25 13:44
@sunil-at-gh Hey there. Could you please tell me your clang version ? :)

**Comment by sunil-at-gh** [comment] 2016-05-25 14:41
I had to download and install Xcode 6.2.
Then set the following env var (I created a shell script for running Theano):

DEVELOPER_DIR=/Applications/Xcode_6_2.app/Contents/Developer

_
Sunil

**Comment by Sentient07** [comment] 2016-05-25 19:14
@sunil-at-gh since I am not using x-code(I am using command line tool), I am not able to install the command line tool corresponding to x-code 6.2. The basic problem is, x-code and command line tool above certain version uses gcc v5.0, which isn't working with nvcc for some reason. 
I guess this thread has explained the reason. https://groups.google.com/forum/#!topic/theano-users/-N-W6GKL4eU
Thanks for your help! :)

**Comment by Sentient07** [comment] 2016-05-26 11:25
I have a fix without the necessity of x-code, with just using the command line tool. 
It did take sometime for me to install gcc-4.8 and link that as the default compiler. The gcc compiler of version > 5 doesn't work with nvcc compiler on OSX 10.11, on apple-darwin 15.4.0 kernel. 
So, if anyone is facing this problem, the fix would be to check if the version of gcc >= 4.9, if so install previous versions of gcc using home-brew( do not install gcc47 using home-brew as gcc-4.7 causes this [issue](https://github.com/Homebrew/homebrew-versions/issues/1007) on os 10.10 and 10.11). 
Then,  aliases in your `.bash_profile` file, 

```
alias gcc='gcc-4.8'
alias cc='gcc-4.8'
alias g++='g++-4.8'
alias c++='c++-4.8'
```
Now, linking the gcc by following these [steps](http://stackoverflow.com/a/20940521/3212998) helped me to use gcc 4.8. 
Also, i reinstalled BLAS and libgpuarray after shifting to the older compiler (Not sure if this should be done ) 
@nouiz  I think we need to update the docs, cautioning people not to install gcc > 4.8 and updating to x-code above 7.x.x.
