### ISSUE TITLE
FAIL: test_not_lazy_if_inplace (theano.sandbox.cuda.tests.test_opt.TestIfElse)

### ISSUE THREAD

**Issue by jmwoloso** [Theano/Theano#3730] opened 2015-12-03 15:54 UTC
Hello!

My setup:
Numpy 1.9.2
Scipy 0.15.1
GPU: NVIDIA GeForce GTX 860M
Linux Mint (17.2)
Bleeding Edge Theano (installed inside a virtual environment with access to global site packages)
NVIDIA Driver version: 346.46
CUDA 7.0

Contents of .theanorc file (device=cpu; specifically for testing obviously):
```
[global]
floatX=float32  
device=cpu
# force_device=True

[blas]
ldflags = -lmkl_rt

[cuda]
root = /usr/local/cuda-7.0
```

As the title says, that is the error I received. Here is the traceback:

```
Traceback (most recent call last):
  File "/home/jason/source/Theano/theano/tests/test_ifelse.py", line 70, in test_not_lazy_if_inplace
    self.assertFunctionContains1(f, IfElse(1))
  File "/home/jason/source/Theano/theano/tests/unittest_tools.py", line 109, in assertFunctionContains1
    return self.assertFunctionContains(f, op, min=1, max=1)
  File "/home/jason/source/Theano/theano/tests/unittest_tools.py", line 103, in assertFunctionContains
    str(op), len(matches), min, max)
AssertionError: ([GpuFromHost(y), GpuFromHost(x), GpuElemwise{add,no_inplace}(GpuFromHost.0, CudaNdarrayConstant{[ 1.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 2.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 3.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 4.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 5.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 6.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 7.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 8.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 9.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 10.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 11.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 12.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 13.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 14.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 15.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 16.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 17.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 18.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 19.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 20.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 21.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 22.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 23.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 24.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 25.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 26.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 27.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 28.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 29.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 30.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 31.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 32.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 33.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 34.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 35.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 36.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 37.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 38.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 39.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 40.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 41.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 42.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 43.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 44.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 45.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 46.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 47.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 48.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 49.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 50.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 51.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 52.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 53.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 54.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 55.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 56.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 57.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 58.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 59.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 60.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 61.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 62.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 63.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 64.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 65.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 66.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 67.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 68.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 69.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 70.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 71.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 72.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 73.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 74.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 75.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 76.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 77.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 78.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 79.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 80.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 81.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 82.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 83.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 84.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 85.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 86.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 87.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 88.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 89.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 90.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 91.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 92.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 93.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 94.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 95.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 96.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 97.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 98.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 99.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 100.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 101.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 102.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 103.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 104.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 105.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 106.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 107.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 108.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 109.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 110.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 111.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 112.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 113.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 114.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 115.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 116.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 117.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 118.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 119.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 120.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 121.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 122.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 123.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 124.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 125.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 126.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 127.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 128.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 129.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 130.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 131.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 132.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 133.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 134.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 135.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 136.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 137.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 138.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 139.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 140.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 141.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 142.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 143.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 144.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 145.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 146.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 147.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 148.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 149.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 150.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 151.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 152.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 153.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 154.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 155.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 156.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 157.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 158.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 159.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 160.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 161.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 162.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 163.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 164.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 165.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 166.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 167.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 168.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 169.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 170.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 171.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 172.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 173.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 174.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 175.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 176.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 177.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 178.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 179.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 180.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 181.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 182.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 183.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 184.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 185.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 186.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 187.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 188.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 189.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 190.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 191.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 192.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 193.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 194.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 195.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 196.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 197.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 198.]}), GpuElemwise{add,no_inplace}(GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{[ 199.]}), if{gpu}(c, GpuFromHost.0, GpuElemwise{add,no_inplace}.0), HostFromGpu(if{gpu}.0)], [], 'if{}', 0, 1, 1)

----------------------------------------------------------------------
Ran 19865 tests in 4627.586s

FAILED (SKIP=116, failures=2)
```
The second failure is below, though I believe the solution proposed in #3578 would take care of this (haven't tried it yet):
```
FAIL: theano.sandbox.cuda.tests.test_blas.test_downsample
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/source/Theano/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
AssertionError: Theano Assert failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/.virtualenvs/homesite/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/source/Theano/theano/sandbox/cuda/tests/test_blas.py", line 404, in test_downsample
    assert numpy.allclose(gg(), gg2()), shp
  File "/home/jason/source/Theano/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/jason/source/Theano/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/jason/.virtualenvs/homesite/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/jason/source/Theano/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
AssertionError: Theano Assert failed!
Apply node that caused the error: Assert{msg='Theano Assert failed!'}(GpuDownsampleFactorMaxGradGrad{ds=(2, 2), ignore_border=True}.0, Elemwise{eq,no_inplace}.0, Elemwise{eq,no_inplace}.0)
Toposort index: 11
Inputs types: [CudaNdarrayType(float32, 4D), TensorType(int8, scalar), TensorType(int8, scalar)]
Inputs shapes: [(10, 10, 5, 5), (), ()]
Inputs strides: [(250, 25, 5, 1), (), ()]
Inputs values: ['not shown', array(0, dtype=int8), array(0, dtype=int8)]
Outputs clients: [[GpuElemwise{Mul}[(0, 1)](CudaNdarrayConstant{[[[[ 2.]]]]}, Assert{msg='Theano Assert failed!'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```
Any suggestions are greatly appreciated. Thank you very much!

**Comment by nouiz** [comment] 2015-12-03 20:40
You can ignore the first one. It is a problem with the test. For the
second, I did earlier today a PR to fix it.

If I have the time, I'll fix the frist one today.

thanks

**Comment by nouiz** [comment] 2015-12-03 21:15
I did a fis here: https://github.com/Theano/Theano/pull/3731

**Comment by jmwoloso** [comment] 2015-12-04 07:43
Thank you for the very fast reply. I cloned the master again and the tests are running now, though I'm seeing a TON of errors and a few failures already. I'll post whatever output I can pull off of my terminal. I should have sent the output to a file, but I didn't expect that many errors etc, so hopefully I can capture the traceback.

**Comment by jmwoloso** [comment] 2015-12-04 18:15
Here is the most recent run.
[output.txt](https://github.com/Theano/Theano/files/52357/output.txt)

**Comment by lamblin** [comment] 2015-12-04 23:28
Oh, there seems to be an issue with the abstract convolution interface. That may be related to python3.
Hopefully I can have a look during the week end, I'll keep you updated.

**Comment by jmwoloso** [comment] 2015-12-05 17:04
No problem at all. You folks have fast service on these issues!

Sent from my Verizon Wireless 4G LTE DROID


Pascal Lamblin <notifications@github.com> wrote:


Oh, there seems to be an issue with the abstract convolution interface. That may be related to python3.
Hopefully I can have a look during the week end, I'll keep you updated.

**Comment by lamblin** [comment] 2015-12-06 03:59
I can confirm those are related to python3, as I can reproduce them on the same machine in a different virtualenv with python 3. I did not investigate further yet.

**Comment by jmwoloso** [comment] 2015-12-06 09:33
Alright, well at least I know I didn't mess up the configuration. It's weird though because it was working great in a python 3 virtualenv aside from the two errors I posted about originally.

Sent from my Verizon Wireless 4G LTE DROID


Pascal Lamblin <notifications@github.com> wrote:


I can confirm those are related to python3, as I can reproduce them on the same machine in a different virtualenv with python 3. I did not investigate further yet.

**Comment by jmwoloso** [comment] 2015-12-09 23:24
@lamblin If it helps, I believe I was using commit 663500a5ae18de5cee3ac2d644619a43a309049c when I found the original two failures I mentioned above, then I pulled down the latest after @nouiz mentioned the #3731 fix was added and that's when I started getting all of the errors and failures.

**Comment by lamblin** [comment] 2015-12-19 20:56
I believe the convolution issues should be fixed in the master, and the "ifelse" tests should be as well.
If you can confirm, we will close the issue.

**Comment by nouiz** [comment] 2015-12-21 18:59
I think all is fixed, so I'll close this issue. If not, comment on it again.

**Closed by nouiz** 2015-12-21 18:59 UTC

**Comment by jmwoloso** [comment] 2015-12-21 20:57
Awesome! I'll pull down the latest and try it again and let you know one way or the other.

**Comment by jmwoloso** [comment] 2015-12-22 03:38
This particular issue is solved. Thank you very much!
