### ISSUE TITLE
libgpuarray float64 

### ISSUE THREAD

**Issue by apulver** [Theano/Theano#4622] opened 2016-06-13 23:15 UTC
The following code warns about float64 when device=cuda0, but not when device=gpu0. Also, not all "cost" functions result in float64 (see comment in code). 

Incidentally, using the new backend sometimes yields very poor results when using the attached adam implementation, especially with RNNs. I haven't found a simple way to reproduce this problem, and most of the smaller tests I've tried seem to produce accurate results. 

```
import os
device = 'cuda1'
os.environ['THEANO_FLAGS'] = 'floatX=float32,device={},warn_float64=warn'.format(device)
import numpy as np
import theano
import theano.tensor as T

import adam
reload(adam)

x = T.fvector()
y = T.fscalar()
np.random.seed(123)
m = theano.shared(np.random.randn(2,2).astype(np.float32))

cost = (T.dot(x,m) - y).norm(L=2) # results in float64
#cost = x.norm(L=2) + m.norm(L=2) + y # does not result in float64
updates, _, _, _ = adam.adam_updates(cost, [m])

train = theano.function(inputs=[x,y],
                        outputs=cost,
                        updates=updates)

np.random.seed(123)
inv = np.random.randn(2).astype(np.float32)
np.random.seed(123)
ins = np.float32(np.random.randn())

z = train(inv,ins)
print inv, ins,z

```

```
# apulver
# Implementation of adam optimization

import numpy as np
import theano
import theano.tensor as T
from collections import OrderedDict

def adam_updates(cost,
                 params,
                 max_norm=None,
                 alpha=.001,
                 beta1=.9,
                 beta2=.999,
                 eps=1e-8):

    t = theano.shared(np.float64(1).astype(T.config.floatX))
    mt = [theano.shared(np.zeros_like(param.get_value(borrow=True)).astype(T.config.floatX)) for param in params]
    vt = [theano.shared(np.zeros_like(param.get_value(borrow=True)).astype(T.config.floatX)) for param in params]
    lr = theano.shared(np.float64(alpha).astype(T.config.floatX))

    updates = OrderedDict()

    grads = T.grad(cost, params, disconnected_inputs='warn')
    for m, v, param, grad in zip(mt, vt, params, grads):

        if max_norm is not None and max_norm is not False:
            grad_norm = grad.norm(L=2)
            grad = (T.minimum(max_norm, grad_norm)/ (grad_norm + eps)) * grad
        mc = beta1*m + (1.0-beta1)*grad
        vc = beta2*v + (1.0-beta2)*grad**2
        updates[m] = mc
        updates[v] = vc

        mh = m/(1.0 - beta1**t)
        vh = v/(1.0 - beta2**t)
        param_updates = param - alpha * mh / (T.sqrt(vh) + eps)
        updates[param] = param_updates
        updates[t] = t + 1

    return updates, mt, vt, lr
```

**Comment by nouiz** [comment] 2016-06-14 20:14
The float64 problem is fixed in this PR: https://github.com/Theano/Theano/pull/4628

**Comment by abergeron** [comment] 2016-06-14 20:16
For the poor results, can you try in the old backend and see if you still have problems?

If not, can you try and make a script that reproduces the problem (at least sometimes)?

**Comment by lamblin** [comment] 2017-06-09 01:30
We have fixed a couple of bugs in the new back-end since that time, so I'll close.

**Closed by lamblin** 2017-06-09 01:30 UTC
