### ISSUE TITLE
Assertion error when adding lots of variables

### ISSUE THREAD

**Issue by jsalvatier** [Theano/Theano#1960] opened 2014-07-14 08:31 UTC
This came up in PyMC: https://github.com/pymc-devs/pymc/issues/565

When adding a lot of variables, the user got an exception

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-86-b8e71cf7f204> in <module>()
      7         data = observations_flattened.iat[i, 2]
      8         var_name = 'result_%d_%d' % (student, topic)
----> 9         pm.Normal(var_name, mu=skills_means[student, topic], tau=skills_precisions[student, topic], observed=data)
     10 #        if student % 10 == 0 and topic == 0:
     11 #            print('Added student %d' % student, flush=True)

/usr/local/lib/python3.4/dist-packages/theano/tensor/var.py in __getitem__(self, args)
    408                 return theano.tensor.subtensor.Subtensor(args)(
    409                     self, *theano.tensor.subtensor.Subtensor.collapse(args,
--> 410                     lambda entry: isinstance(entry, Variable)))
    411 
    412     def take(self, indices, axis=None, mode='raise'):

/usr/local/lib/python3.4/dist-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    458                 # compute output value once with test inputs to validate graph
    459                 thunk = node.op.make_thunk(node, storage_map, compute_map,
--> 460                         no_recycling=[])
    461                 thunk.inputs = [storage_map[v] for v in node.inputs]
    462                 thunk.outputs = [storage_map[v] for v in node.outputs]

/usr/local/lib/python3.4/dist-packages/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
    616                 logger.debug('Trying CLinker.make_thunk')
    617                 outputs = cl.make_thunk(input_storage=node_input_storage,
--> 618                                         output_storage=node_output_storage)
    619                 fill_storage, node_input_filters, node_output_filters = outputs
    620 

/usr/local/lib/python3.4/dist-packages/theano/gof/cc.py in make_thunk(self, input_storage, output_storage, keep_lock)
    963         cthunk, in_storage, out_storage, error_storage = self.__compile__(
    964             input_storage, output_storage,
--> 965             keep_lock=keep_lock)
    966 
    967         res = _CThunk(cthunk, init_tasks, tasks, error_storage)

/usr/local/lib/python3.4/dist-packages/theano/gof/cc.py in __compile__(self, input_storage, output_storage, keep_lock)
    906                                     input_storage,
    907                                     output_storage,
--> 908                                     keep_lock=keep_lock)
    909         return (thunk,
    910                 [link.Container(input, storage) for input, storage in

/usr/local/lib/python3.4/dist-packages/theano/gof/cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, keep_lock)
   1343         else:
   1344             module = get_module_cache().module_from_key(
-> 1345                 key=key, fn=self.compile_cmodule_by_step, keep_lock=keep_lock)
   1346 
   1347         vars = self.inputs + self.outputs + self.orphans

/usr/local/lib/python3.4/dist-packages/theano/gof/cmodule.py in module_from_key(self, key, fn, keep_lock, key_data)
    976                         # versioned modules.
    977                         try:
--> 978                             key_data.add_key(key, save_pkl=bool(_version))
    979                             key_broken = False
    980                         except pickle.PicklingError:

/usr/local/lib/python3.4/dist-packages/theano/gof/cmodule.py in add_key(self, key, save_pkl)
    457     def add_key(self, key, save_pkl=True):
    458         """Add a key to self.keys, and update pickled file if asked to."""
--> 459         assert key not in self.keys
    460         self.keys.add(key)
    461         if save_pkl:

AssertionError: 
```

Any idea what that's about?

**Comment by nouiz** [comment] 2015-02-12 17:20
Do you have code that reproduce it? In the pymc issue, the code is partial.

If we have a way to reproduce it, I'll close the ticket.

thanks

**Comment by abergeron** [comment] 2015-02-12 18:51
I think you mean: "If we don't get a way to reproduce this, I'll close the ticket".  Because otherwise it can be confusing.

**Comment by kabishop** [comment] 2015-03-12 01:08
Hi, I just got this error as well. I was attempting to duplicate an ARIMA model I found here: http://zinkov.com/posts/2012-06-27-why-prob-programming-matters/

The code I'm trying to use is:
```
with pymc3.Model() as model:
    L1 = pymc3.Uniform('L1',-1000000,1000000)
    MA1 = pymc3.Uniform('MA1',-1000000,1000000)
    sigma = pymc3.Uniform('sigma',0,1000000)

    ys = []
    errors = [0]
    for i in range(1,len(dccu)):
        mu = L1*dccu[i-1] + MA1*errors[i-1]
        ys.append( pymc3.Normal('y{}'.format(i),mu=mu,sd=sigma,observed=dccu[i]) )
        errors.append( dccu[i] - mu )
```

I wanted to let this run to set up first and was just writing it in iPython so I'm not even sure if it's a valid model yet.

The trackback I got was:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-184-fe635c010270> in <module>()
      7     errors = [0]
      8     for i in range(1,len(dccu)):
----> 9         mu = L1*dccu[i-1] + MA1*errors[i-1]
     10         ys.append( pymc3.Normal('y{}'.format(i),mu=mu,sd=sigma,observed=dccu[i]) )
     11         errors.append( dccu[i] - mu )

/usr/lib64/python3.4/site-packages/theano/tensor/var.py in __mul__(self, other)
    153         # and the return value in that case
    154         try:
--> 155             return theano.tensor.mul(self, other)
    156         except (NotImplementedError, AsTensorError):
    157             return NotImplemented

/usr/lib64/python3.4/site-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    552                 # compute output value once with test inputs to validate graph
    553                 thunk = node.op.make_thunk(node, storage_map, compute_map,
--> 554                         no_recycling=[])
    555                 thunk.inputs = [storage_map[v] for v in node.inputs]
    556                 thunk.outputs = [storage_map[v] for v in node.outputs]

/usr/lib64/python3.4/site-packages/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
   1000         self.update_self_openmp()
   1001         return super(OpenMPOp, self).make_thunk(node, storage_map,
-> 1002                                                 compute_map, no_recycling)
   1003 
   1004 

/usr/lib64/python3.4/site-packages/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
    737                 logger.debug('Trying CLinker.make_thunk')
    738                 outputs = cl.make_thunk(input_storage=node_input_storage,
--> 739                                         output_storage=node_output_storage)
    740                 fill_storage, node_input_filters, node_output_filters = outputs
    741 

/usr/lib64/python3.4/site-packages/theano/gof/cc.py in make_thunk(self, input_storage, output_storage, keep_lock)
   1070         cthunk, in_storage, out_storage, error_storage = self.__compile__(
   1071             input_storage, output_storage,
-> 1072             keep_lock=keep_lock)
   1073 
   1074         res = _CThunk(cthunk, init_tasks, tasks, error_storage)

/usr/lib64/python3.4/site-packages/theano/gof/cc.py in __compile__(self, input_storage, output_storage, keep_lock)
   1012                                     input_storage,
   1013                                     output_storage,
-> 1014                                     keep_lock=keep_lock)
   1015         return (thunk,
   1016                 [link.Container(input, storage) for input, storage in

/usr/lib64/python3.4/site-packages/theano/gof/cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, keep_lock)
   1439         else:
   1440             module = get_module_cache().module_from_key(
-> 1441                 key=key, lnk=self, keep_lock=keep_lock)
   1442 
   1443         vars = self.inputs + self.outputs + self.orphans

/usr/lib64/python3.4/site-packages/theano/gof/cmodule.py in module_from_key(self, key, lnk, keep_lock)
   1052         # Is the source code already in the cache?
   1053         module_hash = get_module_hash(src_code, key)
-> 1054         module = self._get_from_hash(module_hash, key, keep_lock=keep_lock)
   1055         if module is not None:
   1056             return module

/usr/lib64/python3.4/site-packages/theano/gof/cmodule.py in _get_from_hash(self, module_hash, key, keep_lock)
    955             with compilelock.lock_ctx(keep_lock=keep_lock):
    956                 try:
--> 957                     key_data.add_key(key, save_pkl=bool(key[0]))
    958                     key_broken = False
    959                 except pickle.PicklingError:

/usr/lib64/python3.4/site-packages/theano/gof/cmodule.py in add_key(self, key, save_pkl)
    462     def add_key(self, key, save_pkl=True):
    463         """Add a key to self.keys, and update pickled file if asked to."""
--> 464         assert key not in self.keys
    465         self.keys.add(key)
    466         if save_pkl:

AssertionError: 
```

I added a print(i) to the end of it and it ran through the loop 391 times each time I ran it. I occasionally get a

```
INFO (theano.gof.compilelock): Refreshing lock /home/kbishop/.theano/compiledir_Linux-3.18-sabayon-x86_64-Intel-R-_Core-TM-_i7-4770K_CPU_@_3.50GHz-with-gentoo-2.2-Intel_R_Core_TM_i7-4770K_CPU_@_3.50GHz-3.4.2-64/lock_dir/lock
INFO:theano.gof.compilelock:Refreshing lock /home/kbishop/.theano/compiledir_Linux-3.18-sabayon-x86_64-Intel-R-_Core-TM-_i7-4770K_CPU_@_3.50GHz-with-gentoo-2.2-Intel_R_Core_TM_i7-4770K_CPU_@_3.50GHz-3.4.2-64/lock_dir/lock
```
before crashing.

**Comment by nouiz** [comment] 2015-03-12 14:27
We are currently pretty busy and we probably can't look at it rapidly. But
can you give us exact instruction to reproduce this with the code? That
way, when we have the time, we will be able to reproduce it.

Also, how it crash? What is the full error message?

The INFO about the lock can be ignored. It just mean there is many process
that try to compile at the same time.

**Comment by nouiz** [comment] 2015-11-03 20:25
fixed by https://github.com/Theano/Theano/pull/3532

**Comment by nouiz** [comment] 2015-11-04 01:28
I'm reopen as the fix was for something similar, but I'm not sure this is the same for this ticket.

Can one of you reproduce it? The current code is partial and don't allow me to try to reproduce it.

In the code in a comment here, the variable dccu, errors and mu aren't defined and I'm not sure what they should be.

**Comment by nouiz** [comment] 2017-01-13 15:22
As this wasn't reported for over a year and I don't know how to replicate this, I'm closing this issue.

**Closed by nouiz** 2017-01-13 15:22 UTC
Labels: Crash

**Comment by tollybe** [comment] 2020-11-11 15:26
Hi guys! I'm running into issues with the pymc3 again

You can reproduce the error here in the first initial model (at [9]) in https://docs.pymc.io/notebooks/multilevel_modeling.html

Running on PyMC3 v3.9.3
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Theano: v1.0.5
____

with pm.Model(coords=coords) as pooled_model:
    floor_idx = pm.Data("floor_idx", floor, dims="obs_id")
    a = pm.Normal("a", 0.0, sigma=10.0, dims="Level")

    theta = a[floor_idx]
    sigma = pm.Exponential("sigma", 1.0)

    y = pm.Normal("y", theta, sigma=sigma, observed=log_radon, dims="obs_id")

pm.model_to_graphviz(pooled_model)


---------------------------------------------------------------------------
```
ImportError                               Traceback (most recent call last)
<ipython-input-10-3ff6fa752afa> in <module>
      1 with pm.Model(coords=coords) as pooled_model:
----> 2     floor_idx = pm.Data("floor_idx", floor, dims="obs_id")
      3     a = pm.Normal("a", 0.0, sigma=10.0, dims="Level")
      4 
      5     theta = a[floor_idx]

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pymc3\data.py in __new__(self, name, value, dims, export_index_as_coords)
    545         # To draw the node for this variable in the graphviz Digraph we need
    546         # its shape.
--> 547         shared_object.dshape = tuple(shared_object.shape.eval())
    548         if dims is not None:
    549             shape_dims = model.shape_from_dims(dims)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\tensor\var.py in <lambda>(self)
    285             return theano.tensor.basic.transpose(self, axes)
    286 
--> 287     shape = property(lambda self: theano.tensor.basic.shape(self))
    288 
    289     size = property(lambda self: self.shape[0] if self.ndim == 1 else

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\op.py in __call__(self, *inputs, **kwargs)
    667 
    668                 # compute output value once with test inputs to validate graph
--> 669                 thunk = node.op.make_thunk(node, storage_map, compute_map,
    670                                            no_recycling=[])
    671                 thunk.inputs = [storage_map[v] for v in node.inputs]

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    952                               compute_map=compute_map, impl='c')
    953             try:
--> 954                 return self.make_c_thunk(node, storage_map, compute_map,
    955                                          no_recycling)
    956             except (NotImplementedError, utils.MethodNotDefined):

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    855                 raise NotImplementedError("float16")
    856         _logger.debug('Trying CLinker.make_thunk')
--> 857         outputs = cl.make_thunk(input_storage=node_input_storage,
    858                                 output_storage=node_output_storage)
    859         thunk, node_input_filters, node_output_filters = outputs

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py in make_thunk(self, input_storage, output_storage, storage_map, keep_lock)
   1213         """
   1214         init_tasks, tasks = self.get_init_tasks()
-> 1215         cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
   1216             input_storage, output_storage, storage_map,
   1217             keep_lock=keep_lock)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py in __compile__(self, input_storage, output_storage, storage_map, keep_lock)
   1151         input_storage = tuple(input_storage)
   1152         output_storage = tuple(output_storage)
-> 1153         thunk, module = self.cthunk_factory(error_storage,
   1154                                             input_storage,
   1155                                             output_storage,

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map, keep_lock)
   1621             for node in self.node_order:
   1622                 node.op.prepare_node(node, storage_map, None, 'c')
-> 1623             module = get_module_cache().module_from_key(
   1624                 key=key, lnk=self, keep_lock=keep_lock)
   1625 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py in module_from_key(self, key, lnk, keep_lock)
   1187             try:
   1188                 location = dlimport_workdir(self.dirname)
-> 1189                 module = lnk.compile_cmodule(location)
   1190                 name = module.__file__
   1191                 assert name.startswith(location)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py in compile_cmodule(self, location)
   1518         try:
   1519             _logger.debug("LOCATION %s", str(location))
-> 1520             module = c_compiler.compile_str(
   1521                 module_name=mod.code_hash,
   1522                 src_code=src_code,

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2418             open(os.path.join(location, "__init__.py"), 'w').close()
   2419             assert os.path.isfile(lib_filename)
-> 2420             return dlimport(lib_filename)
   2421 
   2422 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py in dlimport(fullpath, suffix)
    315             warnings.filterwarnings("ignore",
    316                                     message="numpy.ndarray size changed")
--> 317             rval = __import__(module_name, {}, {}, [module_name])
    318         t1 = time.time()
    319         import_time += t1 - t0

ImportError: DLL load failed while importing mf0c597995cda5a5ddd6f2023fd9404c7f21824ed4f7f0d5318dee29bd7fd2b7c: The specified module could not be found.
```
