### ISSUE TITLE
Catch  bug in Theano dev version

### ISSUE THREAD

**Issue by jcyk** [Theano/Theano#3684] opened 2015-11-25 12:01 UTC
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.Exception'> Constant{0} is already owned by another fgraph local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(for{cpu,grad_of_scan_fn}.21)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 592, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 530, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 363, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 394, in __import__
    raise Exception("%s is already owned by another fgraph" % r)
Exception: Constant{0} is already owned by another fgraph

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.Exception'> Constant{0} is already owned by another fgraph local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(for{cpu,grad_of_scan_fn}.19)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 592, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 530, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 363, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 394, in __import__
    raise Exception("%s is already owned by another fgraph" % r)
Exception: Constant{0} is already owned by another fgraph

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.Exception'> Constant{0} is already owned by another fgraph local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(for{cpu,grad_of_scan_fn}.21)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 592, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 530, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 363, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 394, in __import__
    raise Exception("%s is already owned by another fgraph" % r)
Exception: Constant{0} is already owned by another fgraph

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.Exception'> Constant{0} is already owned by another fgraph local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(for{cpu,grad_of_scan_fn}.19)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 592, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 530, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 363, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 394, in __import__
    raise Exception("%s is already owned by another fgraph" % r)
Exception: Constant{0} is already owned by another fgraph

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'>  local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(for{cpu,grad_of_scan_fn}.21)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 591, in replace
    assert (node == 'output' and self.outputs[i] is r) or (node.inputs[i] is r)
AssertionError

Traceback (most recent call last):
  File "train.py", line 3, in <module>
    train_model()
  File "/Users/jcyk/Desktop/CWS/model.py", line 225, in train_model
    f_update = theano.function([T_x,T_dropout,T_y,T_yy,T_y_mask,T_yy_mask],T_cost,updates=T_updates)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    output_keys=output_keys).create(
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1457, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 2211, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1830, in process_node
    self.failure_callback(e, self, repl_pairs, lopt, node)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1688, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1674, in warn
    raise exc
AssertionError

**Comment by nouiz** [comment] 2015-11-26 21:55
Duplicate of https://github.com/Theano/Theano/issues/3663.

I have a way to reproduce it. It was working a few week ago, so you could revert Theano dev version of a few week in the mean time.

thanks for the report.

**Closed by nouiz** 2015-11-26 21:55 UTC

**Comment by bourbakimember** [comment] 2015-11-30 01:53
@nouiz @jcyk What is the best dev version to revert to?

Thanks!

**Comment by yunqiw** [comment] 2015-11-30 22:52
Hi, I am new to Theano, but how can I revert the version? My program works fine around one month ago, but it is not working now. I have reported the issume at #3707

**Comment by jcyk** [comment] 2015-12-01 07:25
@yunqiw @bourbakimember I don't know which one is the best ,but some version works fine for me .
You can install a specific git commit by using the bleeding edge instruction and adding @COMMIT_ID to the pip command like:
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git@COMMIT_ID

And I don't remember the commit_Id of the version I am using currently.  just try some  COMMIT_IDs lies on the right of  https://github.com/Theano/Theano/commits/master .
Hope that will help.

**Comment by yunqiw** [comment] 2015-12-01 18:00
@jcyk Thank you so much, I actually was able to find the version I downloaded before that worked with my code.
