### ISSUE TITLE
flake8 theano/tests/*.py

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4059] opened 2016-02-15 18:35 UTC

**Comment by fvisin** [comment] 2016-02-15 20:09
This ticket is to fix all the PEP8 errors. This includes making sure that all the functions and classes have comprehensible and exhaustive docstrings.

**Comment by abergeron** [comment] 2016-03-07 16:38
I just realized, but this is Chibeb's ticket.  Why do you have someone working on this?

**Comment by fvisin** [comment] 2016-03-07 16:42
@abergeron if you are asking me, I only commented on the things to do (I pasted the same text on all the flake8 tickets) but I have no one working on it. We should probably specify when someone is working on a ticket to prevent external people from working on it.

**Comment by AnishShah** [comment] 2016-03-07 16:43
There was no interaction on this ticket. So I thought no one is working on this. And since, this is an easy issue. I made the changes and created a PR. If anyone was already working, then I'm extremely sorry. I will close my PR.

**Comment by abergeron** [comment] 2016-03-07 18:20
No it's ok, it not already fixed yet, so we'll just take one of the two PRs

**Comment by abergeron** [comment] 2016-03-07 18:26
Also for the future, issues that are tagged CCW will usually be assigned to someone by us.  If you want to work on one, it's not a problem, but it can help to ask if the issue is assigned to avoid duplicating work.

**Comment by abergeron** [comment] 2016-03-14 17:13
Closed by #4144

**Closed by abergeron** 2016-03-14 17:13 UTC
Labels: CCW
