### ISSUE TITLE
Bug: IfElse evaluates both conditions in some cases

### ISSUE THREAD

**Issue by matthias-k** [Theano/Theano#3793] opened 2015-12-17 20:39 UTC
Hi,

I am experiencing strange behaviour in theano. I am implemented a gaussian convolution with behaves like `mode='nearest'` in scipy. To save time, I check with an `ifelse` wether the kernel size is actually greater than zero return the input otherwise. I noticed that in some special cases the convolution is calculated anyway, without ever using it. Here is my minimal example:

```python
import numpy as np

import theano
import theano.tensor as T
import theano.ifelse

def gaussian_filter_1d(input, sigma, window_radius = 40):
    """
    Filter 1d input with a Gaussian using mode `nearest`.

    input is expected to be three dimensional of type n times x times y
    """

    # Construction of 1d kernel
    filter_1d = T.arange(2*window_radius + 1) - window_radius

    filter_1d = T.exp(-0.5*filter_1d**2/sigma**2)
    filter_1d = filter_1d / filter_1d.sum()
    filter_1d = filter_1d.astype(input.dtype)

    blur_input = input.dimshuffle(['x', 'x','x', 0])
    filter_W = filter_1d.dimshuffle(['x','x','x',0])

    # Construction of filter pipeline
    blur_input_start = blur_input[:, :, :, :1]
    blur_input_start_padding = T.repeat(blur_input_start, window_radius, axis=3)
    blur_input_end = blur_input[:, :, :, -1:]
    blur_input_end_padding = T.repeat(blur_input_end, window_radius, axis=3)
    
    padded_input = T.concatenate([blur_input_start_padding, blur_input, blur_input_end_padding], axis=3)
    
    blur_op = T.nnet.conv2d(padded_input, filter_W, border_mode='valid', filter_shape=[1, 1, 1, None])
    return blur_op[0, 0, 0, :]

X = T.vector('X')
sigma = theano.shared(0.0, name='sigma')
apply_blur = T.gt(sigma, 0.0)

blur = gaussian_filter_1d(X, sigma)
out = theano.ifelse.ifelse(apply_blur, blur, X)
out = out/out.sum()

f = theano.function([X], out, profile=True)
X_data = np.random.randn(10000000)
f(X_data);
f.profile.summary()
```
The profile shows that the convolution is executed, of course leading to a massive speed penalty (interestingly, the bug is not present if I remove the line `out = out/out.sum()`):

```
Function profiling
==================
  Message: <ipython-input-2-95241e38ca15>:43
  Time in 1 calls to Function.__call__: 5.835893e+00s
  Time in Function.fn.__call__: 5.835533e+00s (99.994%)
  Time in thunks: 5.832838e+00s (99.948%)
  Total compile time: 2.700269e-01s
    Number of Apply nodes: 32
    Theano Optimizer time: 2.191091e-01s
       Theano validate time: 6.579399e-03s
    Theano Linker time (includes C, CUDA code generation/compiling): 3.559184e-02s
       Import time 7.619858e-04s

Time in all call to theano.grad() 0.000000e+00s
Time since theano import 29.530s
Class
---
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  97.6%    97.6%       5.692s       5.69e+00s     C        1       1   theano.tensor.nnet.corr.CorrMM
   0.8%    98.4%       0.047s       2.37e-02s     Py       2       1   theano.ifelse.IfElse
   0.8%    99.1%       0.044s       4.39e-02s     C        1       1   theano.tensor.basic.Join
   0.5%    99.6%       0.028s       3.09e-03s     C        9       9   theano.tensor.elemwise.Elemwise
   0.4%   100.0%       0.022s       1.10e-02s     C        2       2   theano.tensor.elemwise.Sum
   0.0%   100.0%       0.000s       1.29e-05s     C        4       4   theano.tensor.subtensor.Subtensor
   0.0%   100.0%       0.000s       7.25e-06s     C        7       7   theano.tensor.elemwise.DimShuffle
   0.0%   100.0%       0.000s       1.56e-05s     C        2       2   theano.tensor.basic.Alloc
   0.0%   100.0%       0.000s       4.05e-06s     C        2       2   theano.tensor.basic.Reshape
   0.0%   100.0%       0.000s       3.93e-06s     C        2       2   theano.tensor.opt.MakeVector
   0.0%   100.0%       0.000s       5.96e-06s     C        1       1   theano.compile.ops.Shape_i
   ... (remaining 0 Classes account for   0.00%(0.00s) of the runtime)

```

The linker is `cvm`. The bug is present in 0.7.0 and in master as of today. If you need any other information, I will be happy to provide it.

**Comment by lamblin** [comment] 2015-12-17 22:25
Thanks for the report and the example. This is a duplicate of #3004, so I'll close the ticket.
For a workaround, you can try to disable inplace operations, or maybe insert explicitly a DeepCopyOp to avoid memory reuse between branches (maybe on X, blur, or out). Swapping the "then" and "else" branches and inverting the condition might help as well.

**Closed by lamblin** 2015-12-17 22:25 UTC
