### ISSUE TITLE
dnn_pool `average_exc_pad` mode is broken?

### ISSUE THREAD

**Issue by ebenolson** [Theano/Theano#3776] opened 2015-12-13 19:03 UTC
Test code:

    import numpy as np
    import theano.tensor as T
    from theano.sandbox.cuda.dnn import dnn_pool

    X = T.tensor4()
    pooled = dnn_pool(X, ws=(2, 2), stride=(1, 1), mode='average_exc_pad', pad=(1,1))
    output = pooled.eval({X: np.ones((1, 1, 3, 3)).astype('float32')})
    print np.array(output)

Output:

       [[[[ 0.25  0.5   1.     inf]
       [ 0.5   1.    2.     inf]
       [ 1.    2.    4.     inf]
       [  inf   inf   inf   inf]]]]

I found this description which seems to match the behavior, so maybe this is a cuDNN issue?
https://github.com/JuliaGPU/CUDNN.jl/blob/master/src/CUDNN.jl#L401

**Comment by lamblin** [comment] 2015-12-17 22:45
This looks indeed like a CuDNN issue. I'm able to reproduce those numbers, and they do not make sense to me.

**Comment by f0k** [comment] 2015-12-18 11:43
Same numbers here. I've sent an email to Nvidia about it (CC'ing both of you).

**Comment by f0k** [comment] 2015-12-18 19:19
Philippe Vandermersch from Nvidia said it should be fixed in cuDNN v4. It seems I cannot run that code in cuDNN v4, though. Replaced v3 by v4, updated to the latest Theano master, removed my compiledir, and get:
```
In [1]: import theano
Using gpu device 0: GeForce GT 640 (CNMeM is disabled)

In [2]: theano.sandbox.cuda.dnn.dnn_available()
Out[2]: True

...

In [8]: output = pooled.eval({X: np.ones((1, 1, 3, 3)).astype('float32')})
...
RuntimeError: ('The following error happened while compiling the node', GpuDnnPool(GpuContiguous.0, GpuDnnPoolDesc{ws=(2, 2), stride=(1, 1), mode='average_exc_pad', pad=(1, 1)}.0), '\n', 'could not create cuDNN handle: CUDNN_STATUS_NOT_INITIALIZED', '[GpuDnnPool(<CudaNdarrayType(float32, 4D)>, <CDataType{cudnnPoolingDescriptor_t}>)]')
```

Is there something not fully updated for cuDNN v4 in Theano? It's the same when I try to run the Lasagne MNIST example.

**Comment by nouiz** [comment] 2015-12-18 19:38
We merged yesterday the support for v4. When did you update Theano? I
suppose today, but if not that would explain this.

Be sure to delete or call theano-cache purge, calling "theano-cache clean"
infrequently cause problems.

Be sure to delete, not just move the v3 stuff. If there is conflict, this
cause this type of problem. Can you install it again? How did you installed
v4?

**Comment by f0k** [comment] 2015-12-18 19:54
I updated Theano right before posting, and I ran `rm -r ~/.theano/compile*`. I deleted the cuDNN v3 `.so` files and extracted the v4 files into `/usr/local` (so they end up in the correct places in `/usr/local/cuda/*` and the header file is overwritten). Note that `dnn_available()` returns `True`, so obviously it is found correctly. `theano.sandbox.cuda.dnn.version()` returns `(4004, 4004)`. No idea... I can try rebooting or testing it on one of our servers, but not today!
It would just be good to know if Eben's example code above produces the correct results with v4 so we can close this issue.

**Comment by lamblin** [comment] 2015-12-18 21:32
I managed to test with v4, and the bug is indeed fixed for the reasonable cases. When padding >= window size, averaging excluding everything would give `nan` or `0`, but that's not unexpected.

The limitation of padding (and the difference with `ignore_border`) is that padding is symmetrical. It would be possible to add a full window size to padding, and then take a subtensor, but I don't think it is worth it.

```python
>>> theano.sandbox.cuda.dnn.version()
(4004, 4004)

>>> print np.asarray(dnn_pool(np.ones((1,1,3,3), np.float32), ws=(2,2), stride=(1,1), mode='average_exc_pad', pad=(1,1)).eval())
[[[[ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]]]]

>>> print np.asarray(dnn_pool(np.ones((1,1,3,3), np.float32), ws=(2,2), stride=(1,1), mode='average_exc_pad', pad=(2,2)).eval())
[[[[ nan  nan  nan  nan  nan  nan]
   [ nan   1.   1.   1.   1.  nan]
   [ nan   1.   1.   1.   1.  nan]
   [ nan   1.   1.   1.   1.  nan]
   [ nan   1.   1.   1.   1.  nan]
   [ nan  nan  nan  nan  nan  nan]]]]

>>> print np.asarray(dnn_pool(np.ones((1,1,3,3), np.float32), ws=(2,2), stride=(1,1), mode='average_exc_pad', pad=(3,3)).eval())
[[[[  0.  nan  -0.  -0.  -0.  -0.  nan   0.]
   [ nan  nan  nan  nan  nan  nan  nan  nan]
   [ -0.  nan   1.   1.   1.   1.  nan  -0.]
   [ -0.  nan   1.   1.   1.   1.  nan  -0.]
   [ -0.  nan   1.   1.   1.   1.  nan  -0.]
   [ -0.  nan   1.   1.   1.   1.  nan  -0.]
   [ nan  nan  nan  nan  nan  nan  nan  nan]
   [  0.  nan  -0.  -0.  -0.  -0.  nan   0.]]]]

```

**Comment by nouiz** [comment] 2016-01-30 04:02
We disabled average_exc_pad for cuddn v3, so I'm closing this issue. It will work with cudnn v4 rc.

**Closed by nouiz** 2016-01-30 04:02 UTC
