### ISSUE TITLE
true_div(2**64, 1.) raises OverflowError

### ISSUE THREAD

**Issue by richardotis** [Theano/Theano#3577] opened 2015-10-29 22:16 UTC
This is with optimizer=None and floatX=float64 on master (as of a few hours ago at least).
```python
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-29-74ae6444993b> in <module>()
      2 import theano.tensor as tt
      3 
----> 4 x = tt.true_div(2**64, 1.)

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/gof/op.pyc in __call__(self, *inputs, **kwargs)
    598         """
    599         return_list = kwargs.pop('return_list', False)
--> 600         node = self.make_node(*inputs, **kwargs)
    601 
    602         if config.compute_test_value != 'off':

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/tensor/elemwise.pyc in make_node(self, *inputs)
    540         using DimShuffle.
    541         """
--> 542         inputs = list(map(as_tensor_variable, inputs))
    543         shadow = self.scalar_op.make_node(
    544             *[get_scalar_type(dtype=i.type.dtype).make_variable()

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/tensor/basic.pyc in as_tensor_variable(x, name, ndim)
    200 
    201     try:
--> 202         return constant(x, name=name, ndim=ndim)
    203     except TypeError:
    204         try:

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/tensor/basic.pyc in constant(x, name, ndim, dtype)
    420 def constant(x, name=None, ndim=None, dtype=None):
    421     ret = constant_or_value(x, rtype=TensorConstant, name=name, ndim=ndim,
--> 422                             dtype=dtype)
    423 
    424     # We create a small cache of frequently used constant.

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/tensor/basic.pyc in constant_or_value(x, rtype, name, ndim, dtype)
    373                 # This is to imitate numpy behavior which tries to fit
    374                 # bigger numbers into a uint64.
--> 375                 x_ = theano._asarray(x, dtype='uint64')
    376         elif rtype is TensorConstant and isinstance(x, float):
    377             x_ = autocast_float(x)

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/theano/misc/safe_asarray.pyc in _asarray(a, dtype, order)
     31         dtype = theano.config.floatX
     32     dtype = numpy.dtype(dtype)  # Convert into dtype object.
---> 33     rval = numpy.asarray(a, dtype=dtype, order=order)
     34     # Note that dtype comparison must be done by comparing their `num`
     35     # attribute. One cannot assume that two identical data types are pointers

/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    472 
    473     """
--> 474     return array(a, dtype, copy=False, order=order)
    475 
    476 def asanyarray(a, dtype=None, order=None):

OverflowError: Python int too large to convert to C long
```

**Comment by nouiz** [comment] 2015-10-30 13:03
2**64 = 18446744073709551616L

This do not fix in int64 or uint64. The number is to big to be represented by NumPy. As use the same dtype as numpy, so we have the same restriction. If you want to use Python bigint, NumPy and Theano won't be very useful to you. You can use Python direction or check for other project that have a support for bigger int, or big int.

I don't think we will support higher int precission until NumPy does, so I'll close this issue. If you or someone else want to work on this, tell us. But it isn't trivial.

**Closed by nouiz** 2015-10-30 13:03 UTC

**Comment by richardotis** [comment] 2015-10-30 14:26
@nouiz My cost function graphs are constructed by a routine and sometimes  What's the objection to upcasting to floatX? In my use case all the arithmetic is floating-point and I've altered my graph constructor to upcast all ints to floats to work around this issue, but I'm wondering if there's a chance of that breaking someone else's expectations if it were implemented in Theano.

**Comment by richardotis** [comment] 2015-10-30 14:29
What I mean is if one operand is an integer and the other is a float (in this case, `1.0`), I see no reason why the integer can't be upcast to match the other operand.

**Comment by nouiz** [comment] 2015-10-30 16:04
The problem isn't the true_div, but the 2**64. This in int that don't fit
in int64. If we convert this to float, it will get rounded and won't be
exact. I don't think we should round ints to float automatically.

You can replicate the 2**64 without the true_div like this:

```
>>> import numpy
>>> numpy.asarray(2**64, dtype='uint64')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/Tmp/lisa/os_v4/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py",
line 462, in asarray
    return array(a, dtype, copy=False, order=order)
OverflowError: Python int too large to convert to C long
```

**Comment by richardotis** [comment] 2015-10-30 16:49
Thanks for the response. Based on your explanation I think your disposition for Theano is reasonable and I will work around the issue on my end. For anyone else who comes across this issue and doesn't care about **losing precision**, you can wrap big integers like
```python
np.array(2**64, dtype=theano.config.floatX)
```
and results will happily compute.
