### ISSUE TITLE
Drop support to Python 2.6

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#4685] opened 2016-07-04 22:32 UTC
For the last two days every new build on Travis crashed due to a commit in pydot that broke the compatibility with Python 2.6. I opened an issue and they are willing to fix *this* bug, but they don't plan to actively support Python 2.6 anymore (see https://github.com/erocarrera/pydot/issues/123 for details). 

It is probably time for Theano to consider doing the same and raise the minimum requirement to Python 2.7.

**Comment by nouiz** [comment] 2016-07-06 21:19
Duplicate of https://github.com/Theano/Theano/issues/4507

**Closed by nouiz** 2016-07-06 21:19 UTC
