### ISSUE TITLE
Why the function f = theano.function([net.input_var, net.target_var], metrics)  taking too much time?

### ISSUE THREAD

**Issue by chowkamlee81** [Theano/Theano#6458] opened 2017-10-04 09:22 UTC
Why the function f = theano.function([net.input_var, net.target_var], metrics) @ line 50 in test.py taking too much time?
Iam using Quadro1000M , 4GB GPU.

Train dataset length = 367
Validation dataset length = 101
Testing dataset length = 233.

To run prediction command it is take more than a day and it still not yet completed. I would like to know whether configuration settings in my Laptop is sufficient to run prediction rather than training. Kindly help me and suggest pls.

**Comment by nouiz** [comment] 2017-10-06 12:59
Theano is made such that you will compile a function (the call to theano.function) a few times and reuse many times the results. So it is expected to take much more times then the execution of the returned function.

Normally, people only compile a few function at the start of there script and reuse them for each minibatch of the training. So this match the expectation well.

Also, we compile many c shared library in the call to theano.function, but they are cached. So the first time you do that it will be longer then following call.

I'm closing as this is by design and won't change. But if you still have question, you can ask them here or in theano-user mailing list.

**Closed by nouiz** 2017-10-06 12:59 UTC
