### ISSUE TITLE
tensor.dot compiles with higher tensors

### ISSUE THREAD

**Issue by eulerreich** [Theano/Theano#3439] opened 2015-09-24 21:44 UTC
In the documentation, `theano.tensor.dot(X, Y)` takes parameters either matrix or vector. However, the following compiles in theano

```python
v = T.vector()
t3 = T.tensor3()
h = theano.function([v, t3], v.dot(t3), allow_input_downcast=True)
```
(the `allow_input_downcast=True` is nonessential)
When calling `h`, for example `h(np.arange(5), np.arange(5*4*3).reshape(5, 4, 3))`, ones gets an error like this

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-58830f470094> in <module>()
----> 1 h(np.arange(5), np.arange(5*4*3).reshape(5, 4, 3))

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    604                         self.fn.nodes[self.fn.position_of_error],
    605                         self.fn.thunks[self.fn.position_of_error],
--> 606                         storage_map=self.fn.storage_map)
    607                 else:
    608                     # For the c linker We don't have access from

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    593         t0_fn = time.time()
    594         try:
--> 595             outputs = self.fn()
    596         except Exception:
    597             if hasattr(self.fn, 'position_of_error'):

ValueError: Shape mismatch: A.shape[1] != y.shape[0]
Apply node that caused the error: CGemv{inplace}(Alloc.0, TensorConstant{1.0}, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1}.0, TensorConstant{0.0})
Inputs types: [TensorType(float32, vector), TensorType(float32, scalar), TensorType(float32, matrix), TensorType(float32, vector), TensorType(float32, scalar)]
Inputs shapes: [(15,), (), (15, 4), (5,), ()]
Inputs strides: [(4,), (), (4, 60), (4,), ()]
Inputs values: ['not shown', array(1.0, dtype=float32), 'not shown', array([ 0.,  1.,  2.,  3.,  4.], dtype=float32), array(0.0, dtype=float32)]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

This error is incredibly cryptic especially when `dot` is called with tensors created from things like `jacobian` which could create higher tensors without the user particularly willing them (for example, if the parameters differentiated against form rows instead of vectors).

I think the desired behavior here is to immediately throw an error on compilation of `dot` with anything other than vector or matrix.

**Comment by nouiz** [comment] 2015-09-25 12:55
Our dot implementation is equivalent to numpy.dot. And it suport higher
dimensions. We convert it to gemm,gemv call (matrix x matrix or matrix x
vector) for performance reason.

To get a much better error, run the same code with the Theano flag:

optimizer=None.

It will run slower and won't have stability optimization, but it will tell
you in your code where the dot node was created. This way, you know where
in your own code the problem is.

The numpy.dot doc tell:

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
arrays to inner product of vectors (without complex conjugation). For N
dimensions it is a sum product over the last axis of *a* and the
second-to-last of *b*:

We follow this. I'll close this issue as it is normal that it work, but if
my suggestion don't help you to find the problem in your code, don't
hesitate to reply.

**Closed** 2015-09-25 12:55 UTC

**Comment by eulerreich** [comment] 2015-09-25 17:25
OK, then in the [doc](http://deeplearning.net/software/theano/library/tensor/basic.html#linear-algebra), the entry for `dot` should mention this. Right now the `parameters` in the entry contradicts its behavior.

**Comment by nouiz** [comment] 2015-09-25 17:42
Thanks. I'll update the doc.
