### ISSUE TITLE
ImportException Theano

### ISSUE THREAD

**Issue by PierrotLC** [Theano/Theano#4292] opened 2016-03-24 19:52 UTC
Since last XCode command lines update yesterday, any theano function compilation - even the dumbest one - has raised an error, whereas theano was running well for 6 months I used Python 3.4 w/ other Anaconda packages.

So I did a clean install of my Mac, then reinstalled everything and now, importing theano raises an exception of failed compilation.
I join the partial screen shot :
[ImportException.pdf](https://github.com/Theano/Theano/files/188567/ImportException.pdf)

Please could you explain me what's going on ? And possibly help me to solve it ?
Thanks in advance !

**Comment by lamblin** [comment] 2016-03-24 20:11
Duplicate of #4277.

**Closed by lamblin** 2016-03-24 20:11 UTC
