### ISSUE TITLE
 GpuDimShuffle crashes

### ISSUE THREAD

**Issue by mzhang001** [Theano/Theano#4713] opened 2016-07-10 14:38 UTC
Hi, 

When I use GpuDimShuffle, it crashes. I have tried different -march in  ~/.theanorc like corei7-avx, corei7, and none of them works.

Theano: 0.8.2
gcc: 4.8.1
cuda: 7.5
python: 2.7.10
OpenBLAS:0.2.15

===============================
In file included from /usr/local/Cluster-Apps/python/2.7.10/include/python2.7/Python.h:8:0,
                 from mod.cu:1:
/usr/local/Cluster-Apps/python/2.7.10/include/python2.7/pyconfig.h:1188:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/local/Cluster-Apps/cuda/7.5/include/host_config.h:161:0,
                 from /usr/local/Cluster-Apps/cuda/7.5/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:162:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/local/Cluster-Apps/python/2.7.10/include/python2.7/Python.h:8:0,
                 from mod.cu:1:
/usr/local/Cluster-Apps/python/2.7.10/include/python2.7/pyconfig.h:1210:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/local/Cluster-Apps/cuda/7.5/include/host_config.h:161:0,
                 from /usr/local/Cluster-Apps/cuda/7.5/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:164:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
In file included from /usr/local/Cluster-Apps/python/2.7.10/include/python2.7/Python.h:8:0,
                 from mod.cu:1:
/usr/local/Cluster-Apps/python/2.7.10/include/python2.7/pyconfig.h:1188:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/local/Cluster-Apps/cuda/7.5/include/host_config.h:161:0,
                 from /usr/local/Cluster-Apps/cuda/7.5/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:162:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/local/Cluster-Apps/python/2.7.10/include/python2.7/Python.h:8:0,
                 from mod.cu:1:
/usr/local/Cluster-Apps/python/2.7.10/include/python2.7/pyconfig.h:1210:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/local/Cluster-Apps/cuda/7.5/include/host_config.h:161:0,
                 from /usr/local/Cluster-Apps/cuda/7.5/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:164:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
/tmp/cc3LfQ4C.s: Assembler messages:
/tmp/cc3LfQ4C.s:629: Error: no such instruction: `shlx %ecx,%edi,%edi'

['nvcc', '-shared', '-O3', '-arch=sm_30', '-m64', '-Xcompiler', '-fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/cuda_ndarray', '-I/home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/cuda_ndarray', '-I/usr/local/Cluster-Apps/cuda/7.5/include', '-I/home/mz342/python_lib/py2/lib/python2.7/site-packages/numpy/core/include', '-I/usr/local/Cluster-Apps/python/2.7.10/include/python2.7', '-I/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof', '-I/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/sandbox/cuda', '-o', '/home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/tmpb1UCvT/561cf3a07c6124dfa8afda3ef055f9de.so', 'mod.cu', '-L/home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/cuda_ndarray', '-L/usr/local/Cluster-Apps/python/2.7.10/lib', '-lcudart', '-lcublas', '-lcuda_ndarray', '-lpython2.7']
Traceback (most recent call last):
  File "mnist_transfer_cnn.py", line 115, in <module>
    (X_test_lt5, y_test_lt5), nb_classes)
  File "mnist_transfer_cnn.py", line 66, in train_model
    validation_data=(X_test, Y_test))
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/keras/models.py", line 413, in fit
    sample_weight=sample_weight)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1026, in fit
    self._make_test_function()
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/keras/engine/training.py", line 695, in _make_test_function
    **self._function_kwargs)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 541, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 527, in __init__
    **kwargs)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 399, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuDimShuffle{x,0}(dense_2_b), '\n', 'nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -arch=sm_30 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/cuda_ndarray -I/home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/cuda_ndarray -I/usr/local/Cluster-Apps/cuda/7.5/include -I/home/mz342/python_lib/py2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/Cluster-Apps/python/2.7.10/include/python2.7 -I/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/gof -I/home/mz342/python_lib/py2/lib/python2.7/site-packages/theano/sandbox/cuda -o /home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/tmpb1UCvT/561cf3a07c6124dfa8afda3ef055f9de.so mod.cu -L/home/mz342/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.7-Carbon-x86_64-2.7.10-64/cuda_ndarray -L/usr/local/Cluster-Apps/python/2.7.10/lib -lcudart -lcublas -lcuda_ndarray -lpython2.7', '[GpuDimShuffle{x,0}(dense_2_b)]')

**Comment by nouiz** [comment] 2016-07-11 13:02
Try Theano dev version. We tried to automatically detect this category of g++ bug and tried to fix it automatically:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

If that don't, try this Theano flag:

    gcc.cxxflags='-march=core2" 

Closing as this is a duplicate of gh-3780

If that don't work, you can reply here.

**Closed by nouiz** 2016-07-11 13:02 UTC

**Comment by mzhang001** [comment] 2016-07-11 13:25
Hi,

I have updated Theano to the development version, and it still has the same problem with gcc/4.8.1. 

The problem is finally solved by using gcc/4.9.2 and setting cxxflags. (Not sure whether the stable version of Theano 0.8.2 work as well by updating the gcc version and setting cxxflags.)

It seems that -march=corei7, corei7-arx and core2 all work on my machine.

Thanks a lot.
