### ISSUE TITLE
using libgpuarray backend: "BUG IN FGRAPH.REPLACE OR A LISTENER" 

### ISSUE THREAD

**Issue by apulver** [Theano/Theano#4586] opened 2016-06-04 19:54 UTC
I get this optimization error when using the new backend, but not with the old one.

Here's some LSTM code to reproduce the error:

optimizer=fast_run

```
import numpy as np
import theano.tensor as T
import theano
import theano_lstm as lstm
import gc

def softmax(x):
    return T.nnet.softmax(x)[0]

SIZE = 10

INPUT_SIZE = SIZE
LAYERS = [20]
OUTPUT_SIZE = SIZE

N = 100

network = lstm.StackedCells(INPUT_SIZE, layers=LAYERS, celltype=lstm.LSTM, activation=T.tanh)
network.layers.append(lstm.Layer(LAYERS[-1], OUTPUT_SIZE, softmax))

def time_step(x, *prev):
    states = network.forward(T.extra_ops.to_one_hot(x,10)[0], prev_hiddens=prev) 
    return states

input_sequence = T.imatrix('input_sequence')
target_sequence = T.ivector('target_sequence')

t_i = T.iscalar()



results, updates = theano.scan(fn=time_step,
                               outputs_info = [dict(initial=layer.initial_hidden_state, taps=[-1]) for layer in network.layers if hasattr(layer, 'initial_hidden_state')] + [None], 
                               sequences=input_sequence)

reg_cost = T.sum([nparam.norm(L=2) for nparam in network.params])


R_ETA = .001

cost = -T.sum(T.log(results[-1])[T.arange(target_sequence.shape[0]),target_sequence]) + R_ETA*reg_cost

updates, _, _, _, _ = lstm.create_optimization_updates(cost, network.params, rho=0.99, method='sgd')

training_inputs = theano.shared(np.random.randint(0, SIZE, (10000,1), dtype=np.int32))
training_targets = theano.shared(np.random.randint(0, SIZE, (10000), dtype=np.int32))

b = 100
train_network = theano.function(inputs=[t_i],
                                givens = {input_sequence:training_inputs[t_i*b:(t_i+1)*b], target_sequence:training_targets[t_i*b:(t_i+1)*b]},
                                outputs=cost,
                                updates=updates)

for i in xrange(0, 100):
    t = train_network(i)
    print t

```

**Comment by nouiz** [comment] 2016-10-03 15:22
We don't have the theano_lstm file. So we can't reproduce it. Do you still have this problem? If so, can you give us this file?

As this is old and I can't reproduce, I'm closing this issue. But I'll reopen if I can reproduce and it still happen.

**Closed by nouiz** 2016-10-03 15:22 UTC
Labels: GPU - New back-end, Scan

**Comment by apulver** [comment] 2016-10-03 15:44
it's on pypi

**Comment by apulver** [comment] 2016-10-03 15:46
Is the new backend enabled by default  now? I've been using the git version of Theano and haven't had this problem in a while.
