### ISSUE TITLE
Error when using the memory profiler.

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#4649] opened 2016-06-18 23:24 UTC
I'm trying to profile memory usage on the GPU and I'm seeing this:

```
Using gpu device 1: GeForce GTX TITAN X (CNMeM is enabled with initial size: 90.0% of memory, cuDNN None)
Traceback (most recent call last):
  File "/u/wardefar/src/theano/theano/gof/link.py", line 653, in streamline_default_f
    thunk()
  File "/u/wardefar/src/theano/theano/gof/op.py", line 905, in rval
    r = p(n, [x[0] for x in i], o)
  File "/u/wardefar/src/theano/theano/gof/op.py", line 762, in perform
    "Did you used Theano flags mode=FAST_COMPILE?"
theano.gof.utils.MethodNotDefined: ('perform', <class 'theano.sandbox.cuda.basic_ops.GpuCAReduce'>, 'GpuCAReduce', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bench.py", line 1, in <module>
    from blocks.bricks import BatchNormalization
  File "/u/wardefar/src/blocks/blocks/bricks/__init__.py", line 4, in <module>
    from .base import application, Brick, lazy
  File "/u/wardefar/src/blocks/blocks/bricks/base.py", line 10, in <module>
    from theano import tensor
  File "/u/wardefar/src/theano/theano/__init__.py", line 118, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/u/wardefar/src/theano/theano/sandbox/cuda/tests/test_driver.py", line 40, in test_nvidia_driver1
    if not numpy.allclose(f(), a.sum()):
  File "/u/wardefar/src/theano/theano/compile/function_module.py", line 862, in __call__
    self.fn() if output_subset is None else\
  File "/u/wardefar/src/theano/theano/gof/link.py", line 657, in streamline_default_f
    raise_with_op(node, thunk)
  File "/u/wardefar/src/theano/theano/gof/link.py", line 317, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/u/wardefar/miniconda/envs/invert/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/u/wardefar/src/theano/theano/gof/link.py", line 653, in streamline_default_f
    thunk()
  File "/u/wardefar/src/theano/theano/gof/op.py", line 905, in rval
    r = p(n, [x[0] for x in i], o)
  File "/u/wardefar/src/theano/theano/gof/op.py", line 762, in perform
    "Did you used Theano flags mode=FAST_COMPILE?"
theano.gof.utils.MethodNotDefined: ('perform', <class 'theano.sandbox.cuda.basic_ops.GpuCAReduce'>, 'GpuCAReduce', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')
Apply node that caused the error: GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>)
Toposort index: 0
Inputs types: [CudaNdarrayType(float32, vector)]
Inputs shapes: [(10000,)]
Inputs strides: [(1,)]
Inputs values: ['not shown']
Outputs clients: [[HostFromGpu(GpuCAReduce{add}{1}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

Command is

`CUDA_LAUNCH_BLOCKING=1 THEANO_FLAGS=device=gpu,floatX=float32,profile=True,profile_memory=True,linker=py python bench.py`

Simply using `profile_memory=True` tells me I need to use the "stack VM" without any indication of how the hell to do that. I assumed `linker=py` was the answer. `optimizer=fast_compile` doesn't do it.

I have run "theano-cache basecompiledir purge" and checked out the latest master and this still persists.

**Comment by lamblin** [comment] 2016-06-19 05:51
`linker=py` makes it impossible to run Ops that do not define Python code in the `perform` method, which is the error you see. The error message mentions `mode=FAST_COMPILE` because that is the most frequent way that `linker=py` gets specified. The message could be updated to mention `linker=py` as well.

When you specify only `profile=True,profile_memory=True`, then what should get printed is a warning saying that Theano *will be using* the Stack VM instead of the default CVM. To get rid of the warning, you can explicitly specify `linker=vm`.

**Comment by dwf** [comment] 2016-06-19 05:52
I'll double check but I'm pretty sure the warning had a sentence in the
imperative, i.e. "Use the Stack VM."

**Comment by lamblin** [comment] 2016-06-19 05:58
It printed the following for me, and then the execution and memory profiles were printed upon exit:
```
/home/user/.local/lib/python3.5/site-packages/theano/gof/vm.py:852: UserWarning: CVM does not support memory profile, using Stack VM.
  'CVM does not support memory profile, using Stack VM.')
```

**Comment by nouiz** [comment] 2017-02-14 18:09
As we don't have news and don't know what we could do that is better, I'll close this issue.

But if you remember the problem and know how to reproduce it, reopen the issue.

**Closed by nouiz** 2017-02-14 18:09 UTC
