### ISSUE TITLE
Backpropagation on max-pooling

### ISSUE THREAD

**Issue by lberrada** [Theano/Theano#5248] opened 2016-11-18 11:14 UTC
Maxpool gradients are back-propagated to all the inputs which are equal to the maximum in the patch. This is not consistent with CudNN, which back-propagates on only one input equal to the maximum - which, for my use case at least, makes more sense.

This difference can have an important impact on CNNs with sparse inputs (e.g. MNIST images).

**Comment by nouiz** [comment] 2016-11-24 21:04
This is a know issue that is a duplicate of: https://github.com/Theano/Theano/issues/4761
So I'll close this issue. You can follow the other one to stay up to date.

**Comment by nouiz** [comment] 2016-11-24 21:05
Just a note, on GPU we use cudnn, so there isn't this problem. It is just on CPU or the old GPU back-end without cudnn. The new gpu back-end don't have that problem.

**Closed by nouiz** 2016-11-24 21:04 UTC

**Comment by lberrada** [comment] 2016-11-24 22:55
Thanks
