### ISSUE TITLE
Add hierarchical softmax to nnet

### ISSUE THREAD

**Issue by bouthilx** [Theano/Theano#2627] opened 2015-03-16 17:42 UTC
Take hierarchical softmax from [groundhog](https://github.com/lisa-groundhog/GroundHog/blob/master/groundhog/layers/cost_layers.py) and turn it into an op or helper function under theano.sandbox.cuda.nnet

**Comment by nouiz** [comment] 2015-03-30 18:08
I close as this is a duplicate of gh-2501

**Closed by nouiz** 2015-03-30 18:08 UTC
Labels: CCW
