### ISSUE TITLE
When I run Keras I get a warning of Using NumPy C-API based implementation for BLAS functions. What does this mean?

### ISSUE THREAD

**Issue by markgacoka** [Theano/Theano#6533] opened 2017-12-07 02:54 UTC
When I run keras library I get this error:

Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:12:41) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
>>>

What does this mean? How can I fix it?

**Comment by nouiz** [comment] 2017-12-09 00:19
It mean Theano can't find blas. So it call it indirectly via numpy. This
slow down computation for many technical reason.

An easy fix as you use conda is to execute:

"conda install mkl"

**Comment by markgacoka** [comment] 2017-12-09 15:32
I installed mkl, mkl-service, some tools it also said I install and the error still persists

**Comment by nouiz** [comment] 2017-12-11 15:19
This is also discussed in gh-6532, so I'll close this one as duplicate.

**Closed by nouiz** 2017-12-11 15:19 UTC

**Comment by kajimage** [comment] 2018-03-14 04:10
Thank you very much for I meeting the same question, which is now solved by this method

**Comment by WesleyTheGeolien** [comment] 2018-05-09 01:01
@markgacoka I ran `conda install blas` and that seemed to get rid of the warning on my machine, hope this helps.

**Comment by DerekGrant** [comment] 2018-05-27 02:33
@WesleyTheGeolien Many Thanks! It's really helpful!

**Comment by GbengaOdesanmi** [comment] 2019-03-01 09:21
@all please anyone have solve this error with different method from the above

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
python3 /home/gbenga/Documents/2019 vrep code/maml_rl-master/scripts/run_experiment_lite.py  --n_parallel '1'  --snapshot_mode 'last'  --seed '1'  --plot 'False'  --exp_name 'trpomaml1_fbs20_mbs40_flr_0.5metalr_0.01_step11'  --log_dir '/home/gbenga/Documents/2019 vrep code/maml_rl-master/data/local/vpg-maml-point100/trpomaml1_fbs20_mbs40_flr_0.5metalr_0.01_step11'  --use_cloudpickle 'False'  --args_data 'gANjcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJNZXRob2RDYWxsCnEAKYFxAX1xAihYBgAAAF9fYXJnc3EDKGNybGxhYi5taXNjLmluc3RydW1lbnQKU3R1Yk9iamVjdApxBCmBcQV9cQYoWAQAAABhcmdzcQcpWAYAAABrd2FyZ3NxCH1xCShYAwAAAGVudnEKaAQpgXELfXEMKGgHKWgIfXENWAsAAAB3cmFwcGVkX2VudnEOaAQpgXEPfXEQKGgHKWgIfXERaApoBCmBcRJ9cRMoaAcpaAh9cRRYCwAAAHByb3h5X2NsYXNzcRVjbWFtbF9leGFtcGxlcy5wb2ludF9lbnZfcmFuZGdvYWwKUG9pbnRFbnZSYW5kR29hbApxFnVic2gVY3JsbGFiLmVudnMubm9ybWFsaXplZF9lbnYKTm9ybWFsaXplZEVudgpxF3Vic2gVY3NhbmRib3gucm9ja3kudGYuZW52cy5iYXNlClRmRW52CnEYdWJYBgAAAHBvbGljeXEZaAQpgXEafXEbKGgHKWgIfXEcKFgEAAAAbmFtZXEdaBlYCAAAAGVudl9zcGVjcR5jcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJBdHRyCnEfKYFxIH1xIShYBAAAAF9vYmpxImgLWAoAAABfYXR0cl9uYW1lcSNYBAAAAHNwZWNxJHViWA4AAABncmFkX3N0ZXBfc2l6ZXElRz/gAAAAAAAAWBMAAABoaWRkZW5fbm9ubGluZWFyaXR5cSZjdGVuc29yZmxvdy5weXRob24ub3BzLmdlbl9ubl9vcHMKcmVsdQpxJ1gMAAAAaGlkZGVuX3NpemVzcShLZEtkhnEpdWgVY3NhbmRib3gucm9ja3kudGYucG9saWNpZXMubWFtbF9taW5pbWFsX2dhdXNzX21scF9wb2xpY3kKTUFNTEdhdXNzaWFuTUxQUG9saWN5CnEqdWJYCAAAAGJhc2VsaW5lcStoBCmBcSx9cS0oaAcpaAh9cS5oHmgfKYFxL31xMChoImgLaCNoJHVic2gVY3JsbGFiLmJhc2VsaW5lcy5saW5lYXJfZmVhdHVyZV9iYXNlbGluZQpMaW5lYXJGZWF0dXJlQmFzZWxpbmUKcTF1YlgKAAAAYmF0Y2hfc2l6ZXEySxRYDwAAAG1heF9wYXRoX2xlbmd0aHEzS2RYDwAAAG1ldGFfYmF0Y2hfc2l6ZXE0SyhYEAAAAG51bV9ncmFkX3VwZGF0ZXNxNUsBWAUAAABuX2l0cnE2S2RYCAAAAHVzZV9tYW1scTeIWAkAAABzdGVwX3NpemVxOEc/hHrhR64Ue1gEAAAAcGxvdHE5iHVoFWNzYW5kYm94LnJvY2t5LnRmLmFsZ29zLm1hbWxfdHJwbwpNQU1MVFJQTwpxOnViWAUAAAB0cmFpbnE7KX1xPHRxPVgIAAAAX19rd2FyZ3NxPn1xP3ViLg=='
python3: can't open file '/home/gbenga/Documents/2019': [Errno 2] No such file or directory

**Comment by WesleyTheGeolien** [comment] 2019-03-03 21:24
@GbengaOdesanmi I am guessing the problem is here ` --log_dir '/home/gbenga/Documents/2019 vrep code/maml_rl-master/data/local/vpg-maml-point100/trpomaml1_fbs20_mbs40_flr_0.5metalr_0.01_step11` you have spaces in 2019 vrep code try  --log_dir '/home/gbenga/Documents/2019\ vrep\ code/maml_rl-master/data/local/vpg-maml-point100/trpomaml1_fbs20_mbs40_flr_0.5metalr_0.01_step11` or replace the folder name spaces as underscores.

I don't think this is related to the above blas problem though ...

**Comment by nouiz** [comment] 2019-03-03 22:43
Blas is just a warning. You can ignore it. Otherwise with vonda, you can
fix it like this from memory

Conda install mkl-service

Le dim. 3 mars 2019 16 h 24, Wesley Banfield <notifications@github.com> a
écrit :

**Comment by Ziaeemehr** [comment] 2020-04-18 10:32
This worked for me:
`sudo apt-get install -y libblas-dev`
