### ISSUE TITLE
AttributeError: 'CudaNdarray' object has no attribute 'data'

### ISSUE THREAD

**Issue by ssamot** [Theano/Theano#3710] opened 2015-12-01 07:59 UTC
I am getting an error with the lastest theano pulled from github (previous commits, e.g. #21adebb work fine). Trace: 

Traceback (most recent call last):
  File "experiment.py", line 198, in <module>
    callbacks=[LearningRateScheduler(sch)] )
  File "/home/ssamot/projects/keras/keras/models.py", line 495, in fit
    shuffle=shuffle, metrics=metrics)
  File "/home/ssamot/projects/keras/keras/models.py", line 216, in _fit
    outs = f(*ins_batch)
  File "/home/ssamot/projects/Theano/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/ssamot/projects/Theano/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/ssamot/projects/Theano/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/home/ssamot/projects/Theano/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/ssamot/projects/Theano/theano/scan_module/scan_op.py", line 952, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 389, in theano.scan_module.scan_perform.perform (/home/ssamot/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/scan_perform/mod.cpp:3936)
AttributeError: 'CudaNdarray' object has no attribute 'data'
Apply node that caused the error: forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}(Elemwise{minimum,no_inplace}.0, GpuSubtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, GpuSubtensor{int64:int64:int64}.0, GpuSubtensor{::int64}.0, GpuSubtensor{::int64}.0, GpuSubtensor{::int64}.0, GpuSubtensor{::int64}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, <CudaNdarrayType(float32, matrix)>, GpuDimShuffle{1,0}.0)
Toposort index: 1543
Inputs types: [TensorType(int64, scalar), CudaNdarrayType(float32, 3D), TensorType(int8, (False, False, True)), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(), (5, 100, 128), (5, 100, 1), (5, 100, 128), (6, 100, 128), (6, 100, 128), (6, 100, 128), (6, 100, 128), (), (), (), (), (), (), (), (), (128, 128), (128, 128)]
Inputs strides: [(), (-12800, 128, 1), (-1, 6, 600), (-12800, 128, 1), (-12800, 128, 1), (-12800, 128, 1), (-12800, 128, 1), (-12800, 128, 1), (), (), (), (), (), (), (), (), (128, 1), (1, 128)]
Inputs values: [array(5), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', array(5), array(5), array(5), array(5), array(5), array(5), array(5), array(5), 'not shown', 'not shown']
Outputs clients: [[], [], [], [], [GpuSubtensor{::int64}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.4, Constant{-1})], [GpuReshape{2}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.5, MakeVector{dtype='int64'}.0)], [GpuSubtensor{::int64}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.6, Constant{-1})], [GpuReshape{2}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.7, MakeVector{dtype='int64'}.0)], [GpuSubtensor{::int64}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.8, Constant{-1})], [GpuReshape{2}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.9, MakeVector{dtype='int64'}.0)], [GpuSubtensor{::int64}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.10, Constant{-1})], [GpuReshape{2}(forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}.11, MakeVector{dtype='int64'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by nouiz** [comment] 2015-12-01 14:11
This is pretty strange. Can you delete your Theano cache?

**Comment by f0k** [comment] 2015-12-01 15:43
FWIW, a Lasagne user reported the same: https://groups.google.com/forum/#!topic/lasagne-users/xo6TNuYGqR0

**Comment by ssamot** [comment] 2015-12-01 20:40
I just deleted the cache - takes a bit longer to compile, but you get the same error

**Comment by carriepl** [comment] 2015-12-01 21:00
Can you provide a code sample to reproduce the issue? I have a good sense of where the problem comes from but having a way to reproduce the issue would speed everything up.

**Comment by ssamot** [comment] 2015-12-01 21:21
Well, it's from this: 

https://github.com/ssamot/distnet

It's keras + some of my own theano code. Here on how to run it: 

https://github.com/ssamot/distnet/blob/master/train_emb.sh

**Comment by carriepl** [comment] 2015-12-03 14:59
Thanks a lot,

I installed keras and your code. I'm attempting to run it but it doesn't seem to be compatible with the latest commit in the master since it refers to files that are not in keras any more (theano_utils.py, for instance). Can you tell me which version/commit of keras you are using?

**Comment by jeanpijon** [comment] 2015-12-03 15:01
This is due to change in Keras backend - theano_utils doesnt exist anymore - most of the functions is now in backend/theano_backend.py for more details look here: http://keras.io/backend/

**Comment by ssamot** [comment] 2015-12-03 15:03
I am using febc604fc4c7d8996f73ab585a5ae6237c8bcc97 for keras - I will update soon to the latest if you are willing to wait, but this might break the custom theano layers, so it might be better to go for the commit that that works

**Comment by f0k** [comment] 2015-12-03 16:06
The user from our mailing list also put up his code: https://github.com/mzhai2/SentimentHw/blob/5b631aeb05a4fa4257dc21c80af20c5cc0bf25c3/base.py
It will probably work (i.e., produce the error) with the latest Lasagne master, but I haven't attempted to run it yet.

**Comment by carriepl** [comment] 2015-12-03 18:46
Thanks. 
I have made a PR on Theano to fix the issue : https://github.com/Theano/Theano/pull/3734

**Comment by ssamot** [comment] 2015-12-04 09:54
This has now been fixed  - I don't get the error with the latest theano commit any more! 

Thanks for this!

**Comment by nouiz** [comment] 2015-12-04 13:46
fixed by gh-3734

**Closed by nouiz** 2015-12-04 13:46 UTC

**Comment by carriepl** [comment] 2015-12-04 16:03
Well, thanks to you for the bug report!
