### ISSUE TITLE
Partial evaluation of a Theano function

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2472] opened 2015-02-03 16:07 UTC
This would allow to reuse the same function for test and train. With the cvm/vm linker, this is relatively easy if we compile the full function, then just ask to compute some of the outputs.

We could also allow to compute just some of the intermediate results. This would allow to unroll a big scan with the max supported lenght and compute just the number of iteration we want. Not sure how this would work for the back-ward.

**Comment by nouiz** [comment] 2016-03-11 16:39
For people wanting to know how to implement this:

- Understand how Theano graph are done. (bi-partite graph, with 2 type of node Variable and Apply node, you must understand how to navigate between each node)
- Start by the vm (python version). When this is done there, this can be ported to the cvm (c code). It is easier to work in python to develop the algorithm.
- start by understanding how the vm/cvm evaluate a Theano function. The VM is in the class VM, in the file theano/gof/vm.py. It start from the output, for each node, it check if its dependency are available, if not it try to evaluate this. This is done recursively, but with a loop implementation instead of calling recursively different function.
-Then understand how the compute_map and storage_map work. In particular, understand how the IfElse op work, as this will cause only some of the inputs to be evaluated.
- With that information, you should be able to modify the VM to start from a subset of the output nodes. Implement a user way to do that. This would be the first user available feature.

**Comment by sygi** [comment] 2016-03-17 19:07
Could I ask for (even more) clarification on that? I mean, as partial evaluation you mean:
a) putting just a subset of inputs, calculate some subset of nodes and then, if you give the rest of the inputs multiple times, you don't recompute the nodes that were saved previously OR
b) give all the inputs, but calculate only some subset of the output nodes. This seems as more expected interpretation, as I see "output nodes" in the description, but how is that different from creating separate functions for different output nodes? Isn't it the case that you have to calculate the whole function exactly once for a given input?
In particular, could you elaborate more on the "not recompiling train/test function"?
Thanks for the hints, sorry if these questions are silly.

**Comment by nouiz** [comment] 2016-03-17 19:25
Don't hesitate to ask questions. It is only by well understanding the
problem that we can find a good solution:)

It is more b). Maybe you don' t need to give all inputs as some are maybe
not needed to compute the subset of output we need to compute.

This is similar to compiling many function, but would save on the
compilation time and memory consumption (not so much a problem). As the
goal is to allow many different combination of outputs and same compilation
time, we don't want to retrain a function each time.

**Comment by sygi** [comment] 2016-03-18 16:40
I dived into the code and have few more questions about how it works:
0. Is it at all the around the thing we're discussing here? That is, is the `f.apply(inputs, outputs)` a good way to think about this feature?
1. Am I correct that one needs to implement this feature for all VMs, i.e. `Stack`, `Loop`, `CVM`, etc.? 
2. I thought about passing the output indices as a kwarg to the function call e.q. `f(1,2,3, output_subset=[0, 3])`, but apparently function already can get kwargs. What do they represent?
3. What is actually wrong with the approach that I implemented (except that it creates unnecessarily placeholders for all outputs and passes information from apply to __call__ in a nasty way)? It seemed a bit too easy :tongue:

**Comment by nouiz** [comment] 2016-03-18 16:55
On Fri, Mar 18, 2016 at 12:40 PM, Jakub Sygnowski <notifications@github.com>
wrote:

> I dived into the code and have few more questions about how it works:
> 0. Is it at all the around the thing we're discussing here? That is, is
> the f.apply(inputs, outputs) a good way to think about this feature?
>
yes. It look good. Not sure about the name, could be call, execute. I don't
have a strong preference for the name, but that is a detail.


> 1. Am I correct that one needs to implement this feature for all VMs, i.e.
> Stack, Loop, CVM, etc.?
>

Only Stack and CVM can implement it. Loop and LoopGC don't have an
execution engine that allow this to work.


> 2. I thought about passing the output indices as a kwarg to the function
> call e.q. f(1,2,3, output_subset=[0, 3]), but apparently function already
> can get kwargs. What do they represent?
>
I prefer that. You use this fct signature, I think it would work:

def apply(self, *inputs, output_subset=None, **kwargs):

Otherwise:

def apply(self, *inputs, **kwargs):

and then do kwargs.pop('output_subset') to remove that keyword.



> 3. What is actually wrong with the approach that I implemented (except
> that it creates unnecessarily placeholders for all outputs and passes
> information from apply to *call* in a nasty way)? It seemed a bit too
> easy [image: :tongue:]
>
It seem easier that I taught! But the hard part is understanding how things
work. You seem to have learn it rapidly. As said in the PR, it seem too
light for a full GSoC, so think of what you could do after that part.

Fred

**Comment by sygi** [comment] 2016-03-18 21:36
Thanks for the comments, I applied most of them in the code. I have few more questions:
1. I wanted to make a test where I'd check if I really don't calculate some part of the graph and thought about using profile to do that, but apparently, when I passed `profile=True` to function, I got an error (` File "/home/sygi/projekty/Theano/theano/compile/profiling.py", line 687, in summary_memory
    fct_shapes[node.fgraph][node].append(sh)
UnboundLocalError: local variable 'sh' referenced before assignment`). Is that an expected behavior, or should I file a bug?
2. I wasn't sure how to write a comment about the new feature [here](https://github.com/Theano/Theano/pull/4259/files#diff-e1ec622313fa89e96ae691b21427788fR767). Could you help?

btw, as far as GSoC is concerned, I unfortunately am not eligible to participate (but I am a student). Would you mind if I use your help anyway and finish this issue just for bragging rights (and probably some another not-taken-for-gsoc-issue later, if I'll still have time&motivation)?

**Comment by nouiz** [comment] 2016-03-19 02:13
On Fri, Mar 18, 2016 at 5:36 PM, Jakub Sygnowski <notifications@github.com>
wrote:

> Thanks for the comments, I applied most of them in the code. I have few
> more questions:
> 1. I wanted to make a test where I'd check if I really don't calculate
> some part of the graph and thought about using profile to do that, but
> apparently, when I passed profile=True to function, I got an error (File
> "/home/sygi/projekty/Theano/theano/compile/profiling.py", line 687, in
> summary_memory
> fct_shapes[node.fgraph][node].append(sh)
> UnboundLocalError: local variable 'sh' referenced before assignment). Is
> that an expected behavior, or should I file a bug?
>

Bug, try this branch:

https://github.com/nouiz/Theano/tree/profiling

Maybe there is more problem later.

> 2. I wasn't sure how to write a comment about the new feature here
> <https://github.com/Theano/Theano/pull/4259/files#diff-e1ec622313fa89e96ae691b21427788fR767>.
> Could you help?
>
> btw, as far as GSoC is concerned, I unfortunately am not eligible to
> participate (but I am a student). Would you mind if I use your help anyway
> and finish this issue just for bragging rights (and probably some another
> not-taken-for-gsoc-issue later, if I'll still have time&motivation)?
>

I'm happy to help you finish this:)

I did other comment on the PR.

thanks

Frédéric

**Comment by sygi** [comment] 2016-03-19 15:15
Thanks for the help! I applied most of the comments and squashed the commits into one.
0. I wonder, do you prefer to try to have a working solution for vm, push it and continue with cvm or try to merge them with master together when they'll be ready?
Anyway, I took a look at the travis output and my current [implementation](https://github.com/Theano/Theano/compare/master...sygi:partial-evaluation?expand=1) is failing on `DebugMode` (e.g. on test `compile.tests.test_debugmode.Test_preallocated_output`), which is forcing usage of cvm, which doesn't have `output_subset` argument in `__call__`.
1. Will it be fine to add `output_subset=None` in other VMs as well with raising an error when it is given (it will happen when someone won't pass `allow_partial_eval` and Vm_Linker would choose e.g. LoopGC)?
2. I was trying to find out how does the CVM work and how to add this keyword argument (or an equivalent) to it (so it won't be failing because of the # of arguments to `__call__`). As far as I understand, the cvm code is in `lazylinker_c.(py|c)`. I see that around [here](https://github.com/Theano/Theano/blob/master/theano/gof/lazylinker_c.c#L788) are some calls, but I can't see where is an explicit match between `__call__` and some C code. Are you able to shine some light onto this?
3. Thanks for the patch for profiling. Indeed it doesn't crash now, but I'm still unable to have reasonable profiling info - I'm getting ` No execution time accumulated (hint: try config profiling.time_thunks=1)
` (I tried turning on the flag). But I'm not sure if I'm doing everything right, as when I did `f.profile.print_summary()` I got `AttributeError: 'ProfileStats' object has no attribute 'print_summary'`. Code is [here](https://github.com/sygi/Theano/tree/partial-trash).

**Comment by nouiz** [comment] 2016-03-22 14:36
0. I prefer to merge for the VM alone first. In case some people want to try it and comment on it.

Call self.fn() with the output_subset only when it isn't None.  This could fix your problem. With the full error message, I could tell more.
1) I prefer to not do that and don't set the parameter whtn it is None.
2) Grep for CLazyLinker_call in that file. It is used at 2 places. The first one define the function. The other it is in the Python C-API that tell which C function to use for the python call \__call__.
3) How do you enable the Theano profiler? With the flag profile=True? With which VM do you have that problem?

Others:
- Can you make/reopen the PR? It make commenting on the code easier.

- In the assert > 1e-9, use utt.all_close() instead. It is more robust and give better error message.

- If self.output_keys is True, in function_module.py around line 962, I think it don't work. Raise an error that the combination of output_keys with partial eval isn't implemented or implement it.

thanks

**Comment by sygi** [comment] 2016-03-22 16:07
Thank you for the comments. Sorry for closing PR, I didn't know you'll not be able to comment :( (nor that I'll not be able to reopen it if I'll do some git tricks).
I applied your comments.
I implemented handling of `output_keys` in a way that if that dictionary is present, then you need to pass the list of the keys instead of indices (see [here](https://github.com/Theano/Theano/pull/4279/commits/c4d1145b66b65d92b6dcfda9f0c358a57fa66070#diff-60bfee9b68d200aa1be198398b688490R216)).

I was calling with `profile=True`, `linker=VM_Linker` and `allow_partial_eval=True`. You can see the code [here](https://github.com/sygi/Theano/blob/partial-trash/theano/gof/tests/test_vm.py#L201).

Thanks!

**Closed** 2016-04-18 17:14 UTC
Labels: CCW

**Comment by nouiz** [comment] 2016-06-14 13:06
I created a follow up ticket to implement this in the CVM: https://github.com/Theano/Theano/issues/4624
