### ISSUE TITLE
fblas deprecation warning

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#3045] opened 2015-06-17 21:06 UTC
[These lines](https://github.com/Theano/Theano/blob/2425cd119b96296a7e0ca5bd10bdfdba53c7aa3c/theano/tensor/blas.py#L342-L351) are causing:

```
/usr/local/lib/python2.7/dist-packages/scipy/lib/_util.py:35: DeprecationWarning: Module scipy.linalg.blas.fblas is deprecated, use scipy.linalg.blas instead
  DeprecationWarning)
```

**Comment by nouiz** [comment] 2015-06-17 21:12
The problem is that we want to support many scipy version. Which version os
you use? Can you investigate the code that would work for your version
without warning?

**Comment by skirpichev** [comment] 2016-10-31 17:20
This warning exists on scipy 0.14.0, but not in 0.18.1.

**Comment by nouiz** [comment] 2016-10-31 17:23
So I would just close this issue.

thanks.

**Closed by nouiz** 2016-10-31 17:23 UTC

**Comment by skirpichev** [comment] 2016-10-31 17:37
From your master's setup.py, I see that 0.14 is still supported.  Did I miss something?

**Comment by nouiz** [comment] 2016-11-03 18:16
I just tested with scipy 0.14 and I don't have a warning anymore.

If someone still have a warning, make sure to update to Theano dev version.
If you still have a warning, give us the full error message AND the scipy
version. It would be a specific scipy version that generate more warning.
We could check how to remove it, but you could probably just update scipy.
