### ISSUE TITLE
tensor.abs_() returning negative values in Theano 1.0.0

### ISSUE THREAD

**Issue by diogoff** [Theano/Theano#6514] opened 2017-11-17 20:41 UTC
When I upgraded from Theano 0.9.0 to 1.0.0 my code just broke. I narrowed down the issue to this minimal working example:

```
import theano
import theano.tensor as T
import numpy as np

x = T.dmatrix('x')

f = theano.function([x], T.mean(T.abs_(x), axis=-1))

a = np.array([[-1.], [0.], [1.]])

print f(a)
```

In Theano 0.9.0, the result is: [1.  0.  1.]
In Theano 1.0.0, the result is: [-1.  0.  1.]

Curiously, Theano 1.0.0 gives [-1. 0. 1.] on the GPU, but [1.  0.  1.] on the CPU. Could this be an issue with libgpuarray?

**Comment by notoraptor** [comment] 2017-11-17 21:10
I confirm the problem (tested on Windows), quite strange.

**Comment by notoraptor** [comment] 2017-11-20 14:50
About this issue, the problem is introduced by my commit c2c2879365b14c259a9e69a22cf49e7ddc2d40fe, where sum of abs is optimized with GpuDnnReduction.

In the code above, the tensor to reduce has shape `(3, 1)` (`a = np.array([[-1.], [0.], [1.]])`), and the axis to reduce is the last one, which has size `1`, then the code goes into this section: https://github.com/Theano/Theano/blob/master/theano/gpuarray/c_code/dnn_redux.c#L89 . Nothing is computed, the output returned is just a copy of the input.

It seems that this is to avoid passing an output which will have the same shape as the input (here `(3, 1)`) to the cuDNN reductiion function, as it does not like it (`CUDNN_STATUS_BAD_PARAM`).

@abergeron @lamblin @nouiz

**Comment by nouiz** [comment] 2017-11-20 14:53
Can you comment that bypass for that case and see if cudnn does the right thing?

In the mean time, you can use this theano flag as a workaround: optimizer_excluding=local_gpu_elemwise_careduce

**Comment by notoraptor** [comment] 2017-11-20 15:00
If I comment (`/* || rsz == 1 */`), I got the `CUDNN_STATUS_BAD_PARAM`.

When using `optimizer_excluding=local_gpu_elemwise_careduce` it works, because the merging (abs + max -> norm1 (absmax)) is not done, so that the abs is computed by a GpuElemwise.

**Comment by lamblin** [comment] 2017-11-20 15:03
OK, then I think we would need a special case to handle the pre-scalar op when the output shape is the same as the input.

**Comment by nouiz** [comment] 2017-11-20 15:30
And we should report that to NVIDIA. I'll do that.

**Comment by nouiz** [comment] 2017-11-21 13:57
It is fixed in the master of Theano. Update Theano to the version on github. Thanks for the report.

We will try to make a 1.0.1 release next week as this is a serious bug.

**Closed** 2017-11-21 13:56 UTC
