### ISSUE TITLE
"Python setup.py Develop" failed on installing dependencies

### ISSUE THREAD

**Issue by NNM11** [Theano/Theano#4338] opened 2016-04-05 21:56 UTC
When I installed Theano with the Git and "python setup.py develop" commands.  It failed on dependent libraries.  System: Python 3.5 64bit, on a Windows 10 enterprise PC. 
Is there a way to fix this? Thx.
----
The log:

_D:\Theano>python setup.py develop
running develop
running egg_info
creating Theano.egg-info
writing dependency_links to Theano.egg-info\dependency_links.txt
writing requirements to Theano.egg-info\requires.txt
writing top-level names to Theano.egg-info\top_level.txt
writing Theano.egg-info\PKG-INFO
writing manifest file 'Theano.egg-info\SOURCES.txt'
reading manifest file 'Theano.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 9: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'Theano.egg-info\SOURCES.txt'
running build_ext
Creating c:\python3_5\lib\site-packages\Theano.egg-link (link to .)
Adding Theano 0.8.0 to easy-install.pth file
Installing theano-cache script to C:\Python3_5\Scripts
Installing theano-nose script to C:\Python3_5\Scripts
Installing theano-test script to C:\Python3_5\Scripts

Installed d:\theano
Processing dependencies for Theano==0.8.0
Searching for six>=1.9.0
Reading https://pypi.python.org/simple/six/
Best match: six 1.10.0
Downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
Processing six-1.10.0.tar.gz
Writing C:\Users\NNM~1\AppData\Local\Temp\easy_install-fzidxmui\six-1.10.0\setup.cfg
Running six-1.10.0\setup.py -q bdist_egg --dist-dir C:\Users\NNM~1\AppData\Local\Temp\easy_install-fzidxmui\six-1.10.0\egg-dist-tmp-nsyayt3u
no previously-included directories found matching 'documentation\_build'
zip_safe flag not set; analyzing archive contents...
__pycache__.six.cpython-35: module references __path__
creating c:\python3_5\lib\site-packages\six-1.10.0-py3.5.egg
Extracting six-1.10.0-py3.5.egg to c:\python3_5\lib\site-packages
Adding six 1.10.0 to easy-install.pth file

Installed c:\python3_5\lib\site-packages\six-1.10.0-py3.5.egg
Searching for scipy>=0.11
Reading https://pypi.python.org/simple/scipy/
Best match: scipy 0.17.0
Downloading https://pypi.python.org/packages/source/s/scipy/scipy-0.17.0.zip#md5=28a4fe29e980804db162524f10873211
Processing scipy-0.17.0.zip
Writing C:\Users\NGHIAN~1\AppData\Local\Temp\easy_install-getgugr1\scipy-0.17.0\setup.cfg
Running scipy-0.17.0\setup.py -q bdist_egg --dist-dir C:\Users\NNM\AppData\Local\Temp\easy_install-getgugr1\scipy-0.17.0\egg-dist-tmp-3413vnbm
C:\Python3_5\lib\site-packages\numpy\distutils\system_info.py:633: UserWarning: Specified path C:\projects\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
C:\Python3_5\lib\site-packages\numpy\distutils\system_info.py:1542: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
C:\Python3_5\lib\site-packages\numpy\distutils\system_info.py:1553: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  warnings.warn(LapackNotFoundError.__doc__)
C:\Python3_5\lib\site-packages\numpy\distutils\system_info.py:1556: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  warnings.warn(LapackSrcNotFoundError.__doc__)
Running from scipy source directory.
error: no lapack/blas resources found

D:\Theano>_

**Comment by nouiz** [comment] 2016-04-05 23:54
Python 3.5 on windows is troublesome. Use another python version. 2.7 or 3.4 should be good.

Closing as duplicate of https://github.com/Theano/Theano/issues/3376

**Closed by nouiz** 2016-04-05 23:54 UTC
