### ISSUE TITLE
Incompatible on nanguardmode and sandbox.rng_mrg?

### ISSUE THREAD

**Issue by lovecambi** [Theano/Theano#4823] opened 2016-08-03 22:51 UTC
I try to debug with nanguardmode to find the where my code induces the NAN. However, I find this mode will always throw an NAN error if your random number generator is theano.sandbox.rng_mrg. Thus I cannot locate where the real NAN is.

Below is a simple example to show this issue. f1 and f1_nan are basically the same function except for the later one with nanguardmode, and f1 involves random numbers. f2 has no random numbers, and f2_nan is similar but with nanguardmode.

```python
import numpy as np
import theano
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
import theano.tensor as T
from theano.compile.nanguardmode import NanGuardMode

_srng = RandomStreams(np.random.randint(1, 2147462579))

mu = T.matrix()
logvar = T.matrix()
eps = _srng.normal(mu.shape)

res1 = (mu + T.exp(0.5*logvar) * eps).mean()
f1 = theano.function([mu, logvar], res1, allow_input_downcast=True)
f1_nan = theano.function([mu, logvar], res1, allow_input_downcast=True, mode=NanGuardMode(nan_is_error=True, inf_is_error=True, big_is_error=True))

res2 = (mu + T.exp(0.5*logvar)).mean()
f2 = theano.function([mu, logvar], res2, allow_input_downcast=True)
f2_nan = theano.function([mu, logvar], res2, allow_input_downcast=True, mode=NanGuardMode(nan_is_error=True, inf_is_error=True, big_is_error=True))

v = np.random.normal(size=(100,64))
m = np.random.normal(size=(100,64))

f1(m,v)
#output: array(0.02410086616873741, dtype=float32)

f1_nan(m, v)
#output: AssertionError: NaN detected
#        NanGuardMode found an error in an input of the graph.

f2(m,v)
#output: array(1.1354453563690186, dtype=float32)

f2_nan(m, v)
#output: array(1.1354453563690186, dtype=float32)
```

In addition, I found the CudaNdarray with NAN always has the shape (92160,) regardless of the input shape, which I guess is the pre-allocated vector in GPU for further computation?

**Comment by nouiz** [comment] 2016-08-04 00:17
Can you try with Theano dev version? I think it was fixed since the last
release.

**Comment by lovecambi** [comment] 2016-08-10 15:59
I installed the Theano dev version and I am sure the program run with the new version, but the same error appears.

**Comment by f0k** [comment] 2016-08-18 14:57
@nouiz: Where do you think this was fixed? My colleague seems to have stumbled upon the same problem with the latest git version, he also gets "NanGuardMode found an error in an input of the graph" for a CudaNdarray of shape (92160,). How can we circumvent this?

**Comment by nouiz** [comment] 2016-08-18 16:16
The code in the issue description don't seem to trigger it. But it use
random numbers, I'll execute it in a loop in the hope that it get triggered.

Do you have other code that reproduce the problem? Is it on the CPU or GPU?

**Comment by f0k** [comment] 2016-08-18 16:27
> The code in the issue description don't seem to trigger it.

It does for me, `THEANO_FLAGS=device=gpu0` (i.e., on GPU, old backend). It is not triggered on CPU. No need to run in a loop.

**Comment by f0k** [comment] 2016-08-18 16:33
I guess it's because the internal random state is interpreted as a float32 vector. It's just binary data that may happen to match a NaN representation, which is not unlikely at all:
> [All NaNs in IEEE 754-1985 have this format:](https://en.wikipedia.org/wiki/IEEE_754-1985#NaN)
> sign = either 0 or 1.
> biased exponent = all 1 bits.
> fraction = anything except all 0 bits (since all 0 bits represents infinity).

We'd need a flag or something to tell the NanGuardMode not to inspect these arrays.

**Comment by lovecambi** [comment] 2016-08-18 17:12
> It does for me, THEANO_FLAGS=device=gpu0 (i.e., on GPU, old backend). It is not triggered on CPU. No need to run in a loop.

Same to me.

**Comment by lovecambi** [comment] 2016-08-18 18:01
> I guess it's because the internal random state is interpreted as a float32 vector. It's just binary data that may happen to match a NaN representation, which is not unlikely at all:

That may be true. I also have another test, if I change x to scalar, big value error is triggered. The abs of some value is larger than 1e10.
```python
x = T.scalar()
e =_srng.normal(size=(2,2))
y = x*e
f = theano.function([x], y)
f_nan = theano.function([x], y,  mode=NanGuardMode(nan_is_error=True, inf_is_error=True, big_is_error=True))

f(0)
#output: array([[-0.,  0.],
#               [-0., -0.]], dtype=float32)

f_nan(0)
#output: AssertionError: Big value detected
#        NanGuardMode found an error in an input of the graph.
```

**Comment by lamblin** [comment] 2016-08-18 20:56
A similar issue has indeed been fixed in the past, but probably has been re-introduced when we made changes to NanGuardMode so it uses the Python VM by default.

Please note that it should not affect the new GPU back-end, where we are not trying to pretend that int32 are float32.
Since we are shifting support from the old to the new back-end, we might not fix this issue.

**Comment by nouiz** [comment] 2016-08-19 16:13
It was quick to fix. I'm able to reproduce it with device=gpu.

https://github.com/Theano/Theano/pull/4881

**Closed** 2016-08-19 20:46 UTC
