### ISSUE TITLE
theano catch exceptions

### ISSUE THREAD

**Issue by sachinruk** [Theano/Theano#5766] opened 2017-03-25 21:23 UTC
This is a crosspost from http://stackoverflow.com/questions/42990413/theano-try-except-statements?noredirect=1#comment73077524_42990413

I am trying to take the cholesky of a covariance matrix, which isn't always invertible (few small eigen values). So I wish to do the following:
```
try:
    return T.slinalg.cholesky(self.cov)
except:
    return -np.inf
```
except it seems that theano doesn't like `try-except` statements. Any thoughts on how I could do this?

**Comment by nouiz** [comment] 2017-03-27 13:54
I think you didn't understand that build a symbolic graph when executing " T.slinalg.cholesky(self.cov)". This mean, it plan to do that computation, but did not do the computation. I encourage you to follow Theano tutorial to understand it better. In particular this page should explain that:

http://deeplearning.net/software/theano/tutorial/adding.html

There is no way to catch such exception inside a Theano graph (planned execution). To do that, would request modifing the class Cholesky inside the file tensor/slinalg.py. You can do it yourself, it should be easy. You could make a PR to have this inside Theano.

If someone implement it, it should be an option of the Op to catch or not the execption. By default it should do the current behavior, not catch it.

**Comment by sachinruk** [comment] 2017-03-27 22:42
I suppose I am specifically referring to the code below (from https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py):

Considering how new I am to theano, I don't entirely understand how this theano op came to be. **I do understand that theano is symbolic** and that is why the `try-except` didn't work originally.

So here are some specific questions about the following code (incase it helps me achieve what I am after):
1. Will the try-except in this specific case work?
2. Will there be some sort of switching happening below going from theano to numpy, and hence make it somewhat slower?
3. Do I need to return the gradient myself? 
4. And is it returning zero gradient below because it's a 1 or 0 situation?
5. Is there an easy tutorial (apart from the official docs) that I can read/ watch about doing theano Ops?

```
def posdef(AA):
    try:
        np.linalg.cholesky(AA)
        return 1
    except np.linalg.LinAlgError:
        return 0


class PosDefMatrix(theano.Op):
    """
    Check if input is positive definite. Input should be a square matrix.
    """

    # Properties attribute
    __props__ = ()

    # Compulsory if itypes and otypes are not defined

    def make_node(self, x):
        x = tt.as_tensor_variable(x)
        assert x.ndim == 2
        o = tt.TensorType(dtype='int8', broadcastable=[])()
        return theano.Apply(self, [x], [o])

    # Python implementation:
    def perform(self, node, inputs, outputs):

        (x,) = inputs
        (z,) = outputs
        try:
            z[0] = np.array(posdef(x), dtype='int8')
        except Exception:
            pm._log.exception('Failed to check if positive definite', x)
            raise

    def infer_shape(self, node, shapes):
        return [[]]

    def grad(self, inp, grads):
        x, = inp
        return [x.zeros_like(theano.config.floatX)]

    def __str__(self):
        return "MatrixIsPositiveDefinite"

matrix_pos_def = PosDefMatrix()
```

**Comment by nouiz** [comment] 2017-04-04 19:19
Comments on the pymc3 issue seem to indicate the problem is fixed. If so, can you close this issue?

**Closed** 2017-04-14 01:18 UTC
Labels: Contribution Welcome, Enhancement
