### ISSUE TITLE
possible bug with dimensions when creating tensor

### ISSUE THREAD

**Issue by pjadzinsky** [Theano/Theano#3320] opened 2015-08-23 18:31 UTC
Hi,

I'm new to theano but it seems to me like this is a bug (apologies if I'm missing something basic). The following code tries two initialize to tensors, one works just fine (assuming I know the number of dimensions), the other one crashes with the error at the end. The example is trivial but at the end of the day, I'm trying to initialize a tensor that is very similar to 'x' without relaying on knowing the number of dimensions

```javascript

import theano.tensor as T

x = T.ftensor4('x')

in_shape = x.shape

# explicitely define output shape, this is a very silly case but serves as example
out_shape = (in_shape[0], in_shape[1], in_shape[2], in_shape[3])
out = T.zeros(out_shape)

# Construct shape, this would be useful if I did nott know the number of dimensions in tensor "x"
out_shape2 = (in_shape[0],) + in_shape[1:]
out2 = T.zeros(out_shape2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-286e8d26e65a> in <module>()
----> 1 out2 = T.zeros(out_shape2)

/Users/jadz/miniconda3/lib/python3.4/site-packages/theano/tensor/basic.py in zeros(shape, dtype)
   2230     if dtype is None:
   2231         dtype = config.floatX
-> 2232     return alloc(numpy.array(0, dtype=dtype), *shape)
   2233 
   2234 

/Users/jadz/miniconda3/lib/python3.4/site-packages/theano/tensor/var.py in __iter__(self)
    526     def __iter__(self):
    527         try:
--> 528             for i in xrange(theano.tensor.basic.get_vector_length(self)):
    529                 yield self[i]
    530         except TypeError:

/Users/jadz/miniconda3/lib/python3.4/site-packages/theano/tensor/basic.py in get_vector_length(v)
   4069             return stop - start
   4070 
-> 4071     raise ValueError("length not known")
   4072 
   4073 

ValueError: length not known
```

**Comment by benanne** [comment] 2015-08-23 19:25
This is not a bug: because `out_shape2` is (part) symbolic, Theano has no way of knowing how many elements the tuple will have, so it does not know how many dimensions the resulting tensor should have at the time of its definition. This is not allowed: a Theano tensor always has a fixed number of dimensions.

I believe there might be a workaround for this, but I can't seem to find it with a quick search. Maybe someone else can :)

**Comment by lamblin** [comment] 2015-08-24 16:26
Right, Theano is able to infer the length of a shape vector, but may not be able to infer the length of *a subtensor* of a shape vector.
You could do the following, explicitly making in_shape a tuple before indexing:
```python
# equivalent of explicitly using (x.shape[0], x.shape[1], x.shape[2], x.shape[3]
in_shape = tuple(x.shape)
out_shape2 = (in_shape[0],) + in_shape[1:]
```
It would be possible to expand `get_vector_length` to match the case of a subtensor with a constant slice, in fact I think someone may already be working on it. However, we will never be able to catch all cases.

**Comment by pjadzinsky** [comment] 2015-08-25 00:14
Thanks a lot!

**Comment by nouiz** [comment] 2015-09-01 14:37
I reopen this as Theano can be modified to support the more user friendly case.

**Comment by nouiz** [comment] 2015-09-01 14:39
To fix this, we need someone to go in the theano/tensor/basic.py file and modify the function get_vector_length to detect that subtensor of shape case.

**Comment by nouiz** [comment] 2015-09-14 05:19
I'll close this as this can be done with : T.zeros(in_shape) directly.

I checked and the + is the elemwise add, so we can't easily support that syntax.

**Closed by nouiz** 2015-09-14 05:19 UTC
Labels: Easy fix, Python Code Only
