### ISSUE TITLE
cuDNN producing incoherent outputs

### ISSUE THREAD

**Issue by MarcCote** [Theano/Theano#3971] opened 2016-02-02 00:01 UTC
I'm observing a strange behaviour with cuDNN when using a **large** batch size  i.e at runtime it fills up the entire GPU memory) compare to using a smaller batch size or not using cuDNN at all (even with a large batch size).

The difference in the results are extreme, going from a NLL around 150 to a NLL of 86 on binarized MNIST! Here, I'm not doing any training, I'm just evaluating my model, so there are no gradients involved. 

I'm using a Tesla K40c (12Gb), running theano master (9627228) with CUDA 7.0 and cuDNN v4. My `.theanorc` is empty and I'm using `THEANO_FLAGS` instead.

Running the following lines using this [code](https://gist.github.com/MarcCote/720e477070bf98819837)
```bash
> THEANO_FLAGS="device=gpu,floatX=float32,optimizer_excluding=cudnn" python cudnn_bug.py
Using gpu device 0: Tesla K40c (CNMeM is disabled)
Using cudnn - False, with batch_size=9000:      407.5704040527344

> THEANO_FLAGS="device=gpu,floatX=float32,optimizer_including=cudnn" python cudnn_bug.py
Using gpu device 0: Tesla K40c (CNMeM is disabled)
Using cudnn - True, with batch_size=9000:       399.5690002441406

> THEANO_FLAGS="device=gpu,floatX=float32,optimizer_including=cudnn" python cudnn_bug.py 4000
Using gpu device 0: Tesla K40c (CNMeM is disabled)
Using cudnn - True, with batch_size=4000:       407.57049560546875

> THEANO_FLAGS="device=gpu,floatX=float32,optimizer_excluding=cudnn" python cudnn_bug.py 4000
Using gpu device 0: Tesla K40c (CNMeM is disabled)
Using cudnn - False, with batch_size=4000:      407.5704040527344
```

Note that using cuDNN with a smaller batch size produces a result that is way closer (not identical, maybe some floating point errors) to the result obtained without cuDNN.

**Comment by nouiz** [comment] 2016-02-02 00:14
Can you try all the cudnn algo as destribed here for the forward. To help
us understand if it is a particular algo or not.

http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html

Did you tried with cudnn v3?

**Comment by MarcCote** [comment] 2016-02-02 17:03
Here are the results. It seems the problem is only there when `algo_fwd=small`. That said, maybe the problem has nothing to do with GPU memory and is related to how CUDA's blocks and threads are handled. I can try with a smaller network but a bigger batch size, what do you think?

cudnn | algo_fwd | batch_size | time (sec.) | results
---------|--------------|----------------|---------------|----------
False | N/A | 9000 | 47.34 | 407.5704040527344
False | N/A | 4000 | 47.36 | 407.5704040527344
False | N/A | 1000 | 47.48 | 407.5704040527344
False | N/A | 100 | 48.13 | 407.5704040527344
True | small | 9000 | 33.96 | **399.5690002441406**
True | small | 4000 | 34.04 | 407.57049560546875
True | small | 1000 | 34.12 | 407.57049560546875
True | small | 100 | 36.82 | 407.57049560546875
True | none | 9000 | 40.08 | 407.57049560546875
True | none | 4000 | 40.10 | 407.57049560546875
True | none | 1000 | 40.08 | 407.57049560546875
True | none | 100 | 41.59 | 407.57049560546875
True | large | 9000 | 0.30 | MemoryError
True | large | 4000 | 0.26 | MemoryError
True | large | 1000 | 2.91 | MemoryError
True | large | 100 | 52.13 | 407.57049560546875
True | fft | 9000 | 0.01 | MemoryError
True | fft | 4000 | 0.01 | MemoryError
True | fft | 1000 | 13.24 | 407.5697937011719
True | fft | 100 | 18.41 | 407.5703125
True | fft_tiling | 9000 | 0.01 | MemoryError
True | fft_tiling | 4000 | 0.00 | MemoryError
True | fft_tiling | 1000 | 24.70 | 407.5704040527344
True | fft_tiling | 100 | 29.93 | 407.5704040527344
True | guess_once | 9000 | 20.16 | MemoryError
True | guess_once | 4000 | 34.10 | 407.57049560546875
True | guess_once | 1000 | 29.81 | 407.5704040527344
True | guess_once | 100 | 20.45 | 407.57000732421875
True | guess_on_shape_change | 9000 | 20.17 | MemoryError
True | guess_on_shape_change | 4000 | 33.66 | 407.57049560546875
True | guess_on_shape_change | 1000 | 29.80 | 407.5704040527344
True | guess_on_shape_change | 100 | 20.45 | 407.57000732421875
True | time_once | 9000 | 0.01 | MemoryError
True | time_once | 4000 | 80.15 | 407.5704040527344
True | time_once | 1000 | 42.39 | 407.5704040527344
True | time_once | 100 | 18.81 | 407.5701904296875
True | time_on_shape_change | 9000 | 0.01 | MemoryError
True | time_on_shape_change | 4000 | 104.83 | 407.5704040527344
True | time_on_shape_change | 1000 | 42.34 | 407.5704040527344
True | time_on_shape_change | 100 | 18.83 | 407.5701904296875

 No, I didn't try with cuDNN v3 yet. If you say it might still be useful, let me know.

**Comment by lamblin** [comment] 2016-02-02 17:44
Well, this clearly looks like a bug in CuDNN, that should be reported to NVIDIA. Thanks for all the comparisons!
Comparing to cudnn v3 can be useful to see if the bug was already present in that version.

**Comment by nouiz** [comment] 2016-02-02 18:14
I'm contacting NVIDIA about this.

**Comment by MarcCote** [comment] 2016-02-02 19:46
The behaviour is also present in cudnn v3.

cudnn | algo_fwd | batch_size | time (sec.) | results
---------|--------------|----------------|---------------|----------
N/A | N/A | 50000 | 60.24 | 234.8657989501953
N/A | N/A | 20000 | 60.23 | 234.8657989501953
N/A | N/A | 9000 | 60.30 | 234.8657989501953
N/A | N/A | 4000 | 60.42 | 234.8657989501953
N/A | N/A | 1000 | 60.48 | 234.8657989501953
N/A | N/A | 100 | 61.07 | 234.8657989501953
v3007 | small | 50000 | 44.85 | **254.27439880371094**
v3007 | small | 20000 | 44.92 | **254.27439880371094**
v3007 | small | 9000 | 44.82 | **248.4427947998047**
v3007 | small | 4000 | 44.91 | 234.86610412597656
v3007 | small | 1000 | 44.96 | 234.86610412597656
v3007 | small | 100 | 45.52 | 234.86610412597656
v4004 | small | 50000 | 44.78 | **254.27439880371094**
v4004 | small | 20000 | 44.76 | **254.27439880371094**
v4004 | small | 9000 | 44.82 | **248.4427947998047**
v4004 | small | 4000 | 44.87 | 234.86610412597656
v4004 | small | 1000 | 44.88 | 234.86610412597656
v4004 | small | 100 | 48.50 | 234.86610412597656

*Note that I used a smaller network as it allows for bigger batch sizes.

**Comment by philvdm** [comment] 2016-02-03 21:39
can you narrow the problem to one convolution layer?
What is the image size, filter size, padding, input features map and output feature maps for this failing case?

**Comment by MarcCote** [comment] 2016-02-04 04:37
Interesting, I wasn't able to reproduce the error with only one convolution layer. The smallest configuration (in term of parameters) that I tested and still reproduces the error is the following:

**Layer 1**
image_size: 28 x 28
filter: 1 x 1 (I also tested with 2x2, 3x3 and 4x4)
input_features_map: 1
output_features_map: 256 (reducing this, reduces the error)
padding: no

**Layer 2**
image_size: depends on the output of layer 1 (here 28 x 28)
filter: 1 x 1 (I also tested with 2x2, 3x3 and 4x4)
input_features_map: corresponds to the output_features_map of layer 1 (here 256)
output_features_map: 128 (reducing this, reduces the error)
padding: no

*Note that using padding (i.e. border_mode='full' in Theano) also produces the error.

With that configuration, varying the batch_size (that corresponds to the first parameter of [theano.tensor.nnet.conv.conv2d](http://deeplearning.net/software/theano/library/tensor/nnet/conv.html#theano.tensor.nnet.conv.conv2d)), I obtained these results:

cudnn | algo_fwd | batch_size | time (sec.) | results
---------|--------------|----------------|---------------|----------
 N/A  |  N/A  | 4000 | 3.23 | 56392.43359375
 N/A  |  N/A  | 6000 | 3.25 | 56392.43359375
v3007 | small | 4000 | 2.17 | 56392.43359375
v3007 | small | 5000 | 2.17 | 56392.43359375
v3007 | small | 5350 | 2.17 | 56392.43359375
**v3007** | **small** | **5351** | **2.16** | **56391.4609375**
v3007 | small | 5352 | 2.17 | 56390.484375
v3007 | small | 5354 | 2.17 | 56388.5390625
v3007 | small | 5360 | 2.18 | 56382.65625
v3007 | small | 5365 | 2.16 | 56377.77734375
v3007 | small | 5375 | 2.17 | 56367.98828125
v3007 | small | 5500 | 2.16 | 56245.67578125
v3007 | small | 6000 | 2.18 | 55756.69140625

**Comment by nouiz** [comment] 2016-02-04 13:16
Can you run it with Theano flag mode=DebugMode and
DebugMode.check_py=False? It will help identify which op cause problem.

**Comment by MarcCote** [comment] 2016-02-04 14:58
@nouiz when I set the said flags, it produces a MemoryError with batch_size of 6000 and 4000.

**Comment by philvdm** [comment] 2016-02-04 18:40
I cannot reproduce the problem on my TitanX : it works fine
hilippev-dt:~/theano_bug>python cudnn_bug.py 5000
Using gpu device 0: GeForce GTX TITAN X
Using cudnn - True, with batch_size=5000
Output: 56392.421875
Time: 1.26250910759
philippev-dt:~/theano_bug>python cudnn_bug.py 5500
Using gpu device 0: GeForce GTX TITAN X
Using cudnn - True, with batch_size=5500
Output: 56392.421875
Time: 1.27129411697
philippev-dt:~/theano_bug>python cudnn_bug.py 9000
Using gpu device 0: GeForce GTX TITAN X
Using cudnn - True, with batch_size=9000
Output: 56392.421875
Time: 1.26698803902

And on my K20C, I ran out of memory beyond batch_size=4000

I am going to try to access some K40

**Comment by nouiz** [comment] 2016-02-05 15:02
Could is be related to the cuda version being 7.0? I would be surprised,
but just in case.

**Comment by MarcCote** [comment] 2016-02-05 16:46
@philvdm: I just reproduced the error on a K80 but not on a GTX660 (not enough memory).
@nouiz: for my K80 tests, I used CUDA 7.5 (and cudnn v4) on Helios.

**Comment by nouiz** [comment] 2016-02-05 20:37
I tried on our computers on a Titan X and I also don't have the problem. I tried it on a k80 and I had this problem.

So I suppose the problem is in the code related to the kepler implementation of small for big batch.

This was with cuda V7.5.17, driver 352.68 and both version of cudnn v3 and v4rc1.

**Comment by philvdm** [comment] 2016-02-06 04:51
We have found the root cause of this problem : there is indeed a bug in Algo1 on Kepler only.
The input and output tensors  size including the striding should not exceed 4 Gbytes (e.g 1 Gig element in float, 2 Gig element in FP16). Currently cudnn restricts the creation of tensor bigger than 2 Gig elements.
We will likely workaround this problem in cudnn v4 Final by returning NOT_SUPPORTED when Algo1 on Kepler is selected and the size in bytes exceed 4 Gbytes.

**Comment by nouiz** [comment] 2016-02-08 14:39
thanks.

**Comment by MarcCote** [comment] 2016-02-09 19:56
:+1:

**Comment by nouiz** [comment] 2016-02-10 02:28
@philvdm, how can we detect this case exactly to give a better error
message? As the inputs will be c contiguous, can we just raise an error if
algo1 is used with more then 1G element in float32? You wrote about strides
and I'm not sure how to interpret that part.

**Comment by philvdm** [comment] 2016-02-11 05:05
>>As the inputs will be c contiguous, can we just raise an error if algo1 is used with more then 1G element in float32 YES
In cudnn_v4, we will return CUDNN_NOT_SUPPORTED when this case is detected.

**Comment by nouiz** [comment] 2016-02-24 18:19
I tested cudnn v4 final and it return that error. So I'm closing this issue.

**Closed by nouiz** 2016-02-24 18:19 UTC
Labels: Crash, GPU
