### ISSUE TITLE
Bugs for dilate convolution on gpuarray mode

### ISSUE THREAD

**Issue by danliu2** [Theano/Theano#5078] opened 2016-10-12 05:58 UTC
Hi,
     Now Theano support dilate convolution only with sandbox.cuda, If I set "device=cuda0" and use gpuarray mode, the optimize will failed to translate abstractconv2d to gpu ops, I found there seems to be no implementation in gpuarray package for dilate. Now I'm work with platoon from MLIA for multi-node training and theano must work with gpuarray mode, so I'm here for help. Thanks very much.

**Comment by nouiz** [comment] 2016-10-12 16:05
It is not a bug. It is just that we didn't ported it now. There is a PR for
it here, you can try it:

https://github.com/Theano/Theano/pull/5069

I think it should work. We will probably merge that PR this week.

**Comment by lamblin** [comment] 2016-10-16 00:56
Closed by #5069.

**Closed by lamblin** 2016-10-16 00:56 UTC
