### ISSUE TITLE
bug when update to ubuntu 16.04

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#4426] opened 2016-04-23 08:54 UTC
This happens when `import theano`
```
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^

['nvcc', '-shared', '-O3', '-use_fast_math', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/wenjian/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.1-64/cuda_ndarray', '-I/home/wenjian/pkgs/Theano/theano/sandbox/cuda', '-I/home/wenjian/anaconda3/lib/python3.5/site-packages/numpy/core/include', '-I/home/wenjian/anaconda3/include/python3.5m', '-I/home/wenjian/pkgs/Theano/theano/gof', '-o', '/home/wenjian/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.1-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/home/wenjian/anaconda3/lib', '-lcublas', '-lpython3.5m', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -use_fast_math -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/wenjian/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.1-64/cuda_ndarray -I/home/wenjian/pkgs/Theano/theano/sandbox/cuda -I/home/wenjian/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/wenjian/anaconda3/include/python3.5m -I/home/wenjian/pkgs/Theano/theano/gof -o /home/wenjian/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.1-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/home/wenjian/anaconda3/lib -lcublas -lpython3.5m -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: cuda unavailable)
``

**Comment by rh314** [comment] 2016-04-23 11:40
Here's a workaround while you wait @fayeshine  :)
https://github.com/Theano/Theano/issues/4425

**Comment by lamblin** [comment] 2016-04-26 20:29
Closing as a duplicate of #4425.

**Closed by lamblin** 2016-04-26 20:29 UTC
