### ISSUE TITLE
Problems with g++

### ISSUE THREAD

**Issue by tsoernes** [Theano/Theano#4397] opened 2016-04-19 00:43 UTC
Theano 0.8.2, Python 3.5.1, Windows 10, all 64-bit. I have GCC installed to C:/TDM-GCC-64. This is my config:

```
[global]
floatX=float32
device=cpu
cxx="C:/TDM-GCC-64/bin/g++.exe"

[nvcc]
fastmath=True
```
When running import theano I get:
```
===============================
[output of some file]
'\"C:/TDM-GCC-64/bin/g++.exe\"' is not recognized as an internal or external command,
operable program or batch file.
[output of some file]
Problem occurred during compilation with the command line below:
"C:/TDM-GCC-64/bin/g++.exe" -shared -g -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=ivybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\numpy\core\include -IC:\Users\Torstein\Anaconda2\envs\python3.5\include -IC:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\gof -o C:\Users\Torstein\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-SP0-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.5.1-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Torstein\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-SP0-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.5.1-64\lazylinker_ext\mod.cpp -LC:\Users\Torstein\Anaconda2\envs\python3.5\libs -LC:\Users\Torstein\Anaconda2\envs\python3.5 -lpython35
Traceback (most recent call last):
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\gof\lazylinker_c.py", line 74, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\gof\lazylinker_c.py", line 91, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Torstein/Jottacloud/Skole/Maskinlering/assignment5/test.py", line 1, in <module>
    import theano
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\__init__.py", line 63, in <module>
    from theano.compile import (
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\compile\__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\compile\function_module.py", line 22, in <module>
    import theano.compile.mode
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\compile\mode.py", line 12, in <module>
    import theano.gof.vm
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\gof\vm.py", line 638, in <module>
    from . import lazylinker_c
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\gof\lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "C:\Users\Torstein\Anaconda2\envs\python3.5\lib\site-packages\theano\gof\cmodule.py", line 2203, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. 

Process finished with exit code 1
```
I have tried forward and backwards slashed for the g++ path in Theano config.
I have tried MinGW instead of TDM-GCC.
Both MinGW and TDM-GCC has their \bin folders in the PATH variable, and both have a g++.exe file in their respective \bin folders. g++.exe works from cmd.exe.
If i do not include the cxx variable in the theano config then I get the message:
```
WARNING (theano.configdefaults): g++ not detected ! ...
```

Any help appreciated

**Comment by lamblin** [comment] 2016-04-19 01:39
Theano does not support python 3.5 on windows yet, as things have changed in the way to compile new modules and link them with the Python runtime.
Closing as duplicate of #3376.

**Closed by lamblin** 2016-04-19 01:39 UTC
