### ISSUE TITLE
gpuarray backend and tensor.diag

### ISSUE THREAD

**Issue by trungnt13** [Theano/Theano#4679] opened 2016-07-02 11:29 UTC
It seems that it requires context name to create gpu array with new backend, however, T.diag doesn't allow me to specify the context_name. Hence, this method cannot be used with new gpuarray backend.

```
Traceback (most recent call last):
  File "/Users/trungnt13/tmp/tmp6.py", line 20, in <module>
    K.diag(v)
  File "/Users/trungnt13/libs/odin/odin/backend/theano/tensor.py", line 213, in diag
    x = T.diag(x)
  File "/Users/trungnt13/libs/conda/envs/ai/lib/python2.7/site-packages/theano/tensor/basic.py", line 6006, in diag
    return diagonal(v, k)
  File "/Users/trungnt13/libs/conda/envs/ai/lib/python2.7/site-packages/theano/tensor/basic.py", line 5974, in diagonal
    return theano.tensor.nlinalg.extract_diag(a)
  File "/Users/trungnt13/libs/conda/envs/ai/lib/python2.7/site-packages/theano/gof/op.py", line 602, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/Users/trungnt13/libs/conda/envs/ai/lib/python2.7/site-packages/theano/tensor/nlinalg.py", line 195, in make_node
    dtype=x.type.dtype)()])
  File "/Users/trungnt13/libs/conda/envs/ai/lib/python2.7/site-packages/theano/gpuarray/type.py", line 150, in __init__
    get_context(self.context_name)
  File "/Users/trungnt13/libs/conda/envs/ai/lib/python2.7/site-packages/theano/gpuarray/type.py", line 68, in get_context
    raise ContextNotDefined("context name %s not defined" % (name,))
theano.gpuarray.type.ContextNotDefined: context name None not defined
```

**Comment by Sentient07** [comment] 2016-07-06 09:12
Hello, 
I think this could be fixed with setting context_name by inferring it in the make_node method of the GPU Op that is being used. I had faced this error before and that's how i got over. I'll try a fix for it

**Comment by Sentient07** [comment] 2016-07-06 20:16
Hi, I'm not able to reproduce this traceback. Could you please give me an example ?

**Comment by trungnt13** [comment] 2016-07-07 08:37
Here is the code:
```python
import os
os.environ['THEANO_FLAGS'] = 'contexts=dev0->cuda0,mode=FAST_RUN,floatX=float32,exception_verbosity=high,dnn.conv.algo_fwd=time_once,dnn.conv.algo_bwd_filter=time_once,dnn.conv.algo_bwd_data=time_once,optimizer=fast_run,optimizer_including=unsafe'
import theano
from theano import tensor as T
x = theano.shared(np.ones((10, 10)), target='dev0')
y = T.diag(x)
print(y.eval())
```

My theano version is from commit: **a668c6c**

**Comment by Sentient07** [comment] 2016-07-12 18:15
@trungnt13 Sorry, didn't have time to look on this. I'll try a fix today! Thanks for this case. I could reproduce the error. But it works with Symbolic Variables.(If it could be useful for now)

**Comment by Sentient07** [comment] 2016-07-13 23:17
From what i could see, the error is because `strides` attr of `pygpu.gpuarray.GpuArray` object isn't writable. And because we try to update it in `perform` method of `ExtractDiag`, we encounter this problem. `strides` just denotes the step in each dimension when we iterate through an array. 
cc : @nouiz

**Comment by nouiz** [comment] 2016-11-24 14:11
Note, this PR in libgpuarray advance this: https://github.com/Theano/libgpuarray/pull/291

**Comment by nouiz** [comment] 2016-11-24 22:04
https://github.com/Theano/Theano/pull/5282 should fix this specific crash.

https://github.com/Theano/Theano/pull/5247 will add better diag support in the new back-end.

the libgpuarray PR is merged, you need to update it and update Theano to gh-5282 to have something that have a chance of working. gh-5247 could make this faster, but I think it only cover other cases this this one.

**Comment by nouiz** [comment] 2016-11-25 19:48
fixed by gh-5282, so closing. Thanks for the report.

**Closed by nouiz** 2016-11-25 19:48 UTC
Labels: Crash, GPU - New back-end
