### ISSUE TITLE
Theano scan error.

### ISSUE THREAD

**Issue by Botev** [Theano/Theano#3754] opened 2015-12-06 20:46 UTC
While trying to make a new RNN I got the following weird error:
'''
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.Exception'> Constant{0} is already owned by another fgraph local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(for{cpu,grad_of_scan_fn}.45)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/fg.py", line 592, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/fg.py", line 530, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/fg.py", line 363, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/fg.py", line 394, in __import__
    raise Exception("%s is already owned by another fgraph" % r)
Exception: Constant{0} is already owned by another fgraph
'''
I've very recently update to Theano newest version, however for other RNN models this does not happen. Does anyone have an idea of what is going on? 

PS: Running with 'optimizer=fast_compile' does not produce the error. It seems this is due to some form of optimization procedure?

**Comment by nouiz** [comment] 2015-12-07 00:56
Duplicate of https://github.com/Theano/Theano/issues/3663.

I have a PR to fix this, but it need some changes to tests before merging.

There is a work around in the other issue until the fix get merged.

thanks for the report.

**Closed by nouiz** 2015-12-07 00:56 UTC
