### ISSUE TITLE
Github code link from documentation [source] isn't working properly sometimes.

### ISSUE THREAD

**Issue by ragavvenkatesan** [Theano/Theano#5256] opened 2016-11-20 10:48 UTC
I do't think this is an important issue but some links form [source] that link to github aren't working and it is a little annoying looking up the code on github. I think there is some error in conf.py for the rtd sphinx configuration file. 

For instance.. 
http://deeplearning.net/software/theano/library/tensor/basic.html?highlight=broadcast#theano.tensor.TensorType.broadcastable

This broadcastable code does not link and gives this 404 page: 
https://github.com/Theano/theano/blob/97e3a61264d4fafb9402a11a8b60947e187651bb/theano/tensor.py

**Comment by nouiz** [comment] 2016-11-21 13:43
Closing as duplicate of https://github.com/Theano/Theano/issues/4875.

We don't know how to fix this. We think it is a problem with the plugin. If you know better, tell us on that issue.

thanks for the report.

**Closed by nouiz** 2016-11-21 13:43 UTC
