### ISSUE TITLE
Python 3 Syntax Compatibility

### ISSUE THREAD

**Issue by ebattenberg** [Theano/Theano#2445] opened 2015-01-28 06:38 UTC
It looks like there's a few issues reporting python 3 support issues here, so I'm assuming that Python 3 is supported.  However, I'm simply unable to import Theano when using Python 3 because of a simple syntax incompatibility when catching an exception:
https://github.com/Theano/Theano/blob/master/theano/__init__.py#L153

Am I missing something?  How are others (and buildbots) able to run theano with a syntax error?

**Comment by nouiz** [comment] 2015-01-28 13:58
You need to install theano to make it work with python 3. This will call the 3to2 translator that will fix the syntax. We have a ticket about documenting how to  use Theano with python 3:

https://github.com/Theano/Theano/issues/2317

I think this is the current problem here, so I'll close this ticket. If that do not work, tell us. Use Theano version in git for python 3 support.

**Closed by nouiz** 2015-01-28 13:58 UTC

**Comment by ebattenberg** [comment] 2015-01-28 19:14
Ahh, yes, that was the problem.  I wasn't aware that 2to3 was a part of the process.  I've always used Theano in setup.py "develop" mode which just links in the original source.  So I guess that means that people contributing to Theano should only use python 2?

What are the features in python 2 (and not 3) that are still required for proper operation?  Other than the easy syntax fixes that are forward compatible, I guess there's xrange!=range, from __future__ import division, and new style classes by default.  

Is primary support for python 3 on Theano's roadmap?  I'm just wondering because I feel like my personal transition to python 3 is way past due.  However, Theano plays a large part in my work, so if it's not ready yet, I may delay this process.

**Comment by nouiz** [comment] 2015-01-28 19:19
On Wed, Jan 28, 2015 at 2:14 PM, Eric Battenberg <notifications@github.com>
wrote:

> Ahh, yes, that was the problem. I wasn't aware that 2to3 was a part of the
> process. I've always used Theano in setup.py "develop" mode which just
> links in the original source. So I guess that means that people
> contributing to Theano should only use python 2?
>
For now, that make there live easier. But we dropped support for python 2.4
and 2.5. So if someone is have the time to make Theano work with woth
version and the same code base, it is possible.


> What are the features in python 2 (and not 3) that are still required for
> proper operation? Other than the easy syntax fixes that are forward
> compatible, I guess there's xrange!=range, from *future* import division,
> and new style classes by default.
>
Is primary support for python 3 on Theano's roadmap? I'm just wondering
> because I feel like my personal transition to python 3 is way past due.
> However, Theano plays a large part in my work, so if it's not ready yet, I
> may delay this process.
>

The problem is time for it. This do not allow new research :) So it is not
on the top of the stack of the core dev. But if you or someone else want to
work on that, we would be happy to have PR for this. We need to keep python
2.6 and 2.7 compabitility for now.

Fred

**Comment by ebattenberg** [comment] 2015-01-28 21:03
Ok, thanks.  I may do a PR for some forward compatible syntax fixes.  I
think those are all suggested by PEP8, PEP3110, etc, anyway, so they
shouldn't be too hard to find and fix (and enforce in the future).  This is
probably a good idea going forward in order to future proof the code base.
