### ISSUE TITLE
How can I unistall Theano and reinstall it from source code

### ISSUE THREAD

**Issue by lixinyutfd** [Theano/Theano#5278] opened 2016-11-24 02:08 UTC
Hi all

Just want to know how I can unistall theano and reinstall it from source code cuz when i try 
pip unistall theano it shows No files were found to uninstall while I used to install it from pip

Thanks in advance

**Comment by lamblin** [comment] 2016-11-24 03:46
This is not a bug report nor a feature request, so I'm closing the ticket.
You are welcome to ask for help on theano-users or StackOverflow.

**Closed by lamblin** 2016-11-24 03:46 UTC
