### ISSUE TITLE
Grad illegally returned an integer-valued variable

### ISSUE THREAD

**Issue by ColCarroll** [Theano/Theano#5171] opened 2016-11-02 02:43 UTC
Hi!  Wanted to mention that a few tests broke in pymc3 when moving from 0.9.0.dev3 to 0.9.0.dev4

You can see some failures [here](https://travis-ci.org/pymc-devs/pymc3/jobs/172281533), but the gist is 

`TypeError: Elemwise{mul,no_inplace}.grad illegally  returned an integer-valued variable. (Input index 1, dtype bool)`.  

I'm looking at how to fix this in the pymc3 code -- it would be helpful to know if this is considered a bug, and if there's an easy fix!

**Comment by nouiz** [comment] 2016-11-02 15:43
I don't see the error at the URL.

We recently added a bool dtype in Theano. And we made comparison return
that instead of int8/16.

From the error line you gave, it seem the problem is in the method
Elemwise.grad(). I checked rapidly, and there is some special code for int,
but it seem not being triggered when the inputs is a bool.


I'll try to reproduce it.

**Comment by nouiz** [comment] 2016-11-02 15:48
I'm not able to reproduce it rapidly. But I remember there was some fixes.
@abergeron do you think this is already fixed in Theano or we have
something to do?

**Comment by abergeron** [comment] 2016-11-02 15:54
I can't be 100% certain that it is fixed, but all of our grad tests don't seem to trigger this.  At this point I'd say have code to reproduce would be necessary.

**Comment by ColCarroll** [comment] 2016-11-02 16:05
I'll get an example tonight- thanks for looking!

**Comment by ColCarroll** [comment] 2016-11-03 13:15
Found a small example on the pymc3 side (https://github.com/pymc-devs/pymc3/issues/1496) -- you *should* be able to pip install `pymc3`, and install theano master to reproduce.  I'll keep working to get an example that doesn't require pymc3, to at least figure out which library has a bug!

**Comment by nouiz** [comment] 2016-11-03 17:20
Just to be sure, @abergeron did a PR that should fix this:

https://github.com/Theano/Theano/pull/5175

**Closed** 2016-11-08 03:21 UTC
