### ISSUE TITLE
AttributeError: 'module' object has no attribute 'select_a_gpu'

### ISSUE THREAD

**Issue by DeanChan** [Theano/Theano#3571] opened 2015-10-28 09:09 UTC
I just upgraded theano to the bleeding-edge version using <code>sudo pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git</code>. When I try to import theano, an error was raised as below:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/__init__.py", line 545, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/__init__.py", line 432, in use
    cuda_ndarray.cuda_ndarray.select_a_gpu()
AttributeError: 'module' object has no attribute 'select_a_gpu'
```
This is my <code>~/.theanorc</code> file:
```
[global]
floatX = float32
device = gpu
```

I've checked the gpus with some caffe code, nothing wrong with the device.

**Comment by nouiz** [comment] 2015-10-28 12:21
Delete your Theano cache. For some reason Theano didn't recompile a module.
I have in a pr change that convert this error to a better error.

**Comment by DeanChan** [comment] 2015-10-28 13:03
I used <code>theano-cache clear</code>. A similar error was raised:
```
Traceback (most recent call last):
  File "/root/anaconda/bin/theano-cache", line 4, in <module>
    __import__('pkg_resources').run_script('Theano==0.7.0', 'theano-cache')
  File "/root/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script
  File "/root/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/EGG-INFO/scripts/theano-cache", line 7, in <module>
    import theano
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/__init__.py", line 545, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/__init__.py", line 432, in use
    cuda_ndarray.cuda_ndarray.select_a_gpu()
AttributeError: 'module' object has no attribute 'select_a_gpu'
```

**Comment by DeanChan** [comment] 2015-10-28 13:04
I used <code>theano-cache clear</code>. A similar error was raised:
```
Traceback (most recent call last):
  File "/root/anaconda/bin/theano-cache", line 4, in <module>
    __import__('pkg_resources').run_script('Theano==0.7.0', 'theano-cache')
  File "/root/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script
  File "/root/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/EGG-INFO/scripts/theano-cache", line 7, in <module>
    import theano
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/__init__.py", line 545, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/root/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/__init__.py", line 432, in use
    cuda_ndarray.cuda_ndarray.select_a_gpu()
AttributeError: 'module' object has no attribute 'select_a_gpu'
```

**Comment by nouiz** [comment] 2015-10-28 13:39
use theano-cache purge.

If that do not do it, you have multiple Theano version conflicting together.

**Comment by abergeron** [comment] 2015-10-28 17:39
I think the problem is that theano-cache imports theano, which then tries to initialize the GPU due to the config, which fails and raises the error.

Deleting the theano cache manually could fix the problem.  You'll have to find the folder (which is usually in ~/.theano)

**Comment by nouiz** [comment] 2015-10-28 17:41
This can be done with "theano-cache purge"
 instead of "theano-cache clear"

**Comment by abergeron** [comment] 2015-10-28 17:43
running "theano-cache <whatever>" still imports theano which crashes right there due to the problem.  So it will never delete anything.

**Comment by DeanChan** [comment] 2015-10-29 05:34
Delete all things in ~/.theano did solve the problem. Thanks very much!
Running <code>theano-cache purge</code> still raises error like <code>theano-cache clear</code>.

**Comment by nouiz** [comment] 2015-11-10 16:09
I'll close this as now we detect this and give a good error message.

**Closed by nouiz** 2015-11-10 16:09 UTC

**Comment by sakshijain032** [comment] 2020-03-26 11:06
Does anyone got that how to fix this error
