### ISSUE TITLE
Compiling function does not finish within 12h....

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6501] opened 2017-11-01 11:37 UTC
The function even does not have a scan. It's an IAF which is 10 deep, but I've left it since yesterday and still compiling.... any ideas how to reduce this?

**Comment by notoraptor** [comment] 2017-11-01 18:17
Hi @botev , do you have a small code to reproduce the problem ?

**Comment by botev** [comment] 2017-11-01 19:07
:D  I wish I did, but no small code does that. Trying with 5 deep IAF does not have the same issue. It's somehow related to the depth and my guess is maybe some of the optimizations are going in cycles or so...

**Comment by botev** [comment] 2017-11-02 22:22
I could provide someone privately with access to the code to reproduce but can't really publish it here.

**Comment by botev** [comment] 2017-11-02 23:53
Maybe another pointer is that when you do `Ctrl+C` on the hand the process is here:
```
File "/jmain01/home/JAD002/dxt02/aab09-dxt02/work/python/eval_vi/bin/train.py", line 138, in <module>
    main(**vars(parser.parse_args()))
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/work/python/eval_vi/bin/train.py", line 78, in main
    updates=updates, givens=givens)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 1839, in orig_function
    name=name)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 1519, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 99, in __call__
    return self.optimize(fgraph)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 88, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 242, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 84, in optimize
    self.add_requirements(fgraph)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 794, in add_requirements
    fgraph.attach_feature(MergeFeature())
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/fg.py", line 546, in attach_feature
    attach(self)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 548, in on_attach
    self.on_import(fgraph, node, "on_attach")
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 569, in on_import
    self.process_node(fgraph, node)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 631, in process_node
    merge_candidates = [c for c, i in clients if c in self.nodes_seen]
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 631, in <listcomp>
    merge_candidates = [c for c, i in clients if c in self.nodes_seen]
```

**Comment by nouiz** [comment] 2017-11-03 00:09
First, make sure to use an updated Theano. But I suppose this is your case.

Sadly, there is part of the optimization compilation time that is
super-linear in the number of node in the graph.

A "quick" fix can be to compile with the flag "optimizer=fast_compile"
Normally, it work, but slow down the execution.

If you have more time to investigate, can you do a few runs with different
depth up to what seem resonable. Like 5, 6, 7 with some flags and send me
the output? With this, I could try to find which optimizer get super-linear
compilation time in your case. The flags are
profile=True,profile_optimizer=True

**Comment by botev** [comment] 2017-11-03 00:13
Ok sure, I'll run it with reasonable sizes and increase them up to the complication is less than 10 min. However what kind of "output" you are referring to? Or is that something that will pop out after I set the flags?

**Comment by botev** [comment] 2017-11-03 01:12
Ok so [here](https://ufile.io/ij85c) is the output, from what I could take a look it seems it is something with the merger.

**Comment by nouiz** [comment] 2017-11-03 12:55
The problem is that your original graph seem to have 864k nodes. The merge
optimizer bring this down to 2549.

The problem is not the graph analysis, but the time to update the graph to
merged nodes. This part will be hard to speed up enough, as we stop
develloping Theano, I don't think we will go in that.

Do you use OpFromGraph? If not, you can probably relatively easily modify
your graph building to generate less different constant. How do you create
your constant?

**Comment by botev** [comment] 2017-11-03 13:27
Hmm, that is quite strange to get so many nodes as the whole things are less than 50 layers and I'm using Lasagne. I think I'm using at some point OpFromGraph so will cut that out to see if it helps.

**Comment by botev** [comment] 2017-11-03 13:35
Ok that fixed it... thanks a lot for the help.

**Comment by nouiz** [comment] 2017-11-03 13:44
I suppose the OpFromGraph you use are with the inline flag. There was
probably a big quantity of constant inside the OpFromGraph. It seem that
sadly we duplicate the constant when we inline and merge them back after.

Why did you used OpFromGraph? Did you needed special gradient for some part
of the graph? If not, OpFromGraph isn't going to help you.

**Comment by botev** [comment] 2017-11-03 13:50
Yes, so long-story-short - I've needed OpFromGraph to the Stein-Gradient VI. However, I also for testing implemented with OpFromGraph a clipping function which propagates derivatives back (e.g. `clip=T.clip(x, 2, 3)` than `T.grad(clip,x)` would be `1` even when x is outside [2,3]. I forgot I was using it and kept using it quite over the place.

**Comment by nouiz** [comment] 2017-11-03 14:46
In resume, do you need us to see if we can speed up this case or not?

Le ven. 3 nov. 2017 09:50, Alexander Botev <notifications@github.com> a
écrit :

**Comment by botev** [comment] 2017-11-03 14:53
No no, don't waste time on this. Removing that resolve it so doesn't bother.

**Comment by nouiz** [comment] 2017-11-03 17:05
ok, so closing.

**Closed by nouiz** 2017-11-03 17:05 UTC
