### ISSUE TITLE
TypeError: iteration over a 0-d array

### ISSUE THREAD

**Issue by daweileng** [Theano/Theano#4836] opened 2016-08-09 05:40 UTC
Theano: latest version. Tested both on Windows(CPU) and Ubuntu (GPU).
I'm using Keras to do NN training. Randomly after the compilation is done, an error 
`TypeError: iteration over a 0-d array`
would be raised. Seemed this exists some kind of random compilation bug.

**Comment by nouiz** [comment] 2016-09-01 01:43
When you mean last version. Do you mean last development version or last
release version? Be sure to try last dev version.

We need the full stack trace to help. Do you still have it?

**Comment by heavendai** [comment] 2016-09-14 07:39
hi, @daweileng, @nouiz . Recently, "TypeError: iteration over a 0-d array", the error is found in theano. and the scene is same to @nouiz, using Keras to train a NN model (in train_on_batch function). I tried using both Theano 0.8.0 and 0.8.2, but neither one is ok. @daweileng do you still have the error? can you give me a hand? Thanks.

**Comment by nouiz** [comment] 2016-09-16 18:37
In the comment above, I'm asking to try the dev version of Theano. Also, we would need the full error to be able to help.

Use theano-user mailing list for user help. The problem is probalby in the user code, not in Theano. So closing this issue.

**Closed by nouiz** 2016-09-16 18:37 UTC

**Comment by nouiz** [comment] 2016-09-20 12:52
I'm pretty sure the problem is with keras. Can you update or?

**Comment by nouiz** [comment] 2016-09-20 12:52
I mean, can you update it.

Le 20 sept. 2016 08:21, a écrit :

I'm pretty sure the problem is with keras. Can you update or?

Le 14 sept. 2016 03:39, "heavendai" <notifications@github.com> a écrit :

hi, @daweileng <https://github.com/daweileng>, @nouiz
<https://github.com/nouiz> . Recently, "TypeError: iteration over a 0-d
array", the error is found in theano. and the scene is same to @nouiz
<https://github.com/nouiz>, using Keras to train a NN model (in
train_on_batch function). I tried using both Theano 0.8.0 and 0.8.2, but
neither one is ok. @daweileng <https://github.com/daweileng> do you still
have the error? can you give me a hand? Thanks.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Theano/Theano/issues/4836#issuecomment-246931309>, or mute
the thread

**Comment by heavendai** [comment] 2016-09-21 02:56
hi, @nouiz , I tried Keras 1.0.5 and 1.0.7, but neither one is ok. Which version Keras do you compile? I can have a try. Thank you.

**Comment by heavendai** [comment] 2016-09-21 08:58
fixed it. It needs giving the parameter "metrics=['accuracy]" for model.compile() function explicitly, if you want to get "acc" from train_on_batch and test_on_batch functions, in the new version keras. Thanks for you reply @nouiz .

**Comment by arthiv1** [comment] 2017-04-19 06:56
Iam facing the same issue with latest version of theano.  
'0.9.0.dev-388805f946685e86225cdf602eb8a4f0059f9667'  :
TypeError: iteration over a 0-d array
 Problem does not happen while running in Debug mode.

**Comment by nouiz** [comment] 2017-04-19 14:05
Make a new issue with the full stack trace. This is probably another problem that give the same error.
