### ISSUE TITLE
import theano failed

### ISSUE THREAD

**Issue by zihaolucky** [Theano/Theano#4171] opened 2016-03-04 08:04 UTC
I've searched a lot and didn't find a solution. The gensim/theano is useable after I installed them months ago, but suddenly it doesn't work.

When I import theano, got error info:

````
===============================
Problem occurred during compilation with the command line below:
/home/zihao.zzh/toolchains/bin/g++ -shared -g -march=corei7-avx -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=15360 -mtune=corei7-avx -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/zihao.zzh/anaconda2/include/python2.7 -o /home/zihao.zzh/.theano/compiledir_Linux-2.6-ali927.el5.x86_64-x86_64-with-redhat-5.7-CatFeces-x86_64-2.7.10-64/lazylinker_ext/lazylinker_ext.so /home/zihao.zzh/.theano/compiledir_Linux-2.6-ali927.el5.x86_64-x86_64-with-redhat-5.7-CatFeces-x86_64-2.7.10-64/lazylinker_ext/mod.cpp -L/home/zihao.zzh/anaconda2/lib -lpython2.7
as: unrecognized option `-msse2avx'

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-3397704bd624> in <module>()
----> 1 import theano

/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/theano/__init__.pyc in <module>()
     53     object2, utils
     54
---> 55 from theano.compile import \
     56     SymbolicInput, In, \
     57     SymbolicOutput, Out, \

/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/theano/compile/__init__.py in <module>()
      7         SpecifyShape, specify_shape, register_specify_shape_c_code)
      8
----> 9 from theano.compile.function_module import *
     10
     11 from theano.compile.mode import *

/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py in <module>()
     16 from theano import gof
     17 from theano.compat.python2x import partial
---> 18 import theano.compile.mode
     19 from theano.compile.io import (
     20     In, SymbolicInput, SymbolicInputKit, SymbolicOutput)

/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/theano/compile/mode.py in <module>()
      9 import  theano
     10 from theano import gof
---> 11 import theano.gof.vm
     12 from theano.configparser import config, AddConfigVar, StrParam
     13 from theano.compile.ops import register_view_op_c_code, _output_guard

/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py in <module>()
    566
    567 try:
--> 568     import lazylinker_c
    569
    570     class CVM(lazylinker_c.CLazyLinker, VM):

/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/theano/gof/lazylinker_c.py in <module>()
    114             args = cmodule.GCC_compiler.compile_args()
    115             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
--> 116                                              preargs=args)
    117             # Save version into the __init__.py file.
    118             init_py = os.path.join(loc, '__init__.py')

/home/zihao.zzh/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.pyc in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module)
   2008             # difficult to read.
   2009             raise Exception('Compilation failed (return status=%s): %s' %
-> 2010                             (status, compile_stderr.replace('\n', '. ')))
   2011         elif config.cmodule.compilation_warning and compile_stderr:
   2012             # Print errors just below the command line.

Exception: Compilation failed (return status=1): as: unrecognized option `-msse2avx'.
````

**Comment by nouiz** [comment] 2016-03-09 01:48
This problem is a duplicate of gh-4002.  A workaround until we fix it autoatically is there, so I'll close this issue. If it don't work for you, tell us.

**Closed by nouiz** 2016-03-09 01:48 UTC
