### ISSUE TITLE
Theano 0.8.0.dev0 ignores cpu setting on Python 3.5.1, invokes nvcc anyway

### ISSUE THREAD

**Issue by yhdanid** [Theano/Theano#4104] opened 2016-02-23 02:11 UTC
I have installed Theano 0.8.0.dev0 on both Python 2.7.11 and Python 3.5.1 from a zip of the master tree from github. Both Theano installations are using the same .theanorc file, 

[global]
device = cpu 
floatX = float32

[blas]
#ldflags = -LC:/usr/bin -lopenblas

Theano on Python 2.7 is well behaved and uses the gpu and openblas settings correctly and runs the blas test in the documentation fine as follows:

C:\>python testblas.py
blas.ldflags=
NP time: 0.833000[s], theano time: 0.789000[s] (times should be close when run o
n CPU!)
Result difference: 0.000000

However switching to Python 3.5 and running the same code (found under Configuring Theano on http://deeplearning.net/software/theano/install_windows.html) causes Theano to somehow ignore the cpu device setting and invoke nvcc and then proceed to hang as follows:

C:\>python testblas.py
blas.ldflags=
F:\Python35\lib\site-packages\theano\tensor\signal\downsample.py:5: UserWarning:
 downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
DEBUG: nvcc STDOUT    Creating library F:/Users/me/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_15_Stepping_11_GenuineIntel-3
.5.1-64/cuda_ndarray/cuda_ndarray.lib and object F:/Users/me/AppData/Local/The
ano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_15_Stepping_11_Genu
ineIntel-3.5.1-64/cuda_ndarray/cuda_ndarray.exp

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: DLL load failed:
 The specified module could not be found.

I know that the gpu device handling for Theano on Python 3.5.1 is broken due to CUDA still not supporting VS2015, and I think when invoked above CUDA may be using VS2008 to create the pyd library and then trying to import it with the wrong runtime (due to Python 3.5 using the new VS runtime as opposed to the old msvcr90), but why would Theano do so when I disable the gpu option and specify cpu to start with, the same options that the same Theano version on Python 2.7 has no problem working with?

**Comment by nouiz** [comment] 2016-02-23 02:50
Python 3.5 changed many things on Windows. We didn't try to make it work.
Do you want to be the first to make it work? Otherwise, use python 3.4 or
2.7 on Windows.

You can use the Theano flags "force_device=True" to disable the GPU.
device=cpu or gpu is more a hint, guideline to Theano. It don't force or
deactivate the GPU. device=cpu + force_device=True will disable the GPU.
device=gpu + force_device=True will raise an error if the GPU can't be
used, but if some ops aren't implemented on the GPU, they will still run on
the CPU.

**Comment by nouiz** [comment] 2016-05-17 17:11
closing as a duplicate of https://github.com/Theano/Theano/issues/3376

**Closed by nouiz** 2016-05-17 17:11 UTC
