### ISSUE TITLE
Not able to use gpu with new backend on power

### ISSUE THREAD

**Issue by deepali-c** [Theano/Theano#5528] opened 2017-02-10 08:36 UTC
I observed the following error while running the theano sample code from the [Using GPU](http://deeplearning.net/software/theano_versions/dev/tutorial/using_gpu.html) section to check if the new gpu backend is being used. I am working on a power pc. 

```
THEANO_FLAGS=device=cuda0,floatX=float32 python check.py
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "<path to __init__.py>", line 164, in <module>
    use(config.device)
  File "<path to __init__.py>", line 151, in use
    init_dev(device)
  File "<path to __init__.py>", line 61, in init_dev
    context.dev = dev
AttributeError: 'pygpu.gpuarray.GpuContext' object has no attribute 'dev'
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 5.829392 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```
The old gpu backend does work fine.

**Comment by nouiz** [comment] 2017-02-10 18:06
This is strange. Can you tell us which version of Theano and libgpuarray you use? 

The object GpuContext don't have a field dev, but that as all python object, we should be able to add new attribute to it.

Which version of Python and cython version?

**Comment by deepali-c** [comment] 2017-02-13 06:11
The details of the versions is;
```
Theano - rel-0.9.0beta1
libgpuarray - v0.6.0
Python -  2.7.12
cython - 0.23.4. 
```

**Comment by gspr** [comment] 2017-02-14 15:41
I am seeing the same error with Theano 0.9.0b1, gpuarray/pygpu 0.6,0, Python 3.4.3, cython 0.25.1.

**Comment by nouiz** [comment] 2017-02-14 15:48
@gspr this issue was specific to Power computers. Can you tell us if you also have a Power computer?

**Comment by gspr** [comment] 2017-02-14 16:03
@nouiz : My bad, I didn't see that part. No, this happened on Xeon system. If it matters, `pygpu.test()` works fine.

**Comment by nouiz** [comment] 2017-02-14 16:09
What is your OS/hardware?

Fred

**Comment by abergeron** [comment] 2017-02-14 17:43
Did you rebuild and install pygpu when you updated libgpuarray?

**Comment by gspr** [comment] 2017-02-15 10:07
On Tuesday, 14 February 2017 09:43:56 CET abergeron wrote:
> Did you rebuild and install pygpu when you updated libgpuarray?

Yes, if pygpu takes notice of environment variables like CPATH and
LD_LIBRARY_PATH.

**Comment by deepali-c** [comment] 2017-02-16 08:26
@nouiz Do you think that there is any chance to accommodate this before v0.10?

**Comment by nouiz** [comment] 2017-02-16 22:15
The problem is that we can't easily try to fix it as we can't reproduce it.

Do you have an idea how we could reproduce this?

There is something different in the software stack that I don't understand.

**Comment by abergeron** [comment] 2017-02-16 22:20
The problem seems to be that context doesn't have a dict.  Since it is a C object that should be reasonable.  However, I've added support for a dict a while back (at least a month ago, maybe more).  So there isn't anything to fix in the code itself, the problem is in your environment.

There are three reasons why it could not work:
 - You did not rebuild properly
 - There is an older install of pygpu shadowing your recent install
 - You somehow managed to compile with Cython older than 0.25.

**Comment by gspr** [comment] 2017-02-17 10:43
On Thursday, 16 February 2017 14:20:50 CET abergeron wrote:
> The problem seems to be that context doesn't have a dict.  Since it is a C
> object that should be reasonable.  However, I've added support for a dict a
> while back (at least a month ago, maybe more).  So there isn't anything to
> fix in the code itself, the problem is in your environment.
> 
> There are three reasons why it could not work:
>  - You did not rebuild properly
>  - There is an older install of pygpu shadowing your recent install
>  - You somehow managed to compile with Cython older than 0.25.

I can take a shot at narrowing this down in a few different
environments during the weekend. Could you help me by pointing out
roughly at what commit this dict was added?

 Best,
 Gard

**Comment by deepali-c** [comment] 2017-02-17 12:36
Yes, looks like it is because of the cython version. I tried with `cython version 0.25` and it does give the expected output. 
```
THEANO_FLAGS=device=cuda0 python check.py

Using cuDNN version 5105 on context None
Mapped name None to device cuda0: Tesla K80 (0004:03:00.0)
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float64, (False,))>), HostFromGpu(gpuarray)(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.346323 seconds
Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
  1.62323285]
Used the gpu
```

I will test it further.

**Comment by Sentient07** [comment] 2017-02-17 14:46
I had faced the exact same error twice, when I tried to update libgpuarray to match with theano's master. I had to uninstall pygpu from pip, and then reinstall it after I have built the libgpuarray. 
P.S : For someone encountering the same error, but updating cython alone hasn't helped, try doing this.

**Comment by lamblin** [comment] 2017-02-17 16:30
@gspr: According to git blame, the commit was https://github.com/Theano/libgpuarray/commit/588228903401fa4194fba3cd6e528f01692b70b1, merged in https://github.com/Theano/libgpuarray/pull/304

**Comment by deepali-c** [comment] 2017-02-20 14:04
@Sentient07 yes correct, we do need correct libgpuarray as well for this in addition to cython.

**Comment by nouiz** [comment] 2017-02-20 15:03
So I think you solved your problem, so I close this issue. If I'm wrong, tell it.

**Closed by nouiz** 2017-02-20 15:03 UTC
Labels: Crash, GPU - New back-end
