### ISSUE TITLE
"CUDA runtime error: invalid device pointer" when using magma

### ISSUE THREAD

**Issue by juancamilog** [Theano/Theano#6414] opened 2017-09-14 03:09 UTC
For the following piece of code

    import theano
    import theano.tensor as tt
    import numpy as np
    
    A = theano.shared(np.random.randn(100, 100).astype(theano.config.floatX))
    B = theano.shared(np.random.randn(100, 100).astype(theano.config.floatX))
    x = tt.nlinalg.matrix_inverse(A).dot(B)
    f = theano.function([], x)

    f()

f hangs for a couple seconds the first time it is called. In subsequent calls it prints "CUDA runtime error: invalid device pointer (17) in magma_inv_node_9fc5107b17ee9afa0a0c811ecfad60eea842c782545830eaa9ec8c425431b70a_0 at /localdata_ssd/juan/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/tmp7vmWUp/mod.cpp:216"

The graph built by theano looks like this:
HostFromGpu(gpuarray) [id A] ''   3
 |GpuDot22 [id B] ''   2
   |GpuMagmaMatrixInverse{inplace=False} [id C] ''   1
   | |GpuContiguous [id D] ''   0
   |   |<GpuArrayType<None>(float32, matrix)> [id E]
   |<GpuArrayType<None>(float32, matrix)> [id F]

Specs:
* Ubuntu 16.04 kernel 4.4.0-93
* theano bleeding edge (installed from the github repo)
* pygpu and libgpuarray ver 0.7.2
* cuda 8.0 and cudnn 7001
* magma 2.2

**Comment by notoraptor** [comment] 2017-09-14 12:45
I can not currently reproduce the problem. Some questions:
- Could you post the full error message ?
- Do you still have the file `/localdata_ssd/juan/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/tmp7vmWUp/mod.cpp` on your computer ? If so, could you upload it ?

**Comment by nouiz** [comment] 2017-09-15 12:58
We merged fix to similar problem that are hard to reproduce.

Can you update to the master version of libgpuarray and reinstall it? Maybe your problem is just another path to that hard to reproduce problem.

**Comment by diogoff** [comment] 2017-12-16 18:45
Since I'm doing [something similar](https://github.com/Theano/Theano/issues/6537), I tried to reproduce this problem, but it ran fine on my machine. I'm running:
- Ubuntu 16.04.3
- cuda 8, cudnn 6021
- magma 2.3.0
- pycuda 2017.1.1
- scikit-cuda 0.5.2
- theano 1.0.1

**Comment by nouiz** [comment] 2017-12-18 14:48
Since no news and 2 people can't reproduce it, I'll close this. If someone can reproduce it, tell us.

@juancamilog if you have it fixed, tell us would be great.

**Closed by nouiz** 2017-12-18 14:48 UTC

**Comment by juancamilog** [comment] 2017-12-18 17:24
HI all, I intalled the latest version of pygpu and no longer see this issue.

**Comment by nouiz** [comment] 2017-12-18 20:07
thanks for the confirmation.
