### ISSUE TITLE
Compilation crash on TK-1

### ISSUE THREAD

**Issue by nt** [Theano/Theano#2010] opened 2014-08-01 17:24 UTC
This is using the bleeding edge install from hash 039f7b5ca21ee4e6d3713c463c95bff5947e8035

```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1374, in process_node
    replacements = lopt.transform(node)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 4133, in constant_folding
    no_recycling=[])
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 236, in make_thunk
    compute_map, no_recycling)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/op.py", line 618, in make_thunk
    output_storage=node_output_storage)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/cc.py", line 992, in make_thunk
    keep_lock=keep_lock)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/cc.py", line 935, in __compile__
    keep_lock=keep_lock)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1372, in cthunk_factory
    key=key, fn=self.compile_cmodule_by_step, keep_lock=keep_lock)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1005, in module_from_key
    module = next(compile_steps)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1287, in compile_cmodule_by_step
    preargs=preargs)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 425, in compile_str
    return dlimport(lib_filename)
  File "/home/nicolas/Development/virt/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 290, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('/home/nicolas/.theano/compiledir_Linux-3.10.24-g6a2d13a-armv7l-with-Ubuntu-14.04-trusty-armv7l-2.7.6-32/tmpq5jChY/b48b93a428043c602bfb5b29b39b6f5c.so: undefined symbol: _Z25CudaNdarray_CopyFromArrayP11CudaNdarrayP16tagPyArrayObject', '[GpuFromHost(TensorConstant{(1, 1) of 1.0})]')
```

**Comment by icoxfog417** [comment] 2015-01-22 04:55
I also faced this error when I run `theano.test()`. It didn't occur when I used it before (around 2014/12/1).

[error](https://gist.github.com/icoxfog417/f9ead88d5436933c7b84)

I installed Theano from master, and other settings are like below.

**platform**
Windows7
Python:3.4.1

**compiler**
g++ 4.9.2

**dependencies**
numpy 1.9.1
scipy 0.15.1
Cython 0.21.2
libpython 

I don't install CUDA and PyCUDA because it is [optional](http://deeplearning.net/software/theano/install.html). Did it become required?

**Comment by nouiz** [comment] 2015-01-22 06:03
CUDA and PyCUDA are optional. This didn't changed.

Did you clear your cache? "theano-cache purge". If that do not fix the
problem, give the full error message.

**Comment by icoxfog417** [comment] 2015-01-22 06:59
I recreated environment, but the problem still occurs.

The full error message is [here](https://gist.github.com/icoxfog417/f9ead88d5436933c7b84). I think you can see some strange character (like `窶・窶・`) in the error message.

So I think it will be some encoding problem (or string problem of Python2 to 3).
If I detect the cause, I'll feedback it.

**Comment by lamblin** [comment] 2015-01-23 04:29
I know it may be a bit long, but could you try to use `git bisect` to pinpoint which commit is responsible for that change? It would help us find how to fix it.

**Comment by thirdwing** [comment] 2015-04-01 02:26
Hi, I have just test. Tk-1 can use theano with its GPU.

**Comment by nouiz** [comment] 2015-04-01 13:08
Thanks for confirmation.

I think it would be good if someone want to write a wiki page or a blog
post that tell how to do it. We could like to it from Theano doc.

For the wiki page, it could be a subpage of
https://github.com/Theano/Theano/wiki

Fred

**Comment by thirdwing** [comment] 2015-04-01 13:56
I will write add a simple wiki page after more testing. It is almost the same with a standard installation on Ubuntu, except some shared libraries' location is not standard.

**Comment by nouiz** [comment] 2015-04-01 14:51
great. Thanks.

Fred

**Comment by nouiz** [comment] 2015-07-21 17:01
As the problem is fixed, I'll close this issue.

**Closed by nouiz** 2015-07-21 17:01 UTC
