### ISSUE TITLE
problems with fast_compile

### ISSUE THREAD

**Issue by stevenxxiu** [Theano/Theano#3756] opened 2015-12-07 04:04 UTC
Commit https://github.com/Theano/Theano/commit/09d58a97726098231bb8e75464a9dedb3b1f9194 introduces the following:

     optdb.register('specialize_device', gof.EquilibriumDB(),
    -               48.6, 'fast_run')  # must be after gpu stuff at 48.5
    +               48.6, 'fast_compile', 'fast_run')  # must be after gpu stuff at 48.5

For my code this gives the following stacktrace:

      ... (my code)
      File "C:\Program Files\Python35\lib\site-packages\lasagne\updates.py", line 498, in adadelta
        grads = get_or_compute_grads(loss_or_grads, params)
      File "C:\Program Files\Python35\lib\site-packages\lasagne\updates.py", line 110, in get_or_compute_grads
        return theano.grad(loss_or_grads, params)
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 561, in grad
        grad_dict, wrt, cost_name)
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1324, in _populate_grad_dict
        rval = [access_grad_cache(elem) for elem in wrt]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1324, in <listcomp>
        rval = [access_grad_cache(elem) for elem in wrt]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1279, in access_grad_cache
        term = access_term_cache(node)[idx]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in access_term_cache
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in <listcomp>
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1279, in access_grad_cache
        term = access_term_cache(node)[idx]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in access_term_cache
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in <listcomp>
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1279, in access_grad_cache
        term = access_term_cache(node)[idx]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in access_term_cache
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in <listcomp>
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1279, in access_grad_cache
        term = access_term_cache(node)[idx]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in access_term_cache
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 973, in <listcomp>
        output_grads = [access_grad_cache(var) for var in node.outputs]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1279, in access_grad_cache
        term = access_term_cache(node)[idx]
      File "C:\Program Files\Python35\lib\site-packages\theano\gradient.py", line 1113, in access_term_cache
        input_grads = node.op.grad(inputs, new_output_grads)
      File "C:\Program Files\Python35\lib\site-packages\theano\tensor\elemwise.py", line 412, in grad
        return [DimShuffle(gz.type.broadcastable, grad_order)(
      File "C:\Program Files\Python35\lib\site-packages\theano\tensor\elemwise.py", line 164, in __init__
        (input_broadcastable, new_order))
    ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False, False), (0, 1, 3)))

, where it was working before. Does anyone know the cause? I'll try and upload a more reproducable example later.

**Comment by llllaaaa** [comment] 2015-12-08 09:09
I got the same error after commit 09d58a9, even if I set the mode to fast_run. My code is based on Lasagne. It seems the error is triggered by this line in Lasagne: activation = conved + self.b.dimshuffle('x', 0, 'x')

@ballasn @f0k Could you take a look at this?

**Comment by f0k** [comment] 2015-12-08 20:33
> It seems the error is triggered by this line in Lasagne: activation = conved + self.b.dimshuffle('x', 0, 'x')

But in @stevenxxiu's example, it is triggered in theano.grad(). Do you mean the problem disappears if you remove the bias, or do you get a different error altogether? Putting together a minimal example (preferably without Lasagne to make it easier for the Theano developers) would surely be helpful!

**Comment by llllaaaa** [comment] 2015-12-08 23:46
@f0k Thanks for your response. Sorry I made a mistake. I still got the error after remove the bias. A network definition in Lasagne like this will produce the error:

```
def build_cnn(input_var, input_length, batch_size):
    offset=9
    l_input = lasagne.layers.InputLayer(shape=(batch_size, 1, input_length + offset), input_var=input_var)
    l_output = lasagne.layers.Conv1DLayer(l_input, num_filters=3, filter_size=10, nonlinearity=identity, b=None)
    l_output = lasagne.layers.DimshuffleLayer(l_output,(0,2,1))
    l_output = lasagne.layers.ReshapeLayer(l_output,(batch_size*input_length,3))
    return l_output
```

I did not find the exact cause, so I'm not able to provide a pure Theano example. It seems the error is related to Conv1DLayer.

**Comment by f0k** [comment] 2015-12-09 12:14
Minimal example:
```python
import theano
import numpy as np
# set up variables for 1D convolution
x = T.tensor3('x')
w = T.tensor3('w')
# this is what Lasagne's Conv1DLayer does internally to do a 1d convolution via conv2d:
# 1. introduce additional dimension
xd = x.dimshuffle(0, 1, 'x', 2)
wd = w.dimshuffle(0, 1, 'x', 2)
# 2. call conv2d
c = T.nnet.conv2d(xd, wd)
# 3. drop added dimension
c = c[:, :, 0, :]
# compute gradient of some loss wrt. weights
loss = (c - T.tensor3('t')).mean()
grad = theano.grad(loss, w)
```
The error is:
```
Traceback (most recent call last):
  File "theanobug.py", line 29, in <module>
    grad = theano.grad(loss, w)
  File "/raid/user/jan/install/Theano-git/theano/gradient.py", line 561, in grad
    grad_dict, wrt, cost_name)
  File "/raid/user/jan/install/Theano-git/theano/gradient.py", line 1324, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/raid/user/jan/install/Theano-git/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/raid/user/jan/install/Theano-git/theano/gradient.py", line 1113, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/raid/user/jan/install/Theano-git/theano/tensor/elemwise.py", line 412, in grad
    return [DimShuffle(gz.type.broadcastable, grad_order)(
  File "/raid/user/jan/install/Theano-git/theano/tensor/elemwise.py", line 164, in __init__
    (input_broadcastable, new_order))
ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False, False), (0, 1, 3)))
```
When we replace `c = c[:, :, 0, :]` by `c = c.dimshuffle(0, 1, 2)`, the error occurs on that line already. It seems the broadcast pattern correctly went through the convolution in the past, but doesn't do so now?

**Comment by nouiz** [comment] 2015-12-09 16:23
I'm able to reproduce this. I have a quick fix locally here but due to
bumpy internet at NIPS, I'm not able to make a PR with my suggested fix.

The problem is that all the abstract op (and all previous one) was
hardcoding a broadcast pattern of False/False for the  last 2 dimensions. I
think that if both inputs are broadcastable in the corresponding
dimensions, the output will be broadcastable in that dimension.

I'm not sure when I can finish this fix.

**Comment by f0k** [comment] 2015-12-09 17:56
> The problem is that all the abstract op (and all previous one)

Are you sure about the previous ones? I haven't checked, but I guess this was working in an earlier Theano version.

> was hardcoding a broadcast pattern of False/False for the last 2 dimensions. I think that if both inputs are broadcastable in the corresponding dimensions, the output will be broadcastable in that dimension.

I guess you'll also have to take into account the `border_mode`. A broadcastable dimension just tells you that the size in that dimension is guaranteed to be 1. Maybe the easiest solution would be using that information to update the filter_shape and input_shape, compute the output shape from that and make all output dimensions broadcastable that are of length 1. This would allow introducing additional broadcast information just via the input_shape and filter_shape arguments to conv2d(), though, I'm not sure if Theano can cope with that?

**Comment by llllaaaa** [comment] 2015-12-09 18:01
https://github.com/Theano/Theano/tree/754baeb3b2e85e4bbd1607d284c0a36ab0b5ea7e
I tested. This the last working version. Commit 09d58a9 caused the error.

**Comment by nouiz** [comment] 2015-12-16 13:48
This should be fixed by gh-3774 in master. Thanks for the report and good example.

**Closed by nouiz** 2015-12-16 13:48 UTC
