### ISSUE TITLE
No way to make RNG shape partially symbolic

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3306] opened 2015-08-18 23:07 UTC
I'd really like to be able to say, `theano.rng.normal((x.shape[0], 100))` where `x` is a tensor, but currently I can't. If I try and make it symbolic via `constant` and `concatenate`, I get errors from `get_vector_length`.

**Comment by lamblin** [comment] 2015-08-24 16:56
That is strange, it works for me, both with `theano.tensor.shared_randomstreams.RandomStreams` and for `theano.sandbox.rng_mrg.MRG_RandomStreams`.
Are you using `theano.tensor.raw_random.normal` directly? If so, the first argument is the random state, that should be passed explicitly, not the shape.

**Comment by nouiz** [comment] 2015-09-01 14:34
I'll close this now as it work for @lamblin and ther, but if you know how to reproduce it, there could be a case missing. Just reopen the ticket if needed.

Also, can you try to always give the stack trace with the exact error message? This help enormously to replicate this and understand what is going on even without code to reproduce it.

thanks.

**Closed by nouiz** 2015-09-01 14:34 UTC

**Comment by dwf** [comment] 2015-11-20 21:30
This must've gotten somehow fixed in a subsequent version as I'm not observing it anymore with a recent checkout. Anyway, thanks for fixing it whoever did.
