### ISSUE TITLE
Alerting instructions before opening a PR

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4922] opened 2016-08-31 17:11 UTC
With many user based questions we get on github's issue page, we can have some instructions outlining the guidelines on how the issue has to be before opening would help in reducing them. It is currently being done in scikit-learn and I think we could adapt something similar.
It looks something like this, 
<img width="1180" alt="screenshot at aug 31 19-10-49" src="https://cloud.githubusercontent.com/assets/6195312/18138793/bdb3bf64-6fae-11e6-9ac2-27b7a724f045.png">

**Comment by Sentient07** [comment] 2016-09-06 17:40
I'll do a PR for this today.

**Comment by lamblin** [comment] 2016-09-06 21:35
#4625 is a duplicate issue, and we just assigned @SinaHonari to work on it.

**Comment by nouiz** [comment] 2016-09-07 13:58
Closing as duplicate of gh-4625

**Closed by nouiz** 2016-09-07 13:58 UTC
