### ISSUE TITLE
Gradient update in convolutional neural net not working

### ISSUE THREAD

**Issue by MagicalFox** [Theano/Theano#2838] opened 2015-04-27 13:31 UTC
I'm implementing a convolutional encoder and have some problems. When I test the model with two standard CNN layers the code works fine (I'm using RMSprop as optimizer). However when I add in a fully connected layer on top of the second CNN layer it stops updating the parameters. My question is: how does gradient work with a theano reshape function reshaping a tensor4 to a matrix followed by another one that reshapes the matrix back to a tensor4?

**Comment by nouiz** [comment] 2015-04-27 20:31
Without more information we can't help more. But we know that it work for
us for many years. Did you saw this cnn tutorial:

http://deeplearning.net/tutorial/lenet.html

Maybe it can help you.

The reshape do not cause any problem for the gradient. It work well and
this is a very simple gradient. I would be very surprised that the reshape
is the cause of the problem. What make you think this?

An example of rmsprop that work is in that tutorial:

http://deeplearning.net/tutorial/lstm.html

It is possible that your implementation do it differently and is good, but
as you have problems, it can help you to look at how it is done there.

**Comment by nouiz** [comment] 2017-02-24 16:15
as no news, closing.

**Closed by nouiz** 2017-02-24 16:15 UTC
