### ISSUE TITLE
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>>

### ISSUE THREAD

**Issue by yunqiw** [Theano/Theano#3707] opened 2015-11-30 22:17 UTC
hi, I got an error like this, not sure how to fix it

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.Exception'> Constant{300} is already owned by another fgraph local_elemwise_alloc
ERROR (theano.gof.opt): Optimization failure due to: local_elemwise_alloc
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(dot.0, Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1822, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 592, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 530, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 363, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/fg.py", line 394, in __import__
    raise Exception("%s is already owned by another fgraph" % r)
Exception: Constant{300} is already owned by another fgraph

**Comment by nouiz** [comment] 2015-12-01 01:23
duplicate of gh-3663. See that ticket for a work around.

**Closed** 2015-12-01 01:25 UTC
