### ISSUE TITLE
BUG IN FGRAPH.REPLACE OR A LISTENER

### ISSUE THREAD

**Issue by jonycgn** [Theano/Theano#2924] opened 2015-05-19 15:09 UTC
hi,

i'm getting these error messages recently, and from the debugprint of the function it seems the graph is left in a half-optimized state (there are, for example, several elementwise divisions chained together, which could easily be folded into one operation).

the graph is a complicated beast, so i'm not really sure what exactly triggered the problem.

i've checked the graph for instances of gpuallocempty. as far as i can see, these nodes appear as placeholders for the results of dnn convolutions. i'm not sure why it would want to merge any of these. plus it seems the problem in doing so is just a broadcast pattern mismatch.

any ideas?

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f5de5e44890>
ERROR:theano.gof.opt:SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f5de5e44890>
ERROR (theano.gof.opt): Traceback:
ERROR:theano.gof.opt:Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 188, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 74, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 1783, in apply
    gopt.apply(fgraph)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 612, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/toolbox.py", line 257, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/fg.py", line 473, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer')

ERROR:theano.gof.opt:Traceback (most recent call last):
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 188, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 74, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 1783, in apply
    gopt.apply(fgraph)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/opt.py", line 612, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/toolbox.py", line 257, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/users-local/balle/anaconda/envs/2015-04-28/lib/python2.7/site-packages/theano/gof/fg.py", line 473, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer')
```

**Comment by nouiz** [comment] 2015-05-20 14:32
Can you update Theano to the development version to make sure it is fixed?

Then, can you dump the function so that we are able to reproduce it?

http://deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

thanks

**Comment by auroua** [comment] 2015-11-01 06:03
I got the same error when I trying the example  [A Real Example: Logistic Regression](http://deeplearning.net/software/theano/tutorial/examples.html#a-real-example-logistic-regression)

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[0], acc_dtype=float64}.0, HostFromGpu.0, TensorType(float64, vector), TensorType(float32, vector), 'local_gpu_careduce') local_gpu_careduce
ERROR (theano.gof.opt): Optimization failure due to: local_gpu_careduce
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/auroua/software/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 1527, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/home/auroua/software/anaconda/lib/python2.7/site-packages/theano/gof/toolbox.py", line 259, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/auroua/software/anaconda/lib/python2.7/site-packages/theano/gof/fg.py", line 474, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{axis=[0], acc_dtype=float64}.0, HostFromGpu.0, TensorType(float64, vector), TensorType(float32, vector), 'local_gpu_careduce')


my .theanorc file is

[global]
device = gpu
floatX=float32

[nvcc]
fastmath = True

**Comment by nouiz** [comment] 2015-11-02 04:10
As there is no new (and from memory such case was fixed), I'll close this ticket. If you still have problems, tell us.

**Closed by nouiz** 2015-11-02 04:10 UTC
