### ISSUE TITLE
Optimizations override ifelse lazy evaluation

### ISSUE THREAD

**Issue by amishtal** [Theano/Theano#3119] opened 2015-07-08 16:56 UTC
I recently encountered an issue using the ifelse op as the final operation in an update for a shared variable. One branch modified the entire value of the shared variable, while the other used 'set_subtensor' to modify only a portion of it. Both branches were being computed if I ran with 'optimizer=fast_run', while 'optimizer=fast_compile' resulting in the correct lazy evaluation and faster execution time. I eventually narrowed the problem down to the 'inplace_elemwise_optimizer' and 'local_inplace_setsubtensor' optimizations. Excluding them from the optimization process resulted in the correct lazy evaluation.

This occured with both the 0.7.0 release and the most recent developement version.

**Comment by lamblin** [comment] 2015-07-09 01:47
Thanks for the report and the investigation.
I'm closing it as a duplicate of #3004.

**Closed by lamblin** 2015-07-09 01:47 UTC

**Comment by nouiz** [comment] 2015-07-18 12:32
@lamblin, would an example help us doing the fix? He was proposing to make
one.
