### ISSUE TITLE
Optimization failure due to: local_IncSubtensor_serialize

### ISSUE THREAD

**Issue by JyotiJ** [Theano/Theano#3914] opened 2016-01-22 04:02 UTC
How can I debug issues of this sort?
What does memory error mean when RAM is still available?
ERROR (theano.gof.opt): Optimization failure due to: local_IncSubtensor_serialize
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{second,no_inplace}.0, IncSubtensor{Inc;::, int64, ::, ::}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/jyoti/Theano/theano/gof/opt.py", line 1782, in process_node
    replacements = lopt.transform(node)
  File "/home/jyoti/Theano/theano/tensor/opt.py", line 3033, in local_IncSubtensor_serialize
    new_add = T.add(*new_inputs)
  File "/home/jyoti/Theano/theano/gof/op.py", line 600, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/jyoti/Theano/theano/tensor/elemwise.py", line 546, in make_node
    for i in inputs])
  File "/home/jyoti/Theano/theano/scalar/basic.py", line 869, in make_node
    inputs = [as_scalar(input) for input in inputs]
  File "/home/jyoti/Theano/theano/scalar/basic.py", line 103, in as_scalar
    from ..tensor import TensorType, scalar_from_tensor
MemoryError

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x74c38b8c>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/jyoti/Theano/theano/gof/opt.py", line 232, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/jyoti/Theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/jyoti/Theano/theano/gof/opt.py", line 2179, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/jyoti/Theano/theano/gof/graph.py", line 969, in io_toposort
    iset = set(inputs)
MemoryError

**Comment by lamblin** [comment] 2016-01-26 16:54
I'm not sure what that MemoryError means, it may depend of the machine's setup. For instance, some clusters or shared environment will limit the amount of RAM available for each process.
Is your graph especially large? How many inputs do you have in your theano function?

**Comment by JyotiJ** [comment] 2016-01-27 04:33
Input to the theano function is 3 layer laplacian pyramid of an image (256*256) ie. (3*256*256,3*128*128,3*64*64)

**Comment by nouiz** [comment] 2016-01-28 06:53
The error happen during the compilation not fitting computation. Give more
memory to your process or use less memory before compiling the Theano
function.

**Comment by JyotiJ** [comment] 2016-01-28 09:15
Is there a graph depth limit or something similar? I don't get these errors now, but segmentation fault.
I am trying to use theano to build a multiscale CNN model which has close to 0.5 million trainable parameters(params in the equations). 
Model has 4 layers and I cannot update the weights for first layer ( It throws segmentation fault ,when function applies updates for the first layer, but works fine for the updates of remaining 3 layers). What could be the possible cause?

Will theano throw a segmentation fault if function is not differentiable wrt some parameters ?
Is there some memory limit on theano function?
This error occurs during functioncompilation

**Comment by nouiz** [comment] 2016-01-29 17:44
By default, python have a recursion limit of 1000. If you didn't change
this, it should not be the cause of the segfault. But if you raised it, it
could be.

The number of parameter do not influence the number of node in the graph,
but only the memory usage. Can you try with smaller parameter size? Like
having only 1 layer. Just to help identify where this come from.

In theory, a segfault should never happen. There is no limit in memory
inside Theano itself, execpt size that should fix in int64 at a few places.
So the segfault is trouble some.

Can you uninstall Theano a few times, to be sure you don't have mixed
version and delete your theano cache. Then reinstall theano development
version?

**Comment by JyotiJ** [comment] 2016-01-30 07:40
I have increased the python recursion limit. I have tried uninstalling theano and installing it again .I have theano development version. Having only one layer it works, but with 4 layers its just the first layer that I cannot update the parameters for. I understand no. of parameters don't influence no. of node in the graph, but I believe complexity of the gradient does. 
Please suggest some possible work around.

**Comment by nouiz** [comment] 2016-02-01 02:16
Can you give the output of "ulimit -a" and "free"?

**Comment by JyotiJ** [comment] 2016-02-01 04:19
Now I am running the code on a 32GB RAM machine. Here also it throws segmentation fault.
These are the outputs:
jyoti@d1:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3609684
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 3609684
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
jyoti@d1:~$ free
             total       used       free     shared    buffers     cached
Mem:     462271472  460149552    2121920      34228     325288  273038464
-/+ buffers/cache:  186785800  275485672
Swap:      4882428    4882428          0

**Comment by nouiz** [comment] 2016-10-14 00:14
We dropped this one, but it was probably missing memory on the user computer, so closing.

**Closed by nouiz** 2016-10-14 00:14 UTC
