### ISSUE TITLE
Got Theano mysterious error after update from 0.8.0 to 0.8.2 when implementing CNN-LSTM

### ISSUE THREAD

**Issue by mememimis** [Theano/Theano#4990] opened 2016-09-19 17:23 UTC
While i was working i made an update for both keras and theano. My numerous times runned model up to that point hadnt no problem to executed. But when i made the update, for a simple network like the following :
 `             
              model = Sequential()
              model.add(Embedding(max_features, embedding_size, input_length=maxlen))
               model.add(Dropout(0.25))
              model.add(Convolution1D(nb_filter=nb_filter,
                        filter_length=filter_length,
                        border_mode='valid',
                        activation='relu',
                        subsample_length=1))
             model.add(MaxPooling1D(pool_length=pool_length))
             model.add(LSTM(lstm_output_size))
             model.add(Dense(1))
            model.add(Activation('sigmoid'))

           model.compile(loss='binary_crossentropy',
                   optimizer='adam',
                  metrics=['accuracy'])

           print('Train...')
          model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=nb_epoch,
               validation_data=(X_test, y_test))
`

I am getting this error :
`Traceback (most recent call last):
  File "C:/Users/usera/Desktop/2/fgdgfgf.py", line 73, in <module>
    validation_data=(X_test, y_test))
  File "C:\Users\usera\Anaconda2\lib\site-packages\keras\models.py", line 620, in fit
    sample_weight=sample_weight)
  File "C:\Users\usera\Anaconda2\lib\site-packages\keras\engine\training.py", line 1104, in fit
    callback_metrics=callback_metrics)
  File "C:\Users\usera\Anaconda2\lib\site-packages\keras\engine\training.py", line 822, in _fit_loop
    outs = f(ins_batch)
  File "C:\Users\usera\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 672, in __call__
    return self.function(*inputs)
  File "C:\Users\usera\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Users\usera\Anaconda2\lib\site-packages\theano\gof\link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Users\usera\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError: alloc failed
Apply node that caused the error: Alloc(TensorConstant{(1L, 1L, 1L) of 0.0}, TensorConstant{24}, Elemwise{Composite{((i0 * i1) // i2)}}[(0, 0)].0, TensorConstant{280})
Toposort index: 145
Inputs types: [TensorType(float32, (True, True, True)), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(1L, 1L, 1L), (), (), ()]
Inputs strides: [(4L, 4L, 4L), (), (), ()]
Inputs values: [array([[[ 0.]]], dtype=float32), array(24L, dtype=int64), array(-450L, dtype=int64), array(280L, dtype=int64)]
Outputs clients: [[IncSubtensor{Inc;:int64:}(Alloc.0, Subtensor{::int64}.0, Constant{24}), IncSubtensor{InplaceInc;int64::}(Alloc.0, IncSubtensor{Inc;:int64:}.0, Constant{0}), forall_inplace,cpu,grad_of_scan_fn}(TensorConstant{24}, Elemwise{tanh}.0, Subtensor{int64:int64:int64}.0, Alloc.0, Elemwise{Composite{(i0 - sqr(i1))}}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Alloc.0, Alloc.0, TensorConstant{24}, TensorConstant{24}, TensorConstant{24}, TensorConstant{24}, TensorConstant{24}, lstm_1_U_o, lstm_1_U_f, lstm_1_U_i, lstm_1_U_c, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
`
Any ideas would are appreciated.

**Comment by nouiz** [comment] 2016-09-19 19:11
It seem that you are missing memory. Could you have also changed your model
to take more memore like bigger batch size, bigger layer size, more layers,
new or bigger dataset, ...? Could you have something else running that take
much memory?

Investigating the message more, It try to allow something of size (24,
-450, 280). Do you have an idea where the -450 could come from?

Fred

**Comment by mememimis** [comment] 2016-09-19 19:29
My pc has 64Gb memory it is unreasonable for my dataset to exceed that memory capacity. I honestly , cant anwser from where the -450 comes from. For instance if i run this toy example [https://github.com/fchollet/keras/blob/master/examples/imdb_cnn_lstm.py](url) i am getting the same error. And this is happening only on keras 1.0.8 and Theano 0.8.2 and not when i use keras 1.0.3 and theano 0.8.0. I just cant get it.
nick

**Comment by nouiz** [comment] 2016-09-19 19:41
Can you try with keras 1.0.3 and Theano 0.8.2? I would guess this is due to
change in keras.

Do you use RNN or other variant? Make sure to not unroll the loop. It saves
memory.

**Comment by mememimis** [comment] 2016-09-19 19:52
I tried , and yelds the same error. I used the them all, LSTM, Bi-lstm , RNN , bi-RNN,GRU , same problem. Shall i ask if you have any resources in order to see the changes , and hopefully clean this mess?

**Comment by nouiz** [comment] 2016-09-19 19:54
Are you able to reproduce it working? If so, you could do a git bisect to
help find when the problem started to appear.

**Comment by mememimis** [comment] 2016-09-19 19:57
Yes i can. However , i havent used git bisect again , so i have to dig on it a bit . Thanks for the advice :)

**Comment by nouiz** [comment] 2016-09-27 13:46
Do you have news about this?

**Comment by mememimis** [comment] 2016-09-28 08:18
actually the problem was solved because of the newest version of keras...

**Comment by nouiz** [comment] 2016-09-28 13:44
closing. I suppose it was an issue with keras that they fixed.

**Closed by nouiz** 2016-09-28 13:44 UTC
