### ISSUE TITLE
GpuDnnPoolGrad broken/missing for average pooling?

### ISSUE THREAD

**Issue by ebenolson** [Theano/Theano#3347] opened 2015-08-31 19:56 UTC
Example:

    import theano
    import theano.tensor as T
    import theano.tensor.signal.downsample
    import numpy as np

    X = T.matrix()
    X2 = T.signal.downsample.max_pool_2d(X, ds=(2, 2), mode='average_inc_pad', ignore_border=True)

    l = X2.sum()
    g = T.grad(l, X)

    x0 = np.zeros((10, 10), dtype='float32')
    g.eval({X: x0})

Error:

    RuntimeError: GpuDnnPoolGrad: error doing operation: CUDNN_STATUS_BAD_PARAM.
    Apply node that caused the error: GpuDnnPoolGrad(GpuContiguous.0, CudaNdarrayConstant{[[[[-1.]]]]}, GpuContiguous.0, GpuDnnPoolDesc{ws=(2, 2), stride=(2, 2), mode='average_inc_pad', pad=(0, 0)}.0)
    Toposort index: 23
    Inputs types: [CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, (True, True, True, True)), CudaNdarrayType(float32, (False, True, False, False)), <theano.gof.type.CDataType object at 0x7fe8032ee8d0>]
    Inputs shapes: [(1, 1, 10, 10), (1, 1, 1, 1), (1, 1, 5, 5), 'No shapes']
    Inputs strides: [(0, 0, 10, 1), (0, 0, 0, 0), (0, 0, 5, 1), 'No strides']
    Inputs values: ['not shown', <CudaNdarray object at 0x7fe803088d30>, 'not shown', <PyCObject object at 0x7fe805948a30>]
    Outputs clients: [[GpuReshape{2}(GpuDnnPoolGrad.0, MakeVector{dtype='int64'}.0)]]

    HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
    HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by kashif** [comment] 2015-09-05 08:39
Yes I do not see the error if I revert back to before #3139 by @sebastien-j was merged... so I suspect the problem is there. Let me investigate.

**Comment by sebastien-j** [comment] 2015-09-07 00:11
The problem comes from `theano/sandbox/cuda/dnn/local_avgpool_dnn_grad_stride`.
```
ret = GpuDnnPoolGrad()(gpu_contiguous(inp),
                       gpu_contiguous(numpy.empty((1,1,1,1),
                           dtype=numpy.float32)),
                       gpu_contiguous(inp_grad),
                       desc)
```
I thought I had made a test to verify this this worked, but I obviously blundered. My apologies.

`CUDNN_STATUS_BAD_PARAM` is due to a shape mismatch. I think that replacing `gpu_contiguous(numpy.empty((1,1,1,1), dtype=numpy.float32))` by `gpu_contiguous(inp_grad)` would work.

To avoid using additional memory, it might be possible to put both both `out` and `inp_grad` at the same address, but this would definitely need to be tested.

**Comment by kashif** [comment] 2015-09-07 06:44
yes @sebastien-j that seems to fix the issue. I can add some tests for it in the coming days?

**Comment by sebastien-j** [comment] 2015-09-07 17:22
Sure, you may add some tests. It might be worth verifying whether the following code also works, and if it decreases memory usage.

```
contiguous_inp_grad = gpu_contiguous(inp_grad)
ret = GpuDnnPoolGrad()(gpu_contiguous(inp),
                       contiguous_inp_grad,
                       contiguous_inp_grad,
                       desc)
```
The same change should probably also be done in ` theano/sandbox/gpuarray/dnn.py`.

As this was my mistake, please tell me if you want me to do something.

**Comment by nouiz** [comment] 2016-09-08 19:59
fixed long time ago by https://github.com/Theano/Theano/pull/3368

**Closed by nouiz** 2016-09-08 19:59 UTC
