### ISSUE TITLE
Time differs between device=gpu0 and device=cuda0 when compiling theano functions

### ISSUE THREAD

**Issue by cshanbo** [Theano/Theano#5556] opened 2017-02-16 08:09 UTC
Hi, 
I was using the new version of Theano, which has a new back-end.
I found that when using 'device=cuda0', the compiling time is much longer than using 'device=gpu0'.
I'm curious about the key point about the cause of the time difference.

**Comment by lamblin** [comment] 2017-02-16 17:44
There is some kernel compilation that was cached on disk in the old back-end, and that the new back-end currently caches only in RAM, so it does some compilation once per process.
A disk cache for libgpuarray is currently in progress and should be merged in the next couple of weeks.

**Comment by nouiz** [comment] 2017-02-17 16:51
closing as a duplicate of https://github.com/Theano/Theano/issues/4817

Here is the PR that was started on the disk cache. Work on it will only continue after Theano 0.9 rc1 is done.

https://github.com/Theano/libgpuarray/pull/335

**Closed by nouiz** 2017-02-17 16:51 UTC
Labels: GPU - New back-end
