### ISSUE TITLE
CNMeM is disabled, cuDNN 5005 

### ISSUE THREAD

**Issue by meshiguge** [Theano/Theano#4677] opened 2016-06-30 19:06 UTC
I am trying to run theano on  GeForce GTX TITAN Black
But it will print 
`CNMeM is disabled, cuDNN 5005 `

and the program can run normally, is anything wrong? 

thank you

**Comment by stergioc** [comment] 2016-06-30 19:15
You can enable the CNMeM by adding 

```
[lib]
cnmem = 1
```

in your `~/.theanorc` file. You can find more details here > [http://deeplearning.net/software/theano/library/config.html#envvar-THEANORC](url)

**Comment by meshiguge** [comment] 2016-06-30 19:19
thank you,
may I ask that  : it must be added to theanorc? 
I saw the program run normally. 
should I added it ?

**Comment by stergioc** [comment] 2016-06-30 19:25
This is up to you. Check this here > http://deeplearning.net/software/theano/library/config.html#config.config.lib.cnmem

**Comment by lamblin** [comment] 2016-06-30 20:27
Closing as this is a request for support, not a bug report.
Please use the `theano-users` mailing list or StackOverflow.

**Closed by lamblin** 2016-06-30 20:27 UTC
