### ISSUE TITLE
GpuCAReduceCuda returning incorrect values

### ISSUE THREAD

**Issue by lachlants** [Theano/Theano#5379] opened 2017-01-03 02:41 UTC
Hello, It appears that GpuCAReduceCuda is silently returning bad values in the new gpuarray backend with the current master e.g.

>import theano
>import numpy
>input = theano.tensor.tensor4()
>f = theano.function([input], input.mean())
>x = numpy.random.uniform(0.0, 1.0, (64,128,32,32)).astype(numpy.float32)
>print("Mean TEST = ", f(x))

I get a result of 0.14  (device=cuda) instead of ~0.5 (device=cpu or device=gpu) .

**Comment by khaotik** [comment] 2017-01-05 15:20
@lachlants I'm not able to reproduce this issue with your test code.

My system is ubuntu 16.04 / GeForce GTX 750 Ti / 367.57 /CUDA 8.0

A brief checklist would be:

- Some obvious mistake.
- Make sure to install lastest dev branch of Theano and libgpuarray
- Clean theano cache
- Run with `cuda-memcheck` for potential hardware defect.

If still corrupts:

- Does it totally corrupt randomly (like popping `NaN`s), or somewhat predictable?
- What's your OS / GPU / video driver / cuda toolkit ?
- What's your `.theanorc` ?
- `theano.printing.debugprint(f)` ?

**Comment by nouiz** [comment] 2017-01-09 16:54
I also have the good answer ~0.5. If you still have the problems, answer the question in the above comment.

**Comment by lachlants** [comment] 2017-01-17 00:36
Hey, sorry for the slow reply. I'm using the latest checkout of master with Ubuntu 16.04 /  gcc-4.9.3 / GTX1080 / 375.26 / CUDA 8.0. The command I'm using to execute the code is:

> THEANO_FLAGS=device=cuda2 python3 -c "import theano; import numpy; z=theano.tensor.tensor4();f=theano.function([z],z.mean());x=numpy.random.uniform(0.0, 1.0, (64,128,32,32)).astype(numpy.float32);print(f(x))"

I cleared the theano cache with "rm -r ~/.theano/*", removed my .theanorc and tried it on two 1080s within the same machine and both consistently return 0.1406. I also tried it on a machine with an identical setup except gcc-5.4.0 and got the same result... setting device=cpu or gpu I get the correct result ~0.5.

Here's the debugprint(f):

> HostFromGpu(gpuarray) [id A] 'mean'   14
>  |GpuElemwise{Composite{((((i0 / i1) / i2) / i3) / i4)}}[(0, 0)]<gpuarray> [id B] ''   13
>    |GpuCAReduceCuda{add} [id C] ''   6
>    | |GpuFromHost<None> [id D] ''   4
>    |   |<TensorType(float64, 4D)> [id E]
>    |GpuSubtensor{int64} [id F] ''   12
>    | |GpuElemwise{Cast{float64}}[]<gpuarray> [id G] ''   8
>    | | |GpuFromHost<None> [id H] ''   7
>    | |   |MakeVector{dtype='int64'} [id I] ''   5
>    | |     |Shape_i{0} [id J] ''   3
>    | |     | |<TensorType(float64, 4D)> [id E]
>    | |     |Shape_i{1} [id K] ''   2
>    | |     | |<TensorType(float64, 4D)> [id E]
>    | |     |Shape_i{2} [id L] ''   1
>    | |     | |<TensorType(float64, 4D)> [id E]
>    | |     |Shape_i{3} [id M] ''   0
>    | |       |<TensorType(float64, 4D)> [id E]
>    | |Constant{0} [id N]
>    |GpuSubtensor{int64} [id O] ''   11
>    | |GpuElemwise{Cast{float64}}[]<gpuarray> [id G] ''   8
>    | |Constant{1} [id P]
>    |GpuSubtensor{int64} [id Q] ''   10
>    | |GpuElemwise{Cast{float64}}[]<gpuarray> [id G] ''   8
>    | |Constant{2} [id R]
>    |GpuSubtensor{int64} [id S] ''   9
>      |GpuElemwise{Cast{float64}}[]<gpuarray> [id G] ''   8
>      |Constant{3} [id T]

Could it be something to do with my libgpuarray / pygpu setup? Unless I run it within the libgpuarray/lib directory I get the following error: ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required).

**Comment by abergeron** [comment] 2017-01-23 18:05
If you have that problem it probably means that you have an install of pygpu somewhere and you override it by changing the current directory.  This is a bad idea, because you probably also have an old install of libgpuarray.

Make sure to clean all old installs of libgpuarray/pygpu and reinstall them.

**Comment by khaotik** [comment] 2017-02-10 23:34
I suspect this is yet another case of #5530

**Comment by nouiz** [comment] 2017-02-14 14:16
We merged in libgpuarray a check of the driver version to not work with bad version.

If by chance, using a driver version know to work well don't work well, you can reopen the issue, but I'm pretty sure this is the problem, so I close this issue.

**Closed by nouiz** 2017-02-14 14:16 UTC
