### ISSUE TITLE
Support newer gcc

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5845] opened 2017-04-12 18:55 UTC
At least 6.3.1 don't work with Theano. See:

[theano-users] Narrowing conversion error(transitioning from the old cuda backend to gpuarray)

**Comment by lamblin** [comment] 2017-04-26 20:11
I've had exactly that problem with a new installation of Ubuntu 17.04, that comes with gcc 6.3.0.
The missing symbol `_ZdlPvm` seems to come from libstdc++.
In fact, setting `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6` seems to solve the importing issue.

I don't know what a clean way of doing that would be.

**Comment by nouiz** [comment] 2017-04-26 20:15
Do you have only one g++ installed on the computer or multiple?

**Comment by lamblin** [comment] 2017-04-26 20:17
Just one.

**Comment by nouiz** [comment] 2017-04-26 20:18
Do you have the OS g++ and the conda one? Maybe the conflict?

**Comment by lamblin** [comment] 2017-04-26 20:24
I do not have anaconda's gcc, however I have `libstdc++.so.6.0.19` distributed by Anaconda, and `libstdc++.so.6.0.22` by the OS, and the Anaconda version does not seem to define `_ZdlPvm`.

**Comment by nouiz** [comment] 2017-04-26 20:28
If you use the os Python, does it work?

Can you update the anaconda libstdc++ ?

**Comment by lamblin** [comment] 2017-04-26 20:33
It does not look like `libstdc++` is part of a package I could update. However, there is libgcc, currently at 4.8.5, which could be updated to 5.2.0, I will check later what it does.
For the OS Python, I will try without Anaconda at another time (I do not have the dependencies like numpy installed from the OS).

**Comment by msarahan** [comment] 2017-04-27 16:10
Anaconda will be shipping a gcc/g++/libstdc++ version 6.3.0 soon.  You can download test packages from my channel or from @mingwandroid's channel.

https://anaconda.org/msarahan/libstdcxx_linux-cos5-x86_64

I expect that these are backwards compatible with earlier compilers, but have not tested much.

**Comment by lamblin** [comment] 2017-04-28 01:55
Thanks for the information!

**Comment by lamblin** [comment] 2017-04-28 03:12
I can confirm that it works with the OS packages.
So, there is really nothing wrong with gcc 6.3 and Theano, it is just a mismatch between the OS and Anaconda.

**Comment by nouiz** [comment] 2017-04-28 15:09
If you have time, I think testing now the new packages would be useful. To make sure it fix the problem with anaconda.

**Comment by lamblin** [comment] 2017-06-09 15:42
I can finally confirm that it works after having installed the newer version
```
$ conda install -c rdonnelly libstdcxx_linux-cos5-x86_64=6.3.0
```

**Comment by mingwandroid** [comment] 2017-06-09 20:47
Great. I'll be moving to GCC 7.1 soon.

**Closed** 2017-06-10 02:03 UTC
Labels: CCW

**Comment by milani** [comment] 2017-06-19 10:35
I tried to use theano in Ubuntu 17.04 using gcc 5.4.1. I still get the error:

```
~/.theano/compiledir_Linux-4.10--generic-x86_64-with-Ubuntu-17.04-zesty-x86_64-3.5.3-64/tmp63qfk4r1/mod.cpp:19:0: error: narrowing conversion of ‘190’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 static const char kbin_mrg_uniform[] = { 0x7f,0x45,.....
```

**Comment by lamblin** [comment] 2017-06-20 20:32
This is a different error. Please open a different ticket in that case.
It looks like you specified an additional argument, `-Wnarrowing`, that transforms a warning into an error.

**Comment by milani** [comment] 2017-06-20 20:45
I didn't set additional argument. By the way, installing from master fixed the issue for me.

**Comment by lamblin** [comment] 2017-06-20 21:03
OK, I'm not sure why the compiler decided to be more difficult then :)
Glad to hear that upgrading to master worked.
