### ISSUE TITLE
IfElse evaluates wrong branch

### ISSUE THREAD

**Issue by cooijmanstim** [Theano/Theano#3552] opened 2015-10-24 16:58 UTC
I am seeing a strange problem involving the gradient of ifelse that causes the wrong branch to be evaluated.  Here's a test case:

```python
    from collections import OrderedDict
    import numpy as np
    import theano, theano.tensor as T
    from theano.ifelse import ifelse

    x = T.matrix("x")

    axes = [0]
    false = theano.shared(0., name="false")
    a = x.mean(axis=axes, keepdims=True)
    b = theano.shared(np.zeros((0,) * a.ndim))
    c = ifelse(false,
	    T.addbroadcast(b, *axes),
	    T.zeros_like(a))

    g = T.grad((a + c).sum(), x)
    f = theano.function([x], g,
	updates=OrderedDict([
	    (b, T.unbroadcast(c + 1, *axes)),
	]))

    print(f(np.identity(3)))
```

The error is:

    Traceback (most recent call last):
    File "theano_ifelse.py", line 23, in <module>
	print(f(np.identity(3)))
    File "/home/tim/dev/Theano/theano/compile/function_module.py", line 867, in __call__
	storage_map=getattr(self.fn, 'storage_map', None))
    File "/home/tim/dev/Theano/theano/gof/link.py", line 314, in raise_with_op
	reraise(exc_type, exc_value, exc_trace)
    File "/home/tim/.local/lib/python3.5/site-packages/six.py", line 685, in reraise
	raise value.with_traceback(tb)
    File "/home/tim/dev/Theano/theano/compile/function_module.py", line 855, in __call__
	outputs = self.fn()
    ValueError: Dimension 0 in Rebroadcast's input was supposed to be 1 (got 0 instead)
    Apply node that caused the error: Rebroadcast{1}(<TensorType(float64, matrix)>)
    Toposort index: 0
    Inputs types: [TensorType(float64, matrix)]
    Inputs shapes: [(0, 0)]
    Inputs strides: [(8, 8)]
    Inputs values: [array([], shape=(0, 0), dtype=float64)]
    Outputs clients: [[if{inplace}(false, Rebroadcast{1}.0, Alloc.0)]]

    Backtrace when the node is created:
    File "/home/tim/dev/Theano/theano/compile/ops.py", line 689, in make_node
	return gof.Apply(self, [x], [t()])

When I investigate the source of the error in pdb:

    ipdb> node = self.fn.nodes[self.fn.position_of_error]
    ipdb> node.outputs[0].clients
    [(if{inplace}(false, Rebroadcast{1}.0, Alloc.0), 1)]
    ipdb> node.outputs[0].clients[0][0].inputs[0].get_value()
    array(0.0)

So it's not like #1318 where the incorrect branch ends up in the grad graph by itself (without the ifelse guard). Here the ifelse node evaluates its true branch even though the condition is false.

Strangely, the error disappears if I remove the update. It also does not occur if I assign that update to some other shared variable instead of to `b`.

**Comment by nouiz** [comment] 2015-10-28 06:38
This is a known issue. Mostly, the inplace operation can trigger the execution of nodes that won't be executed due to the lazy evalution. There isn't a quick fix in Theano for this problem.

It happen that you can re-write the operation to not trigger this. Adding the update will change the graph and what we can do for inplace operation. That is why removing it can change remove/add this error.

**Comment by nouiz** [comment] 2015-10-29 11:53
What aboug using the OpFromGraph and put all the computation specific to one branch in it. That way, it would remove this problem.

Note OpFromGraph don't have a c interface right now, so it would have some extra overhead.

**Comment by lamblin** [comment] 2015-12-17 22:20
Thanks for the report and the code. I'm closing it as a duplicate of #3004.

**Closed by lamblin** 2015-12-17 22:20 UTC
Labels: Crash
