### ISSUE TITLE
Uniform sampling not working when computing test values

### ISSUE THREAD

**Issue by senarvi** [Theano/Theano#5279] opened 2016-11-24 15:21 UTC
When using the new GpuArray backend and `uniform()`, I'm not able to enable some of the debugging functions. If I set `optimizer=None` or `compute_test_value=warn` flag, `mrg_uniform.c_code()` fails in `assert isinstance(node.inputs[0].type, TensorType)`. Here's example code:

Works:
```python
export THEANO_FLAGS="device=cuda0,floatX=float32"
python3 -c 'import theano
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
rng = RandomStreams(23)
u = rng.uniform((12,))
f = theano.function([], u)
print(f())'
```

Assertion error:
```python
export THEANO_FLAGS="device=cuda0,floatX=float32"
python3 -c 'import theano
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
theano.config.compute_test_value = "warn"
rng = RandomStreams(23)
u = rng.uniform((12,))
f = theano.function([], u)
print(f())'
```

Assertion error:
```python
export THEANO_FLAGS="device=cuda0,floatX=float32,optimizer=None"
python3 -c 'import theano
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
rng = RandomStreams(23)
u = rng.uniform((12,))
f = theano.function([], u)
print(f())'
```

**Comment by nouiz** [comment] 2016-11-24 15:25
Thanks for the report. This is a duplicate of https://github.com/Theano/Theano/issues/4916, but your example will be useful to help fix it. Someone was supposed to work on this. I'll poke him to know where he is on this.

**Comment by nouiz** [comment] 2016-11-24 15:25
Follow the other ticket to stay updated on this issue.

**Closed by nouiz** 2016-11-24 15:25 UTC
