### ISSUE TITLE
KnownFailureTest: change them to something else

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2375] opened 2015-01-07 15:00 UTC
This cause to much questions from newcommer. They are used in many case for not implemented feature. We can change them to check that it isn't implement. When we implement them, the tests will be ready we we could just swap the condition.

**Comment by lamblin** [comment] 2015-01-21 19:21
It is true that we should filter them, and make sure that they are all relevant.
However, having some KnownFailureTests is OK, especially since `theano.test` and `theano-nose` will hide them.

**Comment by nouiz** [comment] 2015-01-21 19:25
Currently it continue to happen email on the mailing list related to that.
But I forgot if they used the last release of the dev.

**Comment by abergeron** [comment] 2015-01-22 18:57
The problem is that nosetests doesn't hide them and many people (including
me) still use this directly.

If we could have a way that would not execute those tests when running
under plain nosetests, it might alleviate the problem.

2015-01-21 14:25 GMT-05:00 Frédéric Bastien <notifications@github.com>:

**Comment by lamblin** [comment] 2015-01-23 04:25
I still think the right way is to use theano-nose (or register the KnownFailure plugin by default in the nose config). NumPy uses them, I don't see why we couldn't.
If we find a way to automatically register a nose plugin when theano is imported, why not. But I don't think having to add special cases or decorators to each test that may raise KnownFailure is a viable option.

**Comment by dwf** [comment] 2015-04-07 23:16
@thomasmesnard Any update on this? Accordibh to thr email last week, it is due at the end of this week.

**Comment by thomasmesnard** [comment] 2015-04-13 14:56
Dear @dwf ,

I sent you an email last Thursday but I didn't receive any answer... I found the file in which KnownFailureTest in mentioned but I don't understand very well by looking to this discussion what do you want to do exactly. Would it be possible to have more precise details ?

Thank's a lot,

Best,

Thomas

**Comment by nouiz** [comment] 2015-04-13 15:17
There is many tests that raise KnownFailureTest. Doing this cause problems,
as in some case, they are shown as errors to the user and so, they think
there is a problem with their installation of Theano.

So this ticket is about changing those tests to do something else. Most of
those tests are missing feature in Theano. So we could just change the test
to check that the feature is missing and fail otherwise. That way, when the
feature is implemented, we can just swap the condition and the tests will
be already done.

**Comment by dwf** [comment] 2015-04-13 20:13
@thomasmesnard Sorry, I was juggling a lot last week, and I only noticed your email on Friday near the end of the day.

My understanding from @nouiz is that there are `KnownFailureTests` raised where there is actually a condition not satisfied with the install that is preventing it from working, e.g. some library is not installed, etc. The KnownFailureTests aren't recognized by [nose](https://nose.readthedocs.org/en/latest/) by default so there are a lot of people who are confused by these. One way to handle some of these would be to raise a SkipTest exception (from `nose import SkipTest`) if you test for that library's availability and it is in fact unavailable.

As for where these appear, you'll have to [grep](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_04_02.html) for them. If you have more specific questions about a given test, feel free to post a comment here.

**Comment by nouiz** [comment] 2015-04-13 22:05
Optional libraries not available already generate skiptest. It is missing
feature or optimization that raise KnownFailureTest
Le 13 avr. 2015 16:13, "David Warde-Farley" <notifications@github.com> a
écrit :

**Comment by dwf** [comment] 2015-04-13 23:13
Can you clarify what you mean by "missing features"?

**Comment by lamblin** [comment] 2015-04-14 00:26
Some things were planned, never implemented, but already have tests. For example, there are tests for optimizations that do not exist yet. Also, some pickling tests raise KownFailureTest in DebugMode, because DebugMode is not picklable "yet".

**Comment by thomasmesnard** [comment] 2015-04-16 20:12
Don't  worry @dwf, I totally understand. Thanks for all your reponses.

I understand what I should do but I'm still not sure what should I do with SkipTest. If I understand well, I have to go in each test and add a SkipTest where the test try to find not yet implemented function. Am I right ?

Thanks for everything
Thomas

**Comment by thomasmesnard** [comment] 2015-04-16 20:12
Don't  worry @dwf, I totally understand. Thanks for all your reponses.

I understand what I should do but I'm still not sure what should I do with SkipTest. If I understand well, I have to go in each test and add a SkipTest where the test try to find not yet implemented function. Am I right ?

Thanks for everything
Thomas

**Comment by thomasmesnard** [comment] 2015-04-16 20:12
Don't  worry @dwf, I totally understand. Thanks for all your reponses.

I understand what I should do but I'm still not sure what should I do with SkipTest. If I understand well, I have to go in each test and add a SkipTest where the test try to find not yet implemented function. Am I right ?

Thanks for everything
Thomas

**Comment by carriepl** [comment] 2015-06-30 13:24
Fixed by PR #2789

**Closed by carriepl** 2015-06-30 13:24 UTC
Labels: CCW
