### ISSUE TITLE
Make Theano support numpy 1.12

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5396] opened 2017-01-10 17:03 UTC
See: https://github.com/numpy/numpy/issues/8420#issuecomment-270269649

Many Theano tests are failing with numpy 1.12 rc.

In summary, there seem to be 4 types of errors:

- [ ] TypeError: 'float' object cannot be interpreted as an index errors are from using floats to index arrays, it can probably be fixed in the test by making the dimensions in out_shp integer.
- [x] TypeError: Cannot cast array data from dtype('float32') to dtype('int64') according to the rule 'safe' can be fixed by making the cast explicit, casting="unsafe".
- [ ] TypeError: invalid strides looks to be because of relaxed stride checking.
- [x] That leaves the arctanh errors and I don't know what is going on there.
- [ ] [TypeError](https://travis-ci.org/Theano/Theano/jobs/196714103#L3203): 'numpy.float64' object cannot be interpreted as an index

**Comment by gokul-uf** [comment] 2017-01-11 11:50
@nouiz I'd like to work on this if no one's assigned

**Comment by nouiz** [comment] 2017-01-11 13:54
Maybe someone was working on the first point. So start by the second and third point.

thanks.

**Comment by chinnadhurai** [comment] 2017-01-12 18:07
I have been working on this as part of the CCW. With numpy version, 1.12.0rc2, I am able to reproduce issue 2. Issue 1 and 4 are not reproducible so far. So, I shall fix the errors for issue 2.

**Comment by gokul-uf** [comment] 2017-01-12 18:38
@chinnadhurai you could send a PR for the second issue alone. We could work on this together if you like :)

**Comment by chinnadhurai** [comment] 2017-01-12 19:56
@slefrancois and I fixed issue 2 this morning. Would you be interested in working on issue 3?

**Comment by slefrancois** [comment] 2017-01-12 19:56
I can't reproduce error 1, "float object cannot be interpreted as index".
Also, the arctanh error seems to be a problem with an old glibc.
So we recommend fixing only points 2-3 for now.

**Comment by gokul-uf** [comment] 2017-01-12 20:02
@chinnadhurai, sure!

**Comment by slefrancois** [comment] 2017-01-24 20:41
invalid strides relate to issue #1586

**Comment by slefrancois** [comment] 2017-01-24 22:26
We're going to do a final test by forcing Travis to use numpy 1.12 before closing.

**Comment by chinnadhurai** [comment] 2017-01-27 21:26
numpy 1.12 requires python version 3.4 or higher (issue #4507)

**Comment by rebecca-palmer** [comment] 2017-02-05 22:54
I can reproduce point 1 in Theano 0.8 (TypeError: 'float' object cannot be interpreted as an index), in test_bincountFn (theano.tensor.tests.test_extra_ops.TestBinCountOp) for the uint64 type (only), and can fix it with [here](https://github.com/Theano/Theano/blob/84aa7becb8202ffce38d9fdca3cff2e47d39ae40/theano/tensor/tests/test_extra_ops.py#L138)
-              size = data.max() + 1
+              size = int(data.max()) + 1
I suspect this is because numpy uint64 scalar (i.e. data.max()) + Python int returns numpy float64 (not allowed as an index in numpy 1.12), while for the other integer types it returns the same integer types.

I'd expect this to also work in Theano master, but haven't tried this.

There's also another test failure with Numpy 1.12, which I have [reported separately](https://github.com/Theano/Theano/issues/5494).

**Comment by slefrancois** [comment] 2017-02-06 18:43
Another error related to taking ArgMax of a scalar and returning 0 for all scalars:
https://travis-ci.org/Theano/Theano/jobs/196714103#L3203

numpy.prod(size=()) produces 1.0, but reshape() would warn silently. From 1.12 onward, it became an error.

**Comment by lamblin** [comment] 2017-02-13 05:17
Fixed in #5527.

**Closed by lamblin** 2017-02-13 05:17 UTC
Labels: CCW, Python Code Only
