### ISSUE TITLE
DownsampleFactorMax does not implement R_op

### ISSUE THREAD

**Issue by matthias-k** [Theano/Theano#3904] opened 2016-01-21 14:23 UTC
While trying to calculate a Hessian vector product of a loss function involving max pooling, I came across the following exception which told me to report this to theano:

    NotImplementedError: DownsampleFactorMax{ds=(2, 2), ignore_border=True, st=(2, 2),
    padding=(0, 0), mode='max'} of class DownsampleFactorMax does not implement
    R_op. If this is a theano op, write to the theano-dev mailing list for assistance. If it
    is your own op, implement the R_op method.

I will be happy to help resolving this, if you could give me some advice.

**Comment by nouiz** [comment] 2016-01-21 15:05
I have a PR for that:

https://github.com/Theano/Theano/pull/3587

But I don't have the time to finish it. There was some comments. And it
need a rebase.

**Comment by nouiz** [comment] 2016-02-22 19:46
duplicate of gh-305

**Comment by nouiz** [comment] 2016-02-22 19:46
duplicate of gh-305

**Closed by nouiz** 2016-02-22 19:46 UTC
