### ISSUE TITLE
Investigate and reenable Scan.infer_shape

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3746] opened 2015-12-04 22:02 UTC
https://github.com/Theano/Theano/pull/3709

disable the extra scan infer_shape introduced recently. We have one use case where there is 3 scan with this instead of 2. Maybe this is ok, maybe not. We need to investigate this before enabling again.

**Comment by lamblin** [comment] 2015-12-17 22:57
Closing as a duplicate of #3765, which as a more detailed description.

**Closed by lamblin** 2015-12-17 22:57 UTC
Labels: Scan
