### ISSUE TITLE
"Index out of bounds" in h_softmax() under very specific conditions

### ISSUE THREAD

**Issue by senarvi** [Theano/Theano#5285] opened 2016-11-25 17:09 UTC
It took me quite a while to isolate this bug, because it seems to depend on a lot of things:
- The new GpuArray backend is used.
- Optimizations are *not* disabled.
- The output vector `y` is sliced from a bigger vector `all_outputs` in `givens`.
- The values of the output vector are important.
- The gradient is updated in `updates`.

Maybe someone else is able to compact this code, but this is the shortest example I could come up with:

```python
export THEANO_FLAGS="device=cuda0,floatX=float32,exception_verbosity=high"
python3 -c "import numpy
import theano
from theano import tensor, shared
from theano.tensor.nnet import h_softmax
input_size = 10
batch_size = 4
level1_size = 6
level2_size = 6
output_size = level1_size * level2_size
floatX = theano.config.floatX
all_outputs = tensor.vector('all_outputs', dtype='int64')
W1 = numpy.random.randn(input_size, level1_size).astype(floatX)
W1 = shared(W1)
b1 = numpy.zeros((level1_size,), dtype=floatX)
b1 = shared(b1)
W2 = numpy.random.randn(level1_size, input_size, level2_size).astype(floatX)
W2 = shared(W2)
b2 = numpy.zeros((level1_size, level2_size), dtype=floatX)
b2 = shared(b2)
x = tensor.matrix('x')
y = tensor.vector('y', dtype='int64')
cost = h_softmax(x, batch_size, output_size, level1_size,
                 level2_size, W1, b1, W2, b2, y)
cost = cost.sum()
b1_grad_update = tensor.grad(cost, wrt=b1)
b1_grad = numpy.zeros((level1_size,), dtype=floatX)
b1_grad = shared(b1_grad)
f = theano.function([x, all_outputs],
                    cost,
                    givens=[(y, all_outputs[1:])],
                    updates=[(b1_grad, b1_grad_update)])
x_mat = numpy.random.normal(size=(batch_size, input_size)).astype(floatX)
all_outputs_mat = numpy.arange(20, 25)
f(x_mat, all_outputs_mat)"
```

This is the result of executing the above code:

```
Mapped name None to device cuda0: Tesla K80
PCI Bus ID: 0000:05:00.0
Using cuDNN version 5103 on context None
Traceback (most recent call last):
  File "/.../Theano/Theano-506ae8f/lib/python3.5/site-packages/Theano-0.9.0.dev4-py3.5.egg/theano/compile/function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
IndexError: Index out of bounds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 34, in <module>
  File "/.../Theano/Theano-506ae8f/lib/python3.5/site-packages/Theano-0.9.0.dev4-py3.5.egg/theano/compile/function_module.py", line 886, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/.../Theano/Theano-506ae8f/lib/python3.5/site-packages/Theano-0.9.0.dev4-py3.5.egg/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/share/apps/anaconda/anaconda3-4.1.1/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/.../Theano/Theano-506ae8f/lib/python3.5/site-packages/Theano-0.9.0.dev4-py3.5.egg/theano/compile/function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
IndexError: Index out of bounds.
Apply node that caused the error: GpuAdvancedSubtensor1(<GpuArrayType<None>(float32, (False, False))>, GpuElemwise{IntDiv}[(0, 0)]<gpuarray>.0)
Toposort index: 19
Inputs types: [GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(int64, (False,))]
Inputs shapes: [(6, 6), (4,)]
Inputs strides: [(24, 4), (8,)]
Inputs values: ['not shown', gpuarray.array([3, 3, 3, 4])]
Inputs type_num: [11, 7]
Outputs clients: [[GpuReshape{2}(GpuAdvancedSubtensor1.0, MakeVector{dtype='int64'}.0)]]

Debugprint of the apply node:
GpuAdvancedSubtensor1 [id A] <GpuArrayType<None>(float32, (False, False))> ''
 |<GpuArrayType<None>(float32, (False, False))> [id B] <GpuArrayType<None>(float32, (False, False))>
 |GpuElemwise{IntDiv}[(0, 0)]<gpuarray> [id C] <GpuArrayType<None>(int64, (False,))> ''
   |GpuSubtensor{int64::} [id D] <GpuArrayType<None>(int64, (False,))> ''
   | |GpuFromHost<None> [id E] <GpuArrayType<None>(int64, (False,))> ''
   | | |all_outputs [id F] <TensorType(int64, vector)>
   | |Constant{1} [id G] <int64>
   |GpuArrayConstant{[6]} [id H] <GpuArrayType<None>(int64, (True,))>

Storage map footprint:
 - <GpuArrayType<None>(float32, (False, False, False))>, Shared Input, Shape: (6, 10, 6), ElemSize: 4 Byte(s), TotalSize: 1440 Byte(s)
 - <GpuArrayType<None>(float32, (False, False))>, Shared Input, Shape: (10, 6), ElemSize: 4 Byte(s), TotalSize: 240 Byte(s)
 - GpuFromHost<None>.0, Shape: (4, 10), ElemSize: 4 Byte(s), TotalSize: 160 Byte(s)
 - x, Input, Shape: (4, 10), ElemSize: 4 Byte(s), TotalSize: 160 Byte(s)
 - <GpuArrayType<None>(float32, (False, False))>, Shared Input, Shape: (6, 6), ElemSize: 4 Byte(s), TotalSize: 144 Byte(s)
 - GpuSoftmaxWithBias.0, Shape: (4, 6), ElemSize: 4 Byte(s), TotalSize: 96 Byte(s)
 - all_outputs, Input, Shape: (5,), ElemSize: 8 Byte(s), TotalSize: 40 Byte(s)
 - HostFromGpu(gpuarray).0, Shape: (4,), ElemSize: 8 Byte(s), TotalSize: 32 Byte(s)
 - GpuElemwise{IntDiv}[(0, 0)]<gpuarray>.0, Shape: (4,), ElemSize: 8 Byte(s), TotalSize: 32 Byte(s)
 - TensorConstant{[0 1 2 3]}, Shape: (4,), ElemSize: 8 Byte(s), TotalSize: 32 Byte(s)
 - GpuElemwise{mod,no_inplace}.0, Shape: (4,), ElemSize: 8 Byte(s), TotalSize: 32 Byte(s)
 - <GpuArrayType<None>(float32, (False,))>, Shared Input, Shape: (6,), ElemSize: 4 Byte(s), TotalSize: 24 Byte(s)
 - <GpuArrayType<None>(float32, (False,))>, Shared Input, Shape: (6,), ElemSize: 4 Byte(s), TotalSize: 24 Byte(s)
 - TensorConstant{(4, 1) of 0}, Shape: (4, 1), ElemSize: 4 Byte(s), TotalSize: 16 Byte(s)
 - GpuAdvancedSubtensor.0, Shape: (4,), ElemSize: 4 Byte(s), TotalSize: 16 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - GpuArrayConstant{[6]}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{(1, 1) of 0.0}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 TotalSize: 2516.0 Byte(s) 0.000 GB
 TotalSize inputs: 2148.0 Byte(s) 0.000 GB
```

**Comment by lamblin** [comment] 2016-11-25 19:47
I can confirm the issue, and it still happens with `CUDA_LAUNCH_BLOCKING=1` and in `cuda-memcheck`.
I asked @abergeron to have a look.

**Comment by abergeron** [comment] 2016-11-25 20:09
As far as I can tell this seems to be a casting bug in nvrtc which starts adding random bits to certain values.  I'll try to trace the assembly later.

**Comment by abergeron** [comment] 2016-11-25 20:19
After some more tracing it appears that the strange values were because of incorrect types in printf().  However, for some reason the first element of i appears to be 20 in the kernel, even though it's clearly 3 from outside.

**Comment by abergeron** [comment] 2016-11-25 20:21
Ok I got it, i has an offset and the take1 code doesn't deal with this.  I will have a fix soon.

**Comment by abergeron** [comment] 2016-11-25 20:33
This fixes the problem: https://github.com/Theano/libgpuarray/pull/298

**Comment by senarvi** [comment] 2016-11-25 22:50
That was fast 😮
Thanks!

**Comment by nouiz** [comment] 2016-11-29 13:57
Fixed in libgpuarray. Updated libgpuarray.

**Closed by nouiz** 2016-11-29 13:57 UTC
